### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1003]
```
Cloning the remote Git repository

ERROR: Error cloning remote repo 'origin'

hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/ElektraInitiative/PermaplanT.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:

stderr: fatal: unable to access 'https://github.com/ElektraInitiative/PermaplanT.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Comment by markus2330** [comment]
On v2:

```
mraab@v2:~$ git clone https://github.com/ElektraInitiative/PermaplanT.git/
Cloning into 'PermaplanT'...
fatal: unable to access 'https://github.com/ElektraInitiative/PermaplanT.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
mraab@v2:~$ git clone https://github.com/ElektraInitiative/PermaplanT.git
Cloning into 'PermaplanT'...
```

So the problem seems to be the trailing slash.

But who adds it? In the [build server config](https://build.libelektra.org/job/PermaplanT/configure) it says `https://github.com/ElektraInitiative/PermaplanT`

**Comment by markus2330** [comment]
Also master is already broken because of this for some time: https://build.libelektra.org/job/PermaplanT/job/master/474/console

**Comment by 4ydan** [comment]
maybe some changes to the infrastructure we did @lukashartl?

**Comment by markus2330** [comment]
It would be the TLS setting of GitHub or `git`, so rather unlikely?

Please always document all changes. Did you change something related to Jenkins?

**Comment by 4ydan** [comment]
Master works again.
Maybe the time is not synced properly on the server?
We should probably provide better logs (GIT_CURL_VERBOSE=1, etc..)

~~missing ca-certificates?~~
~~old gnutls and libgnutls package?~~
~~If we want, we could do `git config --global http.sslVerify false` to disable the sslVerify.~~

**Comment by 4ydan** [comment]
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/69115172-96c9-42d6-82c3-81ca84a43ad5)

**Comment by markus2330** [comment]
https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/master/500/pipeline

```
..RRFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRFRRFFFFFFFFFFFFFFFRRRRRR           [100%]R [100%]R [100%]R [100%]R [100%]R [100%]R [100%]F [100%]F [100%]F [100%]F [100%]F [100%]F [100%]

=================================== FAILURES ===================================

___________________________ test_map_already_exists ____________________________

[gw11] linux -- Python 3.10.6 /usr/bin/python3

```

**Comment by markus2330** [comment]
@4ydan I think we need to disable e2e tests until we have a proper solution for #788

**Comment by 4ydan** [comment]
This is what the error says
```
An unstable feature was used.

Erroneous code example:

```
#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
```

If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using [rustup]).

If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:

```
#![feature(repr128)]

#[repr(u128)] // ok!
enum Foo {
    Bar(u64),
}
```

[rustup]: https://rust-lang.github.io/rustup/concepts/channels.html
```

**Comment by 4ydan** [comment]
Pinning the version is also tricky. Changing the typeshare version has no effect and pinning ignore is not possible as its a child dependency of typeshare.
