### ISSUE TITLE
plant name issues

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1006]
### Tasks

 additional name should be shown in:

 - [x] mouse-over text over plants (to be done in #1022)
 - [x] in plants attributes (left bottom toolbar when clicking on plants)

**Comment by markus2330** [comment]
See also https://github.com/ElektraInitiative/PermaplanT/pull/1021 for elaboration on short names (which are currently not needed in plants attributes)

**Comment by badnames** [comment]
> mouse-over text over plants (to be done in https://github.com/ElektraInitiative/PermaplanT/pull/1022)

Implemented in #1022
