### ISSUE TITLE
Timeline two flaky/broken E2E scenarios

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#1007]
### Tasks

#939 did not help.
see [here](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/master/478/pipeline) and also happened already multiple times elsewhere.
Not reproducable on my local machine on windows 10 wsl after running the timeline tests over 10 times, they always passed.

I did not use the bug template for this issue, as I dont think its a frontend bug or any bug that would benefit from the detailed infos of the template.

```
=========================== short test summary info ============================

FAILED steps/test_timeline.py::test_unhide_a_plant_by_changing_the_map_date - AssertionError: Locator expected to be visible

Actual value: None 

Call log:

LocatorAssertions.to_be_visible with timeout 30000ms

waiting for get_by_role("heading", name="Tomato (Solanum lycopersicum)")
```

**Comment by markus2330** [comment]
> I did not use the bug template for this issue, as I dont think its a frontend bug or any bug that would benefit from the detailed infos of the template.

It would be good if you somehow write how we can determine if it is this bug (again). E.g. some significant portion of the error message etc.

**Comment by markus2330** [comment]
It is still flaky:

https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1063/6/pipeline/ (7 was successful)

**Comment by 4ydan** [comment]
These two scenarios were broken:

```
    Scenario: Unhide a plant by changing its added date
        When I change the plants added date to yesterday
        And I change the plants added date to tomorrow
        Then the plant appears

    Scenario: Unhide a plant by changing its removed date
        When I change the plants removed date to yesterday
        And I change the plants removed date to tomorrow
        Then the plant appears
```
See [#1010 ](https://github.com/ElektraInitiative/PermaplanT/pull/1010#issuecomment-1818019707) for more information.

**Comment by markus2330** [comment]
They are not important, you can remove them.
