### ISSUE TITLE
e2e fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1009]
### Steps to Reproduce the Problem

create PR without changes to code

### Expected Result

build passes

### Actual Result

https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1004/5/pipeline

### PermaplanT version

master

### Operating System

Linux

### Browser

any

**Comment by 4ydan** [comment]
This is #1007

**Comment by markus2330** [comment]
ok, changed urgency over there
