### ISSUE TITLE
Transformer rotation handle prevents correct moving of selection

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#1013]
### Describe the Bug

There exists an invisible rotation handle of our transformer on the map.
Even though it provids no functionality, it can be selected:

![transformer-handle_bug](https://github.com/ElektraInitiative/PermaplanT/assets/141152959/5592306d-9987-4e61-8e3b-c3ae60154f56)

Plants can be selected together with that rotation handle:

![transformer-handle_bug(1)](https://github.com/ElektraInitiative/PermaplanT/assets/141152959/a75e1a5b-93bb-46b7-8d5f-e85d9a25b126)

Moving such a selection, i.e. plants together with the rotation handle, will fail in that it resets the moved selection back to its starting position.

### Steps to Reproduce the Problem

1. Select plant(s) together with the (still invisible) rotation handle
2. Move that selection
3. After releasing the mouse to finish the movement, see the selection automatically getting positioned back to its starting point.

### Expected Result

1. Rotation handle is not selectable on the map
2. A moved selection of plant(s) stays put at the new position

### Actual Result

1. Rotation handle is invisible but selectable on the map
2. A moved selection of plant(s) is reset back to the starting position

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Chrome 118.0.5993.89

**Comment by markus2330** [comment]
Very well described, thx! :1st_place_medal:
