### ISSUE TITLE
Improve tooltip wordings of toolbox icons

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#1028]
### Tasks

 - [x] Move all tooltip wordings of toolbox into a single, new JSON file
 - [x] Shorten every toolbox icon's tooltip and check for correct language usage (e.g. _Pflanzenlabels_ is not a german word)

**Comment by markus2330** [comment]
Thx for creating the issue!

"Pflanzennamen anzeigen" could be used instead of Pflanzenlabels.
