### ISSUE TITLE
Enable deletion of plant(s) via DEL shortcut

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#1031]
### Tasks

 - [ ] Selected Plant(s) on the map can be _deleted_ (i.e. not just removed) by pressing the DEL key.
 - [ ] Update the keybinding guideline by adding a concept on how to check if the corresponding layer is active

**Comment by markus2330** [comment]
Thx for creating the issue. If there are more suggestions for key bindings/shortcuts you can simply add all of them here for @danielsteinkogler.
