### ISSUE TITLE
Release 3.5

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#1032]
## Prep for Release

- [x] [Finish release critical task](https://github.com/ElektraInitiative/PermaplanT/milestone/6)
- [x] run external link check (change follow-web-links in book.toml and do `mdbook build`)
- [x] fix _real_ security problems
      unfortunately `npm audit --omit=dev fix` does [too much and too little](https://overreacted.io/npm-audit-broken-by-design/),
      `cargo deny` seems to be more helpful
- [x] check/improve reformatting
- [x] check if all issues labelled `release critical` are fixed
- [x] update mergedDatasets.csv
- [x] Merge PRs (@markus2330)

## Actual Release

- [x] check if all preps are done
- [x] manually test dev.permaplant.net according to protocol
- [x] build <https://build.libelektra.org/job/PermaplanT-Release/>
- [x] git tag -s vX.X.X
- [x] git push --tags
- [x] create release PR to pump versions and new section in Changelog
- [x] write announcement

**Comment by 4ydan** [comment]
We could maybe move
https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/release.md to https://github.com/ElektraInitiative/PermaplanT/tree/master/.github/ISSUE_TEMPLATE and create a new issue template

**Comment by markus2330** [comment]
Thank you for creating the issue!

> and create a new issue template

Yes, good idea, if it helps you please go ahead when you do the release PR.

The only must-have for the release is #1022 (including fixes for key names), #1002 would be very-nice-to-have, but as said, it would be great to merge as many PRs as possible (except of #804, which shouldn't be included for this release).

**Comment by markus2330** [comment]
I think I merged everything that was ready to be included. The refactorings can also be added directly after the release (which is the better moment anyway).

@4ydan So I think everything is up to you now :rocket: (#954 #1003 etc.).

Would be great to get this done asap, so that we can start rebasing the refactoring/testing PRs (@danielsteinkogler @badnames)

**Comment by 4ydan** [comment]
Today I am at work, can release tomorrow.

**Comment by markus2330** [comment]
The version in master is the one that hopefully can be released. :rocket:

**Comment by markus2330** [comment]
@4ydan what is the current status? From my point of view, you can release.

**Comment by 4ydan** [comment]
We released successfully. 🚀
