### ISSUE TITLE
Keybinding concept for MacOS

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1057]
### Tasks

 - [ ] test if modifier keys are also working on Mac OS
 
- event.ctrlKey: Represents whether the Control key (Ctrl) is pressed.
- event.shiftKey: Represents whether the Shift key is pressed.
- event.altKey: Represents whether the Alt key is pressed (Option key on macOS).
- event.metaKey: Represents whether the Meta key (Command key on macOS) is pressed.

### Related Pull request

https://github.com/ElektraInitiative/PermaplanT/pull/994

**Comment by markus2330** [comment]
Thx for creating the issue! When tested please also add it to the guidelines how to use the modifiers properly, so that it will work fine under all OS. In general we should have some redundancy, not all keyboards have a metaKey.
