### ISSUE TITLE
frontend calls /api/seeds/-1 very often

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#1074]
I noticed that there are a lot of calls to the backend for the resource '/api/seeds/-1'.
The id -1 is probably the default for seeds.
I have not yet investigated why these calls happen are made.
The simplest solution would be to block calls from the frontend which are not valid semantically ( there will never be a seed with id -1 )
The more sophisticated solution would be to investigate why these calls are made and fix the problem there.

**Comment by markus2330** [comment]
Thank you for creating this issue!

@badnames do you know anything about it?

Yes, simply block invalid calls makes sense. From time to time we should cleanup broken code which makes invalid calls.

Btw. we should also cleanup `console.log/err` so that logs stay useful.
