### ISSUE TITLE
Timeline: Switch between sliders with arrow keys

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1087]
### Tasks

 - [ ] if a slider of the timeline is selected it should be possible to switch between sliders with ArrowUp and ArrowDown

### Use case

Timeline Single Date Selection

### Related Pull request

#1042

**Comment by markus2330** [comment]
Yes, great idea. Thx for creating the issue :heart: 

What about a shortcut to directly jump to year/month/day?
