### ISSUE TITLE
Timeline: Loading Indicator

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1088]
### Tasks

 - [ ] A loading inicator should be shown when date is changed and data is loaded
 - [ ] Use loading indictor in e2e tests to know when loading is finished

### Use case

Timeline Single Date Selection

### Related Pull request

#1042

**Comment by markus2330** [comment]
Thank you for creating the issue! How should the indication look like? Is it easy to change the cursor? A waiting-cursor would be nice.

As long a date is not selected, it should not be white font with black background.
