### ISSUE TITLE
send email on failed master builds

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#109]
There is currently no obvious indication if the master builds (still) succeeds.

Please:

- [ ] send emails on failed master builds
- [x] (if easily possible) add badge on main README if jobs succeed #521

**Comment by markus2330** [comment]
@fel115 I assigned you as discussed. Ideally emails only get send if master was stable and just got unstable. (And not emails again when it remains unstable).

**Comment by 4ydan** [comment]
So is the desired way to link the issue in the commit and not link it anymore by hand? or either is fine, as long as its linked once?

**Comment by markus2330** [comment]
Better by commits, then it is also in the history. But yes, the most important is that the link exists.
