### ISSUE TITLE
Planting cursor breaks multi placement

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1111]
### Describe the Bug

While the planting cursor is active, a selection rectangle can not be placed, therefore multi placement does not work.

If this issue is already known or is intentionally a feature, please provide a link an close.

### Steps to Reproduce the Problem

1. open a map
2. select a plant to place (tried with tomato)
3. try to drag and drop, see the cursor changing but no selection rectangle spanning

### Expected Result

a selection rectangle spanning.
upon release a bunch of plantings placed inside this rectangle

### Actual Result

nothing happens

### PermaplanT version

master

### Operating System

doesnt matter

### Browser

doesnt matter

**Comment by markus2330** [comment]
Thank you for reporting this problem!

What do you mean with multi-placement?

- one plant after the other, or
- planting an area of plants? (Steps to reproduce indicate it is this form?)

In any case, it is not intended and it would be also great to eventually have regression tests for both forms, as they are fundamental for PermaplanT. As area of plants is currently only a conceptual implementation anyway (and not used by us), it doesn't really need a fix but you can directly go for a correct implementation as discussed.

**Comment by Bushuo** [comment]
@markus2330 Would it be okay to also include a few refactorings in a PR referencing this issue?
I just started refactoring some stuff, especially react query.
Currently it is all over the place and I would really like to introduce the concept of QueryKeyFactories to the codebase.
See here:
https://tkdodo.eu/blog/effective-react-query-keys
https://tkdodo.eu/blog/leveraging-the-query-function-context

**Comment by markus2330** [comment]
Isn't it a bit over-engineering? Which cases are so complex that we need it? Is there any performance impact?

@danielsteinkogler recently refactored most react queries, see #1099, so we should hear his 2cents, too.
#1100 is still to be done, so there it makes most sense to try another approach. @danielsteinkogler what do you think?

**Comment by Bushuo** [comment]
@markus2330 
I don't think it's over-engineering.
In general a connection between related queries is desirable because of how query invalidation refetching and mutations work together inside react query.

creating reusable hooks using this way also makes it more fault tolerant.
it really is a problem if some dependency of the query is not used inside the query key.

I will look at those PRs in the meantime.

**Comment by markus2330** [comment]
If it is more robust and not much more work to do it that way, it sounds fine. :+1: 

But we should take care not to refactor it in one way just to refactor it another way later on :wink: 

Thx for having a look.
