### ISSUE TITLE
Idiomatic React Query

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1117]
In our project it is hard to track where api calls are made from within components and which queryKeys are used.
For this purpose I want to refactor our existing approach to a more idiomatic one making use of QueryKeyFactories, which will help prevent the error of diverging query function parameters and query key.

Example of the error:
```tsx
/**
 * A hook to fetch plants that are available in the current season.
 */
export function useSeasonalAvailablePlants(mapId: number, date: Date) {
  const { t } = useTranslation(['plantingSuggestions']);

  return useQuery({
    queryKey: [mapId] as const,
    queryFn: () => getSeasonalAvailablePlants(mapId, date, 0), // <-- date is not in the query key!!!
    select: mapPageToList,
    meta: {
      autoClose: false,
      errorMessage: t('plantingSuggestions:available_seeds.error_fetching_seasonal_suggestions'),
    },
  });
}
```

Additionally this will help with invalidating queries on a mutation.

For this I propose to group the whole react query custom hooks api in a file that lives alongside the feature.
It is really not that bad to have more than one function in a file.

Please suggest names for the file.
I came up with `<feature>HookApi.ts`
Other options would be `<feature>Queries.ts`

**Comment by markus2330** [comment]
Thx for creating the issue and the PR! Very good job.

Do we still need the non-scalable approach? We should keep our guidelines short.

Is #1100 still to be done? @danielsteinkogler is it clear to you (guidelines of #1118) how to do it consistently with #1118?

**Comment by Bushuo** [comment]
@markus2330
For me it's not needed, but it might ease the entry barrier for new developers. But then again there is a documentation for react query.

**Comment by Bushuo** [comment]
@markus2330 I added the hook api for the map list now. I think #1100 is therefore done.
