### ISSUE TITLE
DrawingLayer: Add Basic Functionality

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1122]
### Tasks

 - [x] Add Drawing Layer in Frontend
 - [x] Allow Drawing of Rectangles, Ellipses and free lines

### Use case

Drawing Layer

**Comment by markus2330** [comment]
Thx for creating the issue! If something is done (e.g. "Add Drawing Layer in Frontend") you can tick the task in the issue.
