### ISSUE TITLE
Drawing Layer: Persist Drawings

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1123]
### Tasks

 - [ ] Drawings have to be stored in database
 - [ ] Create actions so that undo and redo works correctly

### Use case

Drawing Layer

**Comment by markus2330** [comment]
Images endpoints?, #1168

**Comment by markus2330** [comment]
@danielsteinkogler please look through issues, here the title (indicating the issue is done) seems to be inconsistent with the content (talking about image endpoints)
