### ISSUE TITLE
Drawing Layer: Add further shapes

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1124]
Following shapes should be implemented in drawing layer

### Already implemented
- [x] Free drawing
- [x] Rectangels
- [x] Ellipses

### To be implemented

 - [x] Open Bezier Curve/Polygon
 - [x] Closed Bezier Curve/Polygon (with fillings)
 - [ ] Icons/Images

### Use case
Drawing Layer

**Comment by danielsteinkogler** [comment]
@markus2330 
i created this issue to collect shapes that should be implemented in the drawing layer. Please add your wishes here.

**Comment by markus2330** [comment]
The use case should be complete, issues are only to specify details, e.g. that undo also works, data is sent to backend etc.

"Straight Lines" and also "Polygons" separated to Bezier Curve are not needed, one Polygon is enough that can both do straight lines and bezier curves (e.g. shift click to add bezier help points).

Please specify a bit further which buttons etc. you plan to do.

**Comment by danielsteinkogler** [comment]
https://codesandbox.io/p/sandbox/konva-draw-bezier-xhx72i?file=%2Fsrc%2Findex.js

i found an example for a line that can be modified with bezier. maybe we can use parts of it

**Comment by markus2330** [comment]
Yvonne likes it. Especially the highlighting effect is fancy. What is this red thin line?
 If you use other's code, make sure to check the license (must be BSD, MIT or similar) and written in .reuse/dep5.
