### ISSUE TITLE
Timeline performance problem

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#1128]
### Describe the Bug

While working on the heat map I noticed that the editor was unusually unresponsive.
After a short investigation I found out that the timeline is re-rendered after every mouse wheel event (see the attached flame graph bellow), even if only the map should be updated.
Another issue seems to be that the function createDays is called on every render of the component, which I don't think is necessary.

Each event causes ~200ms of delay when panning the map.

### Steps to Reproduce the Problem

Open any map and start moving the viewport using the scroll wheel.
Note: Panning the map using middle click does not seem to cause the issue.

### Expected Result

The map should update responsively with an acceptable frame rate.

### Actual Result

Panning is very slow. Only ~5-10 updates per second can be achieved,

### PermaplanT version

master

### Operating System

Linux 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Browser

Chrome 120.0.6099.71

### Additional info/logs

![grafik](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/cb6d4202-d0a9-41cc-83e8-ec0422ae313a)

**Comment by markus2330** [comment]
Thank you for reporting the problem! Is this issue different to #1121? Can you also check if https://github.com/ElektraInitiative/PermaplanT/pull/1119 fixes the problem?
