### ISSUE TITLE
AreaOfPlants: Amount Indicator

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1138]
<img width="489" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/9990578/1b7c2186-1137-4926-befa-a2977d2006e8">

How about adding a second line in the text representing the size of the field and the size of the plant.

I thought of something similar like in Figma.

**Comment by markus2330** [comment]
Thank you, this is a great idea!

We fully agree about the 1st and 3rd line. Please swap 1st and 3rd, though.

For the second line, as it is constant, it would be better if in the left bottom toolbar: "Spacing: 100 cm" can be shown. Actually in the left bottom toolbar the last planted plant should be shown, see also #1091. (But as Spacing is constant the last plant = current to be planted plant.)

**Comment by Bushuo** [comment]
Thanks for the feedback. It currently looks like this.
I decided to display the number columns in monospace because they change frequently and would move around otherwise.
I also gave the columns fixed width due to the same reason.

<img width="489" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/9990578/8dd3b69d-bfe6-4526-a7c9-4624b3847537">

**Comment by markus2330** [comment]
Yes, great idea with monospace. A few improvements:

1. use centimeters instead of meter so that we don't have a decimal point.
2. right-alignment of each number with 4 digits (area of plants with > 99.9m are rare)

I manipulated the image (only the "c" for the cm" is missing):

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/d40b45a9-d630-43fa-af77-d1e56be1a667)

**Comment by Bushuo** [comment]
@markus2330 I actually was using cm and m, after cm is greater than 100 m was used. But if it is unnecessary, lets just keep cm then.

**Comment by markus2330** [comment]
This is actually an interesting feature. Maybe it is best if we look at it in the PR, is this already possible?
