### ISSUE TITLE
Improve Active Icon Visibility in Toolbar

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1139]
In my opinion, it is very difficult to differentiate between active and non-active tools in the toolbar.

![Image](https://github.com/ElektraInitiative/PermaplanT/assets/16039038/6bd26f87-b791-4d91-a65a-6d87fe082c4f)
![Image](https://github.com/ElektraInitiative/PermaplanT/assets/16039038/d2e25079-26c3-4cc4-a1b5-13e4d6f0a314).

Maybe we should use another visual indicator than just changing stroke color to primary color.

**Comment by danielsteinkogler** [comment]
Idea: change border color and width for active tools:


![Image](https://github.com/ElektraInitiative/PermaplanT/assets/16039038/78dea2eb-cde9-4427-8817-629b6fc820f3)

**Comment by Bushuo** [comment]
Imo additionally using the brighter color `primary-400` would also be better.

**Comment by markus2330** [comment]
@danielsteinkogler thank you for reporting.

We actually think the situation is okay, on our displays the green and gray is easily distinguishable.

Using the border as visual indication for activeness is not a good idea, as it is already used for the selected fields (to work with keyboard, currently only tab, cursor would be nice to have).

**Comment by markus2330** [comment]
A bit greener wouldn't harm, though.
