### ISSUE TITLE
Area Of Plants: Planting Element

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1148]
- [ ] on drag release if at least 2 plantings would be planted -> create an area of plants
- [ ] the area of plants is a rectangle with a different color

# Questions:
- does it make sense that single plantings can be scaled and rotated?
- which color should the area have?

**Comment by markus2330** [comment]
Dear @Bushuo :wave: 

> does it make sense that single plantings can be scaled

Yes, scaling should change the size of the one plant (different to area where it should change the number of plants).

> and rotated?

Yes, would be nice to have the logo of the one plant rotated for visual purposes.

> which color should the area have?

A darker green than the individual plants (you can also make the individual plants lighter if needed to create a difference).

best regards :heart: ,
Yvonne and Markus
