### ISSUE TITLE
Refactor: Plant Layer API

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1153]
Currently the endpoints of the plant layer only support single planting operations.
This requires the frontend to send multiple requests for each planting affected by an operation.
A good example for this is the move action for multiple plantings.
In the editor it looks like all plantings are moved at once, which is the case in the frontend data store, but the data is persisted to the backend one by one, which could cause, in some error case, unexpected behavior.
Also it is not the most efficient approach.

This issue is a proposal for refactoring the plant layer api to a batch processing approach.
Every action would take a `Vec<ActionPayload>` which identifies the planting.
Inside a `Vec<T>` can only be action payloads of the same type `T`.

Overall, I think this would simplify the action code of the frontend, and be a good guidance for new actions following the same approach.

**Comment by markus2330** [comment]
Thank you for writing the proposal!

I assume  #1023 is needed first?

**Comment by Bushuo** [comment]
> Thank you for writing the proposal!
> 
> I assume #1023 is needed first?

I would make this in one PR. Plays hand in hand.

**Comment by markus2330** [comment]
Did you already work on this? We actually now have a good backend team, so I wouldn't see that this task should to be done by you.

**Comment by Bushuo** [comment]
I already talked to @horenso. We will collaborate on this.
