### ISSUE TITLE
Dark mode theme not applied to select menus

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#1163]
### Describe the Bug

All select menus are displayed with a bright background, even though dark mode is enabled.

### Steps to Reproduce the Problem

- Make sure dark mode is selected.
- Go to any page that makes use of select menus.

### Expected Result

Select menus should have the correct theme applied.

### Actual Result

Select menus are displayed with the wrong background color. 
Text is unreadable.

![grafik](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/c9782e60-b98f-44f0-ab12-7271e5a8b329)

### PermaplanT version

current master

### Operating System

Linux FREIMWOERK 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Browser

Version 120.0.6099.199 (Offizieller Build) snap (64-Bit)

**Comment by markus2330** [comment]
Thank you for reporting this problem! I can reproduce. This is a regression, on www.permaplant.net this problem does not exist.

**Comment by markus2330** [comment]
@Bushuo is this issue and maybe also #1166 caused by the Tailwind CSS update?
