### ISSUE TITLE
Landingpage Openstreetmap does not show locations

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1170]
### Steps to Reproduce the Problem

click on the map on the landing page

### Expected Result

that locations of members etc. are approximately shown

### Actual Result

only the map is shown

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by markus2330** [comment]
@danielsteinkogler is this maybe something you can take a look at?

**Comment by markus2330** [comment]
Probably only pictures in NC

**Comment by markus2330** [comment]
Maps/permaplant-map-placeholder.png

**Comment by yvonnemarkl** [comment]
I actually think that "Maps/permaplant-map-placeholder.png" does work. 
Isn't it the jpg that is shown without clicking on the map?

What is missing are the icons once you've activated the map.

**Comment by markus2330** [comment]
Ahh, my misunderstanding. So Maps/permaplant-map-placeholder.png needs updates when we get new members.

But that the plant disappeared is probably due to

e52fd54cbc4399a50022709d0ca97614ad4b84de

where plants.svg was renamed.
