### ISSUE TITLE
Scraper: Separate fetching of german common names and merging of datasets 

### ISSUE THREAD

**Issue by chr-schr** [ElektraInitiative/PermaplanT#1176]
### Issue
Every time `npm run merge:datasets` is run, all German names are fetched from the Wikidata API again.  Fetching and merging should be two distinct steps.

### Related
Related to (but not fixed by) PR #799

**Comment by markus2330** [comment]
Thx for creating this issue! Should we #799 merge first or will you refactor this code anyway (and directly create a PR on top of #799)
