### ISSUE TITLE
Consideration to move away from utoipa

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1181]
Our current api documentation in the backend is done via utoipa.
The process of documenting a new endpoint is currently very tedious and requires a lot of boilerplate.
Errors are easily made by missing something somewhere which results in a broken swagger-ui.
Did I mention the lots of boilerplate?

I was on the lookout for new solutions that integrate well into actix and found this article.
The crate introduced there looks very promising and also looks a lot easier to handle.

https://medium.com/netwo/documenting-api-for-actix-web-b575adb841a1

https://docs.rs/apistos/latest/apistos/

What are your thoughts? 
@horenso @chr-schr @markus2330

**Comment by markus2330** [comment]
Thx for sharing how we could improve.

> requires a lot of boilerplate.

Is it "only" ugly and unpleasant or is it actually taking a lot of time?

> Errors are easily made by missing something somewhere which results in a broken swagger-ui.

Broken at run time?

> The crate introduced there looks very promising and also looks a lot easier to handle.

Thx for sharing! It seems to be a bit premature (at least [one example seems to be wrong](https://gist.github.com/rlebran/2ac1cef65ce210865bd74f3f680f9ca2#file-apistos_simple_app-api-rs-L22)). Or what is your impression?

**Comment by chr-schr** [comment]
Until now I have not made many modifications to the API documentation, so I don't yet share your frustration. Personally I would be fine with either option. 🤷‍♂️

**Comment by markus2330** [comment]
We stay with utopia for now.
