### ISSUE TITLE
Release improvements

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#1196]
I had multiple thoughts so far and Im not sure if we would like to consider some of them.

I was wondering if we would like to have a master and develop branch setup instead of having develop in master.

I found [this](https://github.com/marketplace/actions/release-changelog-builder) interesting github action which might help us with changelogs.  Or [this](https://github.com/marketplace/actions/gh-release) one.

Do we want to have full diffs between the versions like [here](https://github.com/airtai/faststream/releases/tag/0.4.5 ) and maybe also expand the releases and not only do tags.

**Comment by markus2330** [comment]
Thx, great idea, we will use a separate development branch. But we won't use GitHub actions as we migrate to GitLab.
