### ISSUE TITLE
E2E tests fail because of wrong playwright version installation

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#1200]
### Describe the Bug

I have discovered a bug when installing the required packages for e2e testing locally, different versions are installed than in the dockerfile which is pinned on playwright 1.35.0 but in the requirements txt its >=1.25.1 which seems to install something above 1.42

### Steps to Reproduce the Problem

`./install.sh`

`pip list`

observe the packages and also run `e2e.sh` to see that the tests fail.

### Expected Result

tests pass

### Actual Result

tests fail

### PermaplanT version

master

### Operating System

Devcontainer

### Browser

doesnt matter

**Comment by 4ydan** [comment]
It looks like some higher playwright versions have introduced breaking changes to our tests.

**Comment by markus2330** [comment]
Thx for reporting this problem!
Does #1201 fix this issue?

**Comment by markus2330** [comment]
Thank you, well done! :heart:
