### ISSUE TITLE
drawing layer only works on new maps

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1234]
### Tasks

 - [x] migration script to update old maps to include the layer
 - [ ] docu for table drawings missing, see #1206

### Use case

drawing layer

### Related Pull request

#1221

**Comment by horenso** [comment]
Thank you, this was a bad oversight. Indeed, when I create a new map in the commit `e2948faacfed9b7742c2473f0e17a1dcc362fcc7` and then create one map in master, the old map doesn't have a drawing layer.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/41299302/96c61446-78bb-47f3-a13d-bb4bf184f3e1)
