### ISSUE TITLE
plant label missing

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1249]
### Describe the Bug

Eruca und Bergbohnenkraut doesn't have plant label

### Steps to Reproduce the Problem

plant e.g. Eruca und Bergbohnenkraut

### Expected Result

they are shown with plant label

### Actual Result

they don't have a plant label:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/bd68c6fc-130a-4778-a05a-b64fa335e1db)

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by markus2330** [comment]
The name is also broken in the box:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/2a885650-c248-428c-8596-32c6debd0c0c)

Furthermore, the names in German seem to be capitalized wrongly (should be *I*mmergrün), e.g.:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/35cb01e3-6600-42f4-8205-17df77aace3a)

https://de.wikipedia.org/wiki/Gro%C3%9Fes_Immergr%C3%BCn

**Comment by chr-schr** [comment]
@markus2330 
The plant label currently only shows the common name (en/de). I'll use the unique name as a fallback for plants without a common name?

**Comment by markus2330** [comment]
Yes, exactly. Please show the unique name in that case.
