### ISSUE TITLE
Create issues for hydrology layer

### ISSUE THREAD

**Issue by hatchla** [ElektraInitiative/PermaplanT#1253]
### Tasks

Create issues:
 - [x] #1252
 - [x] #1262 
 - [x] #1264
 - [x] #1265 
 - [x] #1266 

### Use case

Hydrology layer (see [Usecase](https://blob.permaplant.net/master/doc/usecases/assigned/hydrology_layer.md))

**Comment by hatchla** [comment]
@markus2330 does this fit your expectation for the issues / the first issue?

**Comment by markus2330** [comment]
LGTM. If all sentences start the same in an enumeration/itemize you can also move the common sentence part before the enumeration/itemize.
