### ISSUE TITLE
Add warn sign for multi-selected plant-areas

### ISSUE THREAD

**Issue by hatchla** [ElektraInitiative/PermaplanT#1271]
When two or more values of one attribute in multi selection are not the same like in the plant date a yellow warning triangle is displayed. This is not the case for hight and neighter width when selecting (only!) multiple areas of plants.

### Tasks

 - [ ]  Adapt the zod validator to warn for different width & height of multiple areas

### Use case

Scenario: User selects two areas that differ in height. The attribute hight does not get a warning triagle but rather after wanting to change something else does not validate the height field and borders it red leading to a disfunction of multiselect+changing attributes.

**Comment by markus2330** [comment]
What exactly is the observable problem here?

**Comment by hatchla** [comment]
> What exactly is the observable problem here?

It is not a problem rather a missing feature that is present in other places: when two or more values of one attribute in multi selection are not the same like in the plant date a yellow warning triangle is displayed. This is not the case for hight and neighter width when selecting (only!) multiple areas of plants. Scenario: User selects two areas that differ in height. The attribute hight does not get a warning triagle but rather after wanting to change something else does not validate the hight field and borders it red leading to a disfunctioning of multiselect+changing attributes.

**Comment by markus2330** [comment]
Thanks for clarifying! :heart:
