### ISSUE TITLE
text is cut on warnings in left toolbar

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1277]
### Steps to Reproduce the Problem

select several plants, hover over warning symbol

### Expected Result

That warning text is readable

### Actual Result

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/c92932ab-aa6a-4d72-bddc-03fe8a2adad9)

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by andreicristian97** [comment]
Analysis of the issue:
As there is no difference in z-index in the components, the order in which the components are rendered determines the "layering". It looks like the tooltip label gets rendered after the base layer of the map, but before the rest of the layers. (See screenshots from Edge's "3D View" Tool).

Simple solution: give a definite z-index value to the tooltip, to be rendered on top of the application.

<img width="952" alt="Capture" src="https://github.com/ElektraInitiative/PermaplanT/assets/46008622/c78afb35-d67e-420d-b03d-a51007d35e1a">
<img width="829" alt="Capture2" src="https://github.com/ElektraInitiative/PermaplanT/assets/46008622/d253e684-2dd9-4d62-aa6a-ce956d1d207a">

**Comment by markus2330** [comment]
Great analysis! Please also document which z-indexes normally should be used/are used for various parts of our application.

**Comment by andreicristian97** [comment]
Currently used z-index values throughout the app, from lowest to highest (as explicitly set in code, or observed in the 3D View coming from external elements):

- BottomStatusPanel (inner Component of BaseStage.tsx, not sure of exact usage) - z-index: 10
- "Leaflet" elements from Openstreetmap (zoom +/- buttons and citation label on bottom right, observed in 3D View) - z-index: 800
- Navbar (comment from component - value chosen to be on top of Leaflet elements) - z-index: 1001
- TransparentBackground.tsx (used for modals) - z-index: 1010
- ModalContainer.tsx - z-index: 1020
- Toast notifications (observed in 3D View) - z-index: 9999

Based on this, some low value could be set for the Tooltip component, to be on top of the map but not interfere with the Modals or Navbar. To be clarified in what context the "BottomStatusPanel" is used, and if the tooltip could conflict with it - and if yes, decide which value should be higher

**Comment by markus2330** [comment]
Great work! Please add a paragraph about this in doc/guidelines/frontend-ui-usability.md so that newly created modal forms etc. are somewhat consistent to current use of z-index (or if there are changes needed, please propose).
