### ISSUE TITLE
concurrent view of drawings not updated

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1278]
### Steps to Reproduce the Problem

- open two windows showing the same map in permaplant
- create a drawing, move a drawing etc...

### Expected Result

that the drawing is created or moved (like it is for plants)

### Actual Result

only the person drawing sees the drawing

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox and Chromium side by side

### Additional info/logs

@hatchla should update the tutorial how to create layers, so that this functionality also works

@Bushuo it is also broken for area of plants

**Comment by danielsteinkogler** [comment]
@markus2330 on https://dev.permaplant.net/ it is working for me: when i draw in my chrome browser i immediately see the changes also in firefox.
i also testet it with @horenso before creating the PR and there it also worked for us.

**Comment by markus2330** [comment]
I also cannot reproduce it anymore, also area of plants work nicely.

Weird is that updating of individual plants worked and only drawing/area of plants stopped working. So the problem cannot've been the Internet connection?

I close it for now unless I find steps to reproduce from an empty map.
