### ISSUE TITLE
db schemata and ER diagram

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#129]
Some thinking needs to be done around how to persist data regarding the gamification use cases. This also includes building a general database schema on user and map data, which then will be extended by gamification data.

- [x] DB schema for map information
- [x] DB schema for user data

**Comment by markus2330** [comment]
See #131, we might consider that some (or all) user data is stored in Nextcloud. (@absurd-turtle)

**Comment by markus2330** [comment]
Can you link your branch/PR with this issue please?
