### ISSUE TITLE
CI fails at mdbook job

### ISSUE THREAD

**Issue by chr-schr** [ElektraInitiative/PermaplanT#1320]
### Describe the Bug

With https://github.com/ElektraInitiative/PermaplanT/issues/1306 now fixed, CI fails at the mdbook job when updating the crates-io registry.

Here are some examples:
PR https://github.com/ElektraInitiative/PermaplanT/pull/1303  [Pipeline](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1303/10/pipeline)
PR https://github.com/ElektraInitiative/PermaplanT/pull/1297 [Pipeline](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1297/5/pipeline)
PR https://github.com/ElektraInitiative/PermaplanT/pull/1298 [Pipeline](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1298/3/pipeline/210)

Error message
```
#14 [builder 7/7] RUN cargo install --git https://github.com/ElektraInitiative/mdbook-generate-summary mdbook-generate-summary --locked
#14 0.286     Updating git repository `[https://github.com/ElektraInitiative/mdbook-generate-summary`](https://github.com/ElektraInitiative/mdbook-generate-summary%60)
#14 0.899   Installing mdbook-generate-summary v0.1.1 (https://github.com/ElektraInitiative/mdbook-generate-summary#39d7f777)
#14 0.912     Updating crates.io index
#14 42.56 error: Unable to update registry `crates-io`
#14 42.56 
#14 42.56 Caused by:
#14 42.56   failed to fetch `[https://github.com/rust-lang/crates.io-index`](https://github.com/rust-lang/crates.io-index%60)
#14 42.56 
#14 42.56 Caused by:
#14 42.56   network failure seems to have happened
#14 42.56   if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
#14 42.56   https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
#14 42.56 
#14 42.56 Caused by:
#14 42.56   SSL error: unknown error; class=Ssl (16)
#14 ERROR: process "/bin/sh -c cargo install --git https://github.com/ElektraInitiative/mdbook-generate-summary mdbook-generate-summary --locked" did not complete successfully: exit code: 101
```

### Steps to Reproduce the Problem

Run CI 

### Expected Result

CI either passes or fails on newly introduced or changed code

### Actual Result

CI fails to complete mdbook job

### PermaplanT version

see linked PRs

### Operating System

Windows

### Browser

Chrome

**Comment by markus2330** [comment]
Thx for this beautiful issue! :heart: 

We already had this issue before, unfortunately nothing showed up when the admin investigated the network.

Does restarting help?

Does it always fail on the same agent?

Can someone reproduce it locally?

**Comment by chr-schr** [comment]
@markus2330 
I tried to fix it by increasing the retry count on network issues and it seems to help: [PR 1332](https://github.com/ElektraInitiative/PermaplanT/pull/1332)

Not sure if that's enough for the time being or @filo14 should take another look

**Comment by chr-schr** [comment]
But logs of the mdbook jobs don't seem to be preserved if successful?

![image](https://github.com/ElektraInitiative/PermaplanT/assets/154217169/626f0b1d-8f44-4ca2-b672-4d9265ce123c)

![image](https://github.com/ElektraInitiative/PermaplanT/assets/154217169/f159b4f8-b069-4717-afcc-2c72c7d9efb6)

**Comment by markus2330** [comment]
Let us reopen if it fails again. Otherwise I think this solution is fine. Network problems are hard to debug.
