### ISSUE TITLE
todo layer use case

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#140]

**Comment by markus2330** [comment]
The last two use cases!

I added them to #1, to keep track when we finished all use cases (next week everything should be reviewed+merged, so it would be great if you can already write it this week.).

As written in #1:

- todo layer: create deck cards in your map
- offline availability (however, maybe notes can also be taken via label layer OR via drawing layer..?)

(@Bushuo this is one more use case that should work offline.)
