### ISSUE TITLE
CI fails: out of disc space

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#149]
PRs currently do not build, e.g. #147

**Comment by markus2330** [comment]
I resized the PermaplanT container (32G+16G), seems to work again.

**Comment by markus2330** [comment]
Back to error: now the disc is completely full, I'll need to do a cleanup.

**Comment by lukashartl** [comment]
Something is really odd. I just cleaned the whole workspace, but:

```sh
rpool/data/subvol-106-disk-0  5.9G  5.9G     0 100% /
```

The 6G (?) disk is full?

**Comment by markus2330** [comment]
Is this for the 100 (jenkins) container? It has a snapshot, so removing data alone does not solve anything, unfortunately removing the snapshot in the UI also does not work 
```
starting worker failed: unable to create output file '/var/log/pve/tasks/C/UPID:pve:0001A202:0B153C5B:641ABD2C:vzdelsnapshot:100:root@pam:' - No space left on device (500)
```

**Comment by lukashartl** [comment]
no, this is the dev container.

**Comment by markus2330** [comment]
It also has snapshots.

**Comment by markus2330** [comment]
@lukashartl are you still working on 106? I think we can unlock and start it again.

**Comment by lukashartl** [comment]
I tried deleting the older snapshot, but Proxmox just gave me the same error...

We could also remove the whole container and set it up again from scratch.

**Comment by markus2330** [comment]
I was able to remove several other snapshots, so we hopefully should be fine for some time now.

I would leave this container now, but create the others (for pr and www) from scratch, and once they work, redo dev later.

**Comment by lukashartl** [comment]
pr is hosted on dev.
But we could also separate it, so we have three containers:

- pr
- dev
- www (prod)

But then i would definitely shrink dev again :)

**Comment by markus2330** [comment]
Yes, please 3 separate containers.
