### ISSUE TITLE
improving the landing page

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#152]
- [x] "BE GOOD TO YOUR PLANTS" -> "make your garden fruitful|diverse|colorful|practical|useful|abundant" in one line using  https://github.com/tameemsafi/typewriterjs
- [ ] fix margins (Giancarlo)
- [ ] for logo it is best if we make a session together
- [ ] Responsive hamburger menu for Navbar (Giancarlo)
- [ ] from "Why?" we like the first high-lighting variant most
- [x] the seeds page is now different (it is stretched)
- [x] dark mode
- [x] mouse-over bold text makes weird changes in layout (better don't make bold or use font where bold has same font metrics)
- [x] navigational elements (gallery map) must be at the top to be useful?
- [x] Who uses? should have our addresses (for us point to Unterfrauenhaid)

**Comment by absurd-turtle** [comment]
> from "Why?" we like the first high-lighting variant most
I added different styles of highlighting to make it look more interesting. If unified highlighting is preferred I will change it. The layout shifts are fixed now.

**Comment by absurd-turtle** [comment]
> "BE GOOD TO YOUR PLANTS" -> "make your garden fruitful|diverse|colorful|practical|useful|abundant" in one line like https://www.libelektra.org/home
Shall I create this typing animation or is there something I can use?

**Comment by markus2330** [comment]
If it is possible for you can copy it from libelektra.org. It has the same license.

**Comment by absurd-turtle** [comment]
Is there a repository for the libelektra.org website?

**Comment by markus2330** [comment]
Of course: https://github.com/ElektraInitiative/libelektra/blob/466ad7da551ae5fcccc59924d08c1837d2d1aa17/src/tools/website/public/pages/main/website/home.html#L3-L9

**Comment by markus2330** [comment]
I think it might be angular-typewriter so it probably won't help us?

**Comment by buenaflor** [comment]
there is https://github.com/tameemsafi/typewriterjs that you can use if you want to consider having a typewriter effect @absurd-turtle

**Comment by buenaflor** [comment]
> Responsive hamburger menu for Navbar

@markus2330  is there anyone specific taking care of this? If not I can also take a look at the navbar

**Comment by absurd-turtle** [comment]
> > Responsive hamburger menu for Navbar
> 
> @markus2330 is there anyone specific taking care of this? If not I can also take a look at the navbar

@buenaflor I don't think so, I added it. If you want to implement it, please go ahead :)

**Comment by markus2330** [comment]
@buenaflor yes, that would be great.
