### ISSUE TITLE
Decision: Which ORM/SQL crate do we want to use in the backend.

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#170]
Currently we are using diesel as our ORM in the backend. There are other options such as `diesel_async`, `sea-orm` or simple sql crates like `sqlx`. Maybe one of them is a better fit for us.

**Comment by markus2330** [comment]
Please make sure to properly describe why an async ORM might be faster than simply using web::block.

I added this issue to #2 to track all decisions.

**Comment by kitzbergerg** [comment]
I don't think async will be faster. I'll push a PR soon.
