### ISSUE TITLE
Feasibility study - PostGIS & QGIS

### ISSUE THREAD

**Issue by NurramoX** [ElektraInitiative/PermaplanT#176]
Feasibility study about the following things:
 - a table that has 5D data (x,y,z,time,alternative)
 - project that data onto a 2D map
 - open QGIS and visualize that data
 - is rasterization possible?
      - which boxes are hatched
 - use Rust Diesel library to make spatial sql queries for PostGIS database

**Comment by markus2330** [comment]
Please use `- [ ]` and indicate which parts were already done? (E.g. did you already open QGIS? Did you already work with postGIS?)

The main goal of the feasibility study is that we have a working PostGIS implementation that can give a 2D representation of a 5D data.
