### ISSUE TITLE
pre-commit hook for database

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#179]
> @markus2330 
> What do you think about adding another pre-commit hook for SQL files?
> https://sqlfluff.com/
> Haven't used it before but it looks interesting.

_Originally posted by @Benjaminimal in https://github.com/ElektraInitiative/PermaplanT/issues/175#issuecomment-1487560392_

**Comment by markus2330** [comment]
If it works well, it would be great to have!

**Comment by Benjaminimal** [comment]
Ok, I'll start working on it when this PR is merged.
https://github.com/ElektraInitiative/PermaplanT/pull/160

**Comment by markus2330** [comment]
I moved this back, as it is probably easier to introduce the reformatting with #206. Or did you have different plans?

**Comment by Benjaminimal** [comment]
Sure we can delay it until this is done.

**Comment by markus2330** [comment]
Implemented and working!
