### ISSUE TITLE
Review and update plant details

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#192]
Implement a details page for plant attributes and a form to submit updated information on that plant. 
Fulfills use case ["plant reviews"](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/review_plant.md).

**Comment by ThorbenStaufer** [comment]
@markus2330 should this also be provisionally placed as it's own route like the seeds use case? Additionally, should all information on the plant be displayed and be editable or only a subset?

**Comment by markus2330** [comment]
> @markus2330 should this also be provisionally placed as it's own route like the seeds use case?

This is an implementation detail and not necessary to be written in a use case.

> Additionally, should all information on the plant be displayed and be editable or only a subset?

Only a small subset, mostly the things which were created specifically for PermaplanT (e.g. is_tree, companions).

**Comment by ThorbenStaufer** [comment]
> This is an implementation detail and not necessary to be written in a use case.
I thought I was assigned to implement this use case as part of this weeks tasks, at least thats what we talked about on Tuesday. And in that case I do need implementation details.

**Comment by markus2330** [comment]
No, this is an misunderstanding then. This week is for you "only" about:

- finalizing the use cases itself
- DB/ER Diagram
- Colors in Frontend
- Mockups (iirc 3 week deadline from last Pavlo meeting)

Together with the other stuff everyone needs to do I think it is more than enough :+1:

**Comment by ThorbenStaufer** [comment]
Ok, then i'm sorry for the misunderstanding. I will immediatelyshift focus to the other tasks.

**Comment by markus2330** [comment]
This issue still doesn't have importance, I'll close it.
