### ISSUE TITLE
use https://tailblocks.cc elements for landingpage

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#193]
From https://tailblocks.cc we like:

- [x] C in Blog without CATEGORY
- [x] C in Feature (but without big picture on the left)
- [x] A in Testimonials
- [x] B Pricing with one column less
- [x] B of CTA
- [x] A in Team
- [x] C in Contact

Can you add it for us to the landing page please?

**Comment by buenaflor** [comment]
on it 👍

**Comment by markus2330** [comment]
Yes, you can leave dummy data for now! :rocket:

**Comment by markus2330** [comment]
Great job, all done here.
