### ISSUE TITLE
document colors

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#194]
We like #7EA15E (Asparagus)

![image](https://user-images.githubusercontent.com/7949075/228907460-5ba2234b-9f65-4951-9062-d5730c068c97.png)

Triadic:

![image](https://user-images.githubusercontent.com/7949075/228907656-59bb7d49-5363-4f50-902d-a7bab272bcd7.png)

Shades:

![image](https://user-images.githubusercontent.com/7949075/228907934-fcb16c45-acb8-4810-b08e-1c38a5d7e91e.png)

Tints:

![image](https://user-images.githubusercontent.com/7949075/228907993-4f519d11-c5c4-4dbf-b2ea-65ffa0520a88.png)

**Comment by ThorbenStaufer** [comment]
Samuel and I already created a few color theme propositions we wanted to show tomorrow. Should I include Asparagus as an option or replace the others with it?

**Comment by markus2330** [comment]
You can simply show us what you have.

**Comment by ThorbenStaufer** [comment]
We put them into the frontend CSS to directly see them in action, but I can create some screenshots of the color palette as soon as I am done with cooking and the dishes if you want me to document them here in the issue.

**Comment by ThorbenStaufer** [comment]
## Variant 1:
### Primary
![image](https://user-images.githubusercontent.com/101188734/228938158-e02bc27e-1b2b-417a-bb6d-14143d71e0c1.png)
### Secondary
![image](https://user-images.githubusercontent.com/101188734/228938256-2592a496-f150-4cbf-97aa-5f1ecce75b1a.png)
### Neutral / Background
![image](https://user-images.githubusercontent.com/101188734/228938447-a783d555-57be-4280-a040-a3a872a596d7.png)

**Comment by ThorbenStaufer** [comment]
## Variant 3:
### Primary
![image](https://user-images.githubusercontent.com/101188734/228941529-5ee9a15b-ac87-422c-af5d-aa5921532dfa.png)
### Secondary
![image](https://user-images.githubusercontent.com/101188734/228941663-aa2555c1-9366-47f4-b626-4e05ea916955.png)
### Neutral / Background
![image](https://user-images.githubusercontent.com/101188734/228938447-a783d555-57be-4280-a040-a3a872a596d7.png)

**Comment by ThorbenStaufer** [comment]
## Variant 4:
### Primary
![image](https://user-images.githubusercontent.com/101188734/228941539-b50b460b-2cc1-4190-9b28-5826634243df.png)
### Secondary
![image](https://user-images.githubusercontent.com/101188734/228941674-022db276-7622-4155-8b53-f6f419592c4d.png)
### Neutral / Background
![image](https://user-images.githubusercontent.com/101188734/228941209-66c0747e-ba01-48ef-b1b9-b0d9e6d67aca.png)

**Comment by ThorbenStaufer** [comment]
Variant 4 is also the one that is currently set in the frontend.

**Comment by markus2330** [comment]
Left here is to document at one place how someone should choose which color to use.

**Comment by markus2330** [comment]
@ThorbenStaufer The place is doc/guidelines/ui.md, you can push to #425

**Comment by ThorbenStaufer** [comment]
Documentation on color theme usage is now part of #425.

**Comment by markus2330** [comment]
Thx, great job!
