### ISSUE TITLE
unknown error when adding seeds

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#195]
When pressing okay on a filled out seeds form:

![20230330_151854](https://user-images.githubusercontent.com/7949075/228912474-41bf93a4-4c76-42f5-bee2-eb2cea7afee8.png)

**Comment by buenaflor** [comment]
That's one of the reasons why I initially added the `ResponseBody` so we can attach messages to error responses as well which is helpful for things like this. Now we only receive an error code but the user would have no idea what the error might be. 

However it got removed some time ago.
