### ISSUE TITLE
check konva features

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#199]
After #196, so that we don't forget:

- [x] drawing SVG on canvas (tomato), does it bring benefits when zooming?
- [x] rectangle with information next to the cursor while changing rectangle size (drawing of areas) [we discussed this already longer time ago]
- [x] can drawing rectangle jump between fixed sizes (for drawing plants)

**Comment by buenaflor** [comment]
**Investigation**:
>  drawing SVG on canvas (tomato), does it bring benefits when zooming?

Definitely, was expected but I still tested it and zooming in on svg does not diminish the quality. I assume this is the case for any vector graphic, not just svg.

> rectangle with information next to the cursor while changing rectangle size (drawing of areas) [we discussed this already longer time ago]

Yes, possible

> can drawing rectangle jump between fixed sizes (for drawing plants)

Yes, possible. See: https://codepen.io/pierrebleroux/pen/gGpvxJ
We can "snap" the rectangle to a grid

**Comment by markus2330** [comment]
Thank you, great job!
