### ISSUE TITLE
Database Schemata

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#20]
Nicht-Optional:
- Kategorie
- Art
- Sorte
- Erntejahr

Geschmack: Text, meistens 1-5
Ertrag: Text, meistens 1-5
Qualität: Bio, Nicht-Bio, unbekannt

```
Kategorie    Art        Sorte        Erntejahr    Verbrauch Bis    Herkunft    Geschmack    Ertrag        Menge    Qualität    Preis    Generation        Notizen
Fruchtpflanzen    Tomate        Grün gemasert        2022                Loase            3    3        1    unbekannt        -            unbekannt ob grün, da nicht ausgereift
Blattpflanzen    Feldsalat    Verte a coeur plein 2    2021        Dez 2024    Spar Natur        nussig    1        1    Bio        2,99    0
Blattpflanzen    Zichoriensalat    Zuckerhut        2020        Dez 2023    Billa                        175    Bio            0            gut Lagerfähig
```

(Offen: Favorit)

Sortendatenbank (draft):
```
Pflanzen:
Kategorie	Art	Synonym		Aussaat		Saattiefe	Keimtemperatur	Pikieren	Verpflanzen		Reihenabstand	Pflanzenstand	Keimzeit	Erntezeit		Standort	Pflege	Höhe
```

**Comment by markus2330** [comment]
Categories are (German - English):

- Blattgemüse - leaf crops
- Fruchtpflanzen - fruit crops
- Wurzelpflanzen - root crops
- Blütenpflanzen - flowering crops
- Kräuter - herbs
- Sonstiges - other

Several categories per plant are possible, so it is actually rather tags and not categories.

**Comment by buenaflor** [comment]
If a seed has a reference to a "sorte" (which has the categories/tags), isn't the category in the seed table redundant?

**Comment by markus2330** [comment]
The idea of this duplication is that people can correct in their seed database what they don't like in our variety database (Sortendatenbank). E.g. broccoli some people think of as fruit crop even though it is a flowering crop.

**Comment by markus2330** [comment]
With the same principle actually everything should be duplicated. In the seeds database everything can be empty though (take as written in the variety database).

**Comment by markus2330** [comment]
First version of varieties DB will be based on https://practicalplants.org/wiki/practical_plants/
