### ISSUE TITLE
seed/searching issues

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#209]
- [x] there should be a way to load further plants (if search is too generic and more than one page is available)
- [x] clicking on plant name field sometimes resets text
- [ ] search for German names does not work

**Comment by badnames** [comment]
A copy of the comment I left on on onother PR regarding searching for German and English names at the same time:

> I have thought a bit about this over the past few days and came to the conclusion that we probably shouldn't search by German and English common names at the same time.
> 
> As a user, I would personally find it very confusing if I started typing "fi" and suddenly spruces (or "Fichten" in German) showed up in the search results, when I actually wanted to find firs. In my opinion it would probably be better to add some mechanism to select which type of common name should be searched for. Preferably depending on the chosen interface language.
> 
> If you want us to implement the search this way none the less we should at least show the German common name beside the English common name.

**Comment by markus2330** [comment]
see [update of use case](https://github.com/ElektraInitiative/PermaplanT/pull/251/files#diff-ffcf3684203226512e824186cca963094610c83f56ecdffd18393acf5c281600)

**Comment by badnames** [comment]
@markus could you please verify if the second bullet point is already fixed in #246?
I've just been testing it locally and were not able to recreate it.

**Comment by markus2330** [comment]
I don't know if it is "broken" but it is still there:

- I type something, e.g. `pa`
- I press **next** to the word `pa` within the "plant name" field
- `pa` is gone.

Is it on purpose that Pos1+End refers to the selection? It seems to be the same as page up/page down. Can we maybe use Pos1 and End to refer to the text (jump with cursor to beginning or end).

These problems are very minor, they don't need to be solved for this release.

German search, however, is needed that Yvonne can actually enter seeds.
