### ISSUE TITLE
mockups

### ISSUE THREAD

**Issue by buenaflor** [ElektraInitiative/PermaplanT#21]
- [ ] plant use case (@buenaflor)
- [ ] gamification (@ThorbenStaufer)
- [x] insertion into list of which seeds the user has

**Comment by markus2330** [comment]
Feedback to #25: We are very happy with the general layout and style. We noticed:

- [ ] mark which fields are mandatory (* after text)
- [ ] Can we use (only) a dark mode instead? (It saves energy)
- [ ] Can we have the layout in a way that it layout elements don't move when something opens or "Erforderlich" gets added
- [ ] "Verbrauch Bis" needs to be editable (date selection)
- [ ] Sorte also should have "Unknown" (used by default)
- [ ] left above must be "Erntejahr", then "Kategorie", then "Art", then "Sorte"
- [ ] Erntejahr -> Bezugsjahr
- [ ] Verbrauch Bis -> Verbrauch bis
- [ ] Menge+Qualität should be before Geschmack
- [ ] Art -> also to be selected from database (Constrainted by "Kategorie")
- [ ] Not all "Kategorien" are listed?
- [ ] Generation could have a + button for increment number
- [ ] "Abbrechen" needs confirmation if there was already a change (please also add to use case)
- [ ] Menge should be enum (Genug, ...)
- :+1: tab order is quite obvious (last items: Preis -> Generation -> Notizen -> Eintragen -> Abbrechen)

Please update the Mockups

**Comment by buenaflor** [comment]
> Art -> also to be selected from database (Constrainted by "Kategorie")

Wouldn't Art be the name field in the seed table?

>  Can we have the layout in a way that it layout elements don't move when something opens or "Erforderlich" gets added

Yes, layouts shouldn't move. I think there should be enough spacing between the layouts so any additional information text underneath shouldn't affect other rows.

**Comment by buenaflor** [comment]
> Erntejahr -> Bezugsjahr

In the seed db this is currently `harvest_year`, should this be changed as well?

**Comment by markus2330** [comment]
> Wouldn't Art be the name field in the seed table?

Yes, "Kategorie, Art und Sorte" all three together decide about the reference to the varieties database.

> In the seed db this is currently harvest_year, should this be changed as well?

Good hint. Lets better stay at "Erntejahr" and harvest_year.

**Comment by markus2330** [comment]
But you can keep it for now. We need hint texts what exactly is meant anyway. (Sometimes the exact harvest year is not known, then you take the time when you got the package, instead).

**Comment by markus2330** [comment]
In #28 are many and great improvements.

- Blattpflanze filled out in mockup should be Blattpflanzen
- Kategorie: multiple points must be selectable
- Generation should have the "+" (not Ertrag)
- Menge: "quantity NOT NULL" -> must have red star *
- Menge: should be moved up
- Saatgut -> Neuer Eintrag

As the problems are minor, I don't think a new mockup is needed.

**Comment by markus2330** [comment]
Looking forward to mockups for main "menu" and maps/layer.

**Comment by absurd-turtle** [comment]
@buenaflor Is the newest mockup you presented in the last meeting available somewhere?
