### ISSUE TITLE
Migrate To React Query

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#213]
Now that #35  is finished we should refactor to react-query like mentioned in #111.
This will give us a good foundation for future reference.

All the stores that use server-side state should be refactored.
- [ ] refactor CreateSeedStore
- [ ] refactor FindSeedStore

**Comment by Bushuo** [comment]
@markus2330 I would like to tackle this issue.

**Comment by markus2330** [comment]
Thank you for creating the issue and volunteering. I assume we should do this after the release, or is this a small thing?

Before the release, however, we should fix #212. Will some linting errors go away by this refactoring?

**Comment by markus2330** [comment]
What is the status of this issue?
