### ISSUE TITLE
prepare scraper for CI

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#217]
To do  #211 it actually it would be better if plants table gets cleaned within the scraper, so that the scraper does in one transaction:

- [x] remove everything in plants table
- [x] add all the plants

Further features:

- [x] removing&inserting of all plants must be within one transaction
- [x] the merge tool should be extended to merge permapeople and reinsaat (next to practicalplants)
- [x] as extra feature, only the changed plants should be fetched from permapeople (full fetch should be available, too)
- [x] as the practicalplants output is always the same, it doesn't need to be redone on the CI
- [x] insert order into DB should stay stable

# EDIT 09.04.2023

Since the merging and insertion of the data will be the same for all the scrapers, this issue will be a logical followup of #230 and #231

**Comment by markus2330** [comment]
@aidnurs as there maybe is confusion about the transaction, I summarized above all the features the scraper finally should have (should be nothing new, everything was already said somewhere):

- [ ] removing&inserting of all plants must be within one transaction
- [ ] the merge tool should be extended to merge permapeople and reinsaat (next to practicalplants)
- [ ] as extra feature, only the changed plants should be fetched from permapeople (full fetch should be available, too)
- [ ] as the practicalplants output is always the same, it doesn't need to be redone on the CI (probably nothing to be done by you, as long as parsing practicalplants stays as an extra command)

**Comment by markus2330** [comment]
Last but not least (was already the case so far):

- [ ] insert order into DB should stay stable

This might actually need consideration for permapeople and reinsaat, maybe even en extra table with all known plants so far?

**Comment by aidnurs** [comment]
Hey guys @markus2330 @yvonnemarkl ,

which column names would you prefer on the overlapping values e.g. `light_requirement` from permapeople vs. `sun` from practicalplants?

**Comment by markus2330** [comment]
We will add this to the same PR describing the mapping.
