### ISSUE TITLE
manual testing seed entry

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#221]
Please report here how adding seed entries worked for you

**Comment by Benjaminimal** [comment]
![image](https://user-images.githubusercontent.com/23339978/230905836-18df70d2-ed4e-4002-95ee-765f32c897ae.png)
![image](https://user-images.githubusercontent.com/23339978/230905927-4fefc10f-c4a1-44ba-be4c-9cced0b38499.png)
The seeds list contains a dummy entry with a non-existing plant.

![image](https://user-images.githubusercontent.com/23339978/230906197-b3ec46d2-6f5e-43ed-bf69-3b8259ad4476.png)
I can't add a new seed as there are no plants found.
Not sure if the database is empty or the search not working.
Seems like it's the former.
```
curl https://dev.permaplant.net/api/plants
[]
```

**Comment by markus2330** [comment]
Yes, on our dev/pr instances the data is unfortunately not yet imported, see #211

**Comment by aidnurs** [comment]
I was testing it with the plants data, so it worked very well. Great job!

 I have just a few non-technical notes:
- the color of the plant name is dark and inconsistent with the rest of the fields
- additional validation for the harvest year(negative numbers allowed)? the rest was decent!

![Screenshot 2023-04-11 at 21 12 11](https://user-images.githubusercontent.com/28778542/231265632-659070f4-ee56-486f-9abb-532d679042ff.png)
