### ISSUE TITLE
Document the bootstrapping of the application

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#237]
Please document somewhere how the bootstrapping of the application works (which is done in which order).

look at `main.tsx` and go from there.
There are some module loading side effects in the `config`.

_Originally posted by @markus2330 in https://github.com/ElektraInitiative/PermaplanT/pull/235#discussion_r1158666200_

**Comment by markus2330** [comment]
This was somehow forgotten. Is this difficult to investigate? I initially thought that you will only write down what you already know. Same for #270.
