### ISSUE TITLE
seeds entry broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#239]
![image](https://user-images.githubusercontent.com/27735433/230178561-298f020a-f496-4c39-a80b-de2101a11c10.png)

I'm currently getting this error message when I open the seeds page. Unfortunately there is no console message or networking error that I could share.

_Originally posted by @badnames in https://github.com/ElektraInitiative/PermaplanT/issues/221#issuecomment-1497975924_

**Comment by markus2330** [comment]
I can reproduce it. Is this maybe some problem introduced by  #220?

@Bushuo or any other idea?

**Comment by Bushuo** [comment]
> I can reproduce it. Is this maybe some problem introduced by  #220?
> 
> 
> 
> @Bushuo or any other idea?

@markus2330 
I think it has to do with how the url is generated for the backend requests.
It works locally because the env variable is set to `localhost...` but on CI it is set to an empty string.
I guess we have to change the code in features/seeds/api

**Comment by Bushuo** [comment]
https://github.com/ElektraInitiative/PermaplanT/blob/fa64bbae226136592d112e83fd93bb08e2761acd/frontend/src/features/seeds/api/createSeed.ts#L8

`baseApiUrl` is an empty string in CI
