### ISSUE TITLE
graceful shutdown timeout

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#247]
On the usual signals (TERM, HUP, ...) the backend should gracefully shut down:

- [ ] already started API calls should be finished
- [ ] new API calls should be terminated with "retry later"
- [ ] signals and behavior should be documented
- [ ] there should be a test case that demonstrates that API calls get finished (e.g. introduce an API call that simply waits a second or so)

**Comment by kitzbergerg** [comment]
@markus2330 Actix handles signals by default: https://actix.rs/docs/server/#graceful-shutdown. 
Should I somehow modify this or write it in the documentation (I believe most modern http servers do something like this so I'm not sure if explicit documentation is necessary)

**Comment by markus2330** [comment]
Great, so copying your linked text block, with fixing the correct numbers (e.g. which amount was configured by the shutdown_timeout() method.) into our documentation should fix most of this issue.

Of course it needs a bit testing, especially if "retry later" error codes will be emitted.

**Comment by kitzbergerg** [comment]
I'm still quite confused what I have to test here.


Actix by default handles shutdowns.
This means that as soon as the signal SIGTERM (it has to be SIGTERM, SIGINT meaning ctrl+c doesn't work) is issued no new connection will be accepted. Still running connection will be finished (or terminated if they take longer than 30sec). The only thing I can configure is how long to wait until running connections are forcefully terminated.
I tested this behaviour locally.

No new connections means that it acts as if there was no backend at all which means that there isn't really anything to test in the backend (at least not automatically). The only testable thing is if the frontend handles the missing backend correctly (meaning it outputs an error message).
Currently it just attempts again and again: 
![image](https://user-images.githubusercontent.com/33102273/233835261-fdda728a-2337-4546-a2a1-27e4fa688929.png)
But then again that should be handled by the frontend guys.


Where should I add the behaviour of SIGTERM/SIGINT? It doesn't really fit in backend architecture, but creating a new directory just for this shutdown behaviour seems unnecessary.

**Comment by markus2330** [comment]
I think we can reduce to 5 sec, as for all calls a user is waiting.

I think it is fine in the architecture, it is not an implementation detail how you can terminate the application and which time constraint API calls have. And we are speaking here about 3-4 sentences. So simply add it to #307.

The test is perfect, nothing else needs to be checked.

**Comment by kitzbergerg** [comment]
> I think we can reduce to 5 sec, as for all calls a user is waiting.

Unless there is a specific reason to set it I would just leave it at the default of 30sec. That way if for some reason something goes wrong the server has some time to act. It keeps the complexity of the backends code lower as well if we leave the default.
