### ISSUE TITLE
get images+csv from Nextcloud

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#248]
As discussed, we want Apache to share files from Nextcloud. This should be both for

- images (in folder PermaplanT/Public), and
- csvs (in folder PermaplanT/Database)

@aidnurs As we already have the data in Nextcloud, let us **only** use the data (csv) from Nextcloud and not add the csv in our repository anymore. (Please remove from PRs.)

**Comment by markus2330** [comment]
This was not yet in project, I added it as it is release critical and actually even needed for #211.

**Comment by lukashartl** [comment]
I think we could use the [Nextcloud Command Line Client](https://docs.nextcloud.com/desktop/latest/advancedusage.html#nextcloud-command-line-client) to fetch these two folders.

How often should we run the sync process (synchronously with the command line client)? once an hour?

We don't need all of them on all instances:

* images (in folder PermaplanT/Public) : on PR, Dev, Prod
* csvs (in folder PermaplanT/Database) : only on PR

How should the images be accessible? `PermaplanT/Public = https://HOSTNAME/assets`?

**Comment by markus2330** [comment]
> I think we could use the [Nextcloud Command Line Client](https://docs.nextcloud.com/desktop/latest/advancedusage.html#nextcloud-command-line-client) to fetch these two folders.

Yes, that would be a possibility. To do actual (ro) mountpoints, however, would have the advantage that the data isn't duplicated several times. It is already > 100MB.

> How often should we run the sync process (synchronously with the command line client)? once an hour?

If the command-line client is used we only need to make sure that the process is still running. No cronjob would be needed then.

> csvs (in folder PermaplanT/Database) : only on PR

Better to have them everywhere (for manual re-imports).

**Comment by markus2330** [comment]
I think this can be closed? It seems to work for pr.permaplant.net and for the others it is not really needed (I can manually sync the file for the import).

Please reopen if there is something else.
