### ISSUE TITLE
privacy/Datenschutz page

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#256]
Additional to imprint/impressum we also need privacy/Datenschutz

**Comment by ThorbenStaufer** [comment]
@markus2330 Is this issue still in scope for my contribution at PermaplanT or should I unassign it?

**Comment by markus2330** [comment]
Yes, please add some information, also for the user study.

**Comment by markus2330** [comment]
probably we won't do it after all and instead send some information in advance
