### ISSUE TITLE
map/layer database layout

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#257]
Takeover PR from @ThorbenStaufer  to design all layers etc. as needed for map

**Comment by NurramoX** [comment]
In which directory should I add my sql examples? I would suppose in the database directory from the guidelines that is yet to be merged. What do you think @markus2330 ?

**Comment by markus2330** [comment]
> In which directory should I add my sql examples? I would suppose in the database directory from the guidelines that is yet to be merged. What do you think @markus2330 ?

In a subfolder below doc/decisions there are already other SQL examples.
