### ISSUE TITLE
Provide full text-search for plants

### ISSUE THREAD

**Issue by Benjaminimal** [ElektraInitiative/PermaplanT#258]
To improve searching for plants we want to implement a full-text search.

For details on how it should work see:
- Original discussion.
  https://github.com/ElektraInitiative/PermaplanT/pull/246#discussion_r1161097428
- Use case.
  https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/polyculture/search_plants.md

Postgres full-text search docs.
https://www.postgresql.org/docs/current/textsearch.html

Diesel full-text search.
https://github.com/diesel-rs/diesel_full_text_search
https://docs.rs/diesel_full_text_search/latest/diesel_full_text_search/index.html

**Comment by markus2330** [comment]
Thank you for creating the issue, looking forward to get a proper full-text search!

Authoritative description is in #251, please review if everything is clear.

**Comment by Benjaminimal** [comment]
Yes, looks clear.
I would scope this issue to the matching of names and ranking by them.
No environmental fit and ecological value for now.
Also no matching of extra columns.

**Comment by badnames** [comment]
I have published a draft pull request (#268) so that you can already take a look how things are getting along.

**Comment by Benjaminimal** [comment]
I looked deeper into the postgres full-text search documentation and tried some local queries.
It looks like this is not the right tool for us.
We can only do prefix or exact matching, no substrings on the `tsvector` type.
Provided ranking mechanisms work with the number of occurrences in the searched text.
This is better suited for searching for whole words and stems of it in larger text documents.

I think I will just go with some pre-computed indexed columns and a tailored select statement where I'll have to manually compute the ranking to order based on the language preference and full or partial match.

Anyway, implementing this is blocked for now since it touches parts that were heavily refactored by https://github.com/ElektraInitiative/PermaplanT/pull/276
Also, the column names to search will be renamed as sketched in https://github.com/ElektraInitiative/PermaplanT/pull/274

**Comment by markus2330** [comment]
Thanks for your deep-dive in that topic!

We also can consider dropping the vector if this is the problem (and separate the words differently).

With [tsquery](https://www.postgresql.org/docs/current/datatype-textsearch.html#DATATYPE-TSQUERY) it should work, shouldn't it?

> I think I will just go with some pre-computed indexed columns and a tailored select statement where I'll have to manually compute the ranking to order based on the language preference and full or partial match.

Sounds like a lot of work, doesn't it?

**Comment by Benjaminimal** [comment]
I used `tsquery`.
It doesn't allow substring matching.
E.g. when typing `chten` it would not match `fichten`.

**Comment by markus2330** [comment]
I don't think this specific example is relevant, important is that

1. `fi` matches `fichten` (prefix search) and
2. `Kirsche` matches `Frühkirsche` (search of subwords, ideally together with prefix search).

A similar example for 1. is even given in the mentioned link:

`SELECT to_tsvector( 'postgraduate' ), to_tsquery( 'postgres:*' );`

Is there no way to split up words? If this works, I think our search would be good enough.

**Comment by Benjaminimal** [comment]
None that I know of.

Did some more research and I think I have a pretty good picture of how to do it now.
We filter on the relevant columns with a simple `col ILIKE '%term%'` and rank the results via string similarity.
We can use one of these two.

1. [Levenshtein distance](https://www.postgresql.org/docs/14/fuzzystrmatch.html#id-1.11.7.24.7)
2. [Trigram similarity](https://www.postgresql.org/docs/current/pgtrgm.html#id-1.11.7.44.6)

A language preference-based factor will then be applied to this rank.

**Comment by markus2330** [comment]
What about splitting the important words already when inserting (like Frühkirsche)? I ask because eventually, we also want to include other text fields in the query, especially edible_uses. E.g. searching for Popcornmais should find "Mais suitable for making Popcorn". For me this sounds very much like full-text search, so I am still puzzled that PostgreSQL full text search cannot help us. As already said, I don't think we need any form of substring messages.

But your two suggestions also sound very good, so I am not fixed on full-text search.

Can you please write up a decision about your investigations so far. Which options do we have with which pros/cons?

**Comment by Benjaminimal** [comment]
> eventually, we also want to include other text fields in the query,

It would be good to know the exact requirements for this search operation.
It seems to me like they keep extending.

> What about splitting the important words already when inserting (like Frühkirsche)?

Of course that would be possible but is it worth investing that much time into fine-tuning this?
I think at this stage it would make more sense to get a simple working solution that can be expanded later if needed.

> Can you please write up a decision about your investigations so far. Which options do we have with which pros/cons?

Again I'd rather just implement the simple working version for now.
This should not be something that is hard to change or revert if needed so I don't see why it needs a decision.

**Comment by markus2330** [comment]
> It seems to me like they keep extending.

Yes, in this case there was one extension. We first thought it is not important to write everything immediately, as we will simply use a full text search anyway. We now wrote it in 9c32241826fee48d5b1ce3c5de0278dfe195c3f3, we also made the use case easier by removing two ranking criteria.

> I think at this stage it would make more sense to get a simple working solution that can be expanded later if needed.

If it is quickly done, of course. It would be great to check with actual queries how good the search works.

> This should not be something that is hard to change or revert if needed so I don't see why it needs a decision.

Decisions are about avoiding many pitfalls like:

1. avoid costly implementations which are not wanted
2. clarifying constraints & assumptions, which are often not explicit in the use cases
3. avoiding reiterating too often

If you have something simple in mind which is quickly done and later easily extensible/changeable you don't need to write a decision.

**Comment by markus2330** [comment]
@Benjaminimal 
A decision also has documentation purposes. Then people don't need to reread everything written here and get a grasp what our current state of affairs is. Maybe you find the time to shortly summarize what you would do when you continue working on the text search.

You can also directly write it as documentation how the search will work. In a similar manner, it would be great if you write a bit about the architecture how the frontend+backend should work together for the plants use case. You will probably be the one with the best overview because you design the API, the central piece.

**Comment by kitzbergerg** [comment]
I just did a bit of a read over this whole discussion and given that I have not done anything in this project related to something like this it will take a long time for me to get this done.

@markus2330 I don't think I will be able to finish this and #158 as both probably require probably another 2 weeks to get done in a nice way.
The auth change was way bigger than anticipated as well and basically took two entire weeks so I think you have to decide which one I should work on and assign the other to someone else.

Personally I'd prefer to do the mdbook as I probably will be faster doing that (as like I mentioned haven't done a task similar to fulltextsearch yet).

**Comment by markus2330** [comment]
> I just did a bit of a read over this whole discussion

The discussion is not relevant anymore, it had clear outcomes: doc/usecases/polyculture/search_plants.md describes what should be implemented and doc/decisions/search_plants.md describe how it can be done. The mentioned alternativey is mostly a question of implementation effort and performance, so a benchmark about this would be relevant and fits well with your thesis.

mdbook can be done as low-prior task next to the high-prior tasks like plant search.
