### ISSUE TITLE
website imprint

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#263]
Should have following content:

- [ ] Name: Markus Raab
- [ ] Address: Feldgasse 19, 7321 Unterfrauenhaid
- [ ] ZVR: not yet registered
- [ ] Purpose of Verein (Vereinszweck): PermaplanT
- [ ] This website is purely non-commercial, this website does not sell anything. It only offers you various forms of memberships.
- [ ] Contact email: contact@permaplant.net
- [ ] Contact form (which currently creates an email)

**Comment by ThorbenStaufer** [comment]
@markus2330 Do we already know what kind of association this will be at the end? There are several different information obligations defined by the government based on factors like registration in the company register, membership with the WKO or commercial obligation.

**Comment by ThorbenStaufer** [comment]
Yes, but there are still minor differences that have different information obligations. A "Verein" can be registered in the company register or not, it can have memberships with different "Kammern", it can be "Gewerbepflichtig" or not. It all influences what needs to be put on the imprint page. 

Minimum requirements are:
 - Name
 - Address
 - Company Purpose

But there can be a variety of additional requirements depending on the exact case.
The WKO has an official document detailing all of that. I will link it [here](https://www.wko.at/service/wirtschaftsrecht-gewerberecht/Das-korrekte-Website-Impressum-Verein.pdf).

**Comment by markus2330** [comment]
Seems you are expert on this topic :+1:  Do you know which Kammer would be suitable for us? Which additional information would we need in the impressum?

As the "Verein" is not registered yet, we obviously don't have the necessary numbers anyway.

> I will link it [here](https://www.wko.at/service/wirtschaftsrecht-gewerberecht/Das-korrekte-Website-Impressum-Verein.pdf).

It does not contain much about Vereine?

**Comment by ThorbenStaufer** [comment]
> Seems you are expert on this topic

Unfortunately I am no expert in this topic. I just researched what we would need for the imprint page and found out that I require a little more information.

> It does not contain much about Vereine?

The whole document is only about the imprint page for Vereine.

**Comment by markus2330** [comment]
> I just researched what we would need for the imprint page and found out that I require a little more information.

I added in the top-post what we add for the first version.

>  The whole document is only about the imprint page for Vereine.

Ahh, thanks for pointing out! I confused this with a very similar document from WKO which had only one sentence about Vereine.
