### ISSUE TITLE
i18n leftovers

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#266]
- [ ] main page not translated
- [ ] translate of composed text (+ include selection of pricing)
- [ ] "Samen speichern" -> "Same speichern" (Einzahl)
- [ ] visual overlap bug

![image](https://user-images.githubusercontent.com/7949075/231401970-4d2d1c71-2fd1-432e-8fee-b6552c61444b.png)

**Comment by Bushuo** [comment]
> main page not translated?

I left it out on purpose, as there is still much placeholder content. Yesterdays merge conflict with the seeds feature was a horror.
I think the person that inserts the text on the main page should also do the translation there.
Same with detail of seeds page, as there are changes coming from @buenaflor I guess (edit/delete).

> "Samen speichern" -> "Same speichern" (Einzahl)

Both is correct as far as I know, but I am happy to change it.

> visual overlap bug

Yes, the height of the navbar changed. I will fix it again.

> translate of composed text (+ include selection of pricing)

Can you please elaborate? i18next has an inbuilt feature for interpolated translations.

**Comment by markus2330** [comment]
>>     translate of composed text (+ include selection of pricing)
>  Can you please elaborate?

The idea was that the user clicks on one field of Pricing, then optionally writes a Message, and then clicks "Compose email". The question was if this text in the email should be translated, too. As you didn't do the translation on the landing page yet, the question is more-or-less answered.

> i18next has an inbuilt feature for interpolated translations.

Yes, that could be useful to get the text of the "Pricing" into the text.
