### ISSUE TITLE
document way to get current language

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#270]
> Additionally, I would try to use the Accept-Language header to infer the language to be used.
How do we determine the language in the frontend?
Is it a manual setting for the user or do we get it from the browser settings?

It is both. If the user loads the page for the first time the language is guessed by the browser settings, with the fallback being english. Then this setting is persisted into local storage.
I think Accept-Language alone will not work, because changing the language on the page does not change this header. I can look into it in the evening though.

_Originally posted by @Bushuo in https://github.com/ElektraInitiative/PermaplanT/issues/268#issuecomment-1506640156_

**Comment by markus2330** [comment]
@Bushuo wrote:
> ```ts
> axios.interceptors.request.use((config) => {
>   config.headers['Accept-Language'] = i18next.resolvedLanguage;
>   return config;
> });
> ```
> 
> This would add the correct `Accept-Language` header to each fetch request.

Sounds okay to me, once we add this, we should document the headers we set for the backend.

I assign this now to @Benjaminimal as part of the search.

**Comment by Benjaminimal** [comment]
Looks good!
