### ISSUE TITLE
Bug: header text clipping into navbar

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#278]
I noticed on the seed overview and seed creation pages, that the header text is partially covered by the navigation bar.

![image](https://user-images.githubusercontent.com/101188734/231977920-f97dd4f3-2ffb-4e60-a07a-98bc8bbe7469.png)

**Comment by Bushuo** [comment]
@markus2330 @ThorbenStaufer This will be fixed by #271

**Comment by badnames** [comment]
Yes should already be fixed, just need someone to review #271.
