### ISSUE TITLE
Bug: language selection on hover colors

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#284]
When hovering over the not-active option, the active one becomes green until you hover over it again and the not-active one becomes the color of the active one.

Normal:
![image](https://user-images.githubusercontent.com/101188734/232200247-4f57e2ac-3b52-4461-be53-21ce39598e9d.png)

After hovering over not-active:
![image](https://user-images.githubusercontent.com/101188734/232200276-27fc2c1c-b7c1-4fee-9916-5651bf74f604.png)

**Comment by Bushuo** [comment]
@ThorbenStaufer 
I think this is not a bug.
Active color: green
Focus color: light gray
Hover color: even lighter gray

On clicking the active option is focussed. You can change the focus via the arrow keys.

But I agree that the colors are weird. It would make sense to define a color for focus and active, hover and active state.
