### ISSUE TITLE
repo structure

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#3]
- [x] mono repo
- [ ] docu architecture
- [x] remove db folder (-> migrations)
- [x] add doc/contrib
- [x] libraries decisions

Other suggestions?

**Comment by markus2330** [comment]
I think we can remove the folder [db](https://github.com/ElektraInitiative/PermaplanT/tree/master/db) (migrations contain the sql statements instead).

I suggest we add a `doc/contrib` which is the documentation for someone who also wants to contribute to PermaplanT. Here infos about how to write migrations, how typeshare works etc. should be.

Ideally, `doc/contrib` should contain an example how to add a feature that goes through whole frontend and backend.

**Comment by buenaflor** [comment]
Contribution docs sounds good, will do.

For the installation and run process, would it make sense to create a `scripts/install.sh` or similar to have a convenient way to install both backend and frontend in one go? Might also be beneficial for the ci/cd pipeline

**Comment by markus2330** [comment]
Yes, it absolutely makes sense to have such scripts to not bloat the Jenkinsfile and to also test it outside of Jenkins. I thought it would simply be in `ci/install.sh` as the scripts is mostly relevant for ci. If there are scripts to be useful outside ci (and probably there are), we can create `scripts` and put `ci` below scripts. (I like it if top-level is clean and only has  a few folders.)

**Comment by markus2330** [comment]
As discussed we will start writing the docu in mdBook. Everything else gets fixed in #62.
