### ISSUE TITLE
Geometric Measurement Units

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#303]
Since I'm currently working on the base layer, I was wondering how we are going to handle different kinds of geometric measurement units throughout the app.
I have not yet found any decisions on this topic yet, so please tell me if I'm missing something. 

Here are my suggestions:
### Distance 
Konva seems to use CSS pixels in its API.
We therefore need some way of converting these to real world units (such as meters).
IMO using a fixed conversion would be the easiest way to do this (e.g. 10px in Konva = 1m in the real world), since the base layer would be the only component that has to deal with variable scales AFAIK.

### Angles
I have started to use degrees in the base layer for now.

**Comment by markus2330** [comment]
About Konva there is a bit written in #106.

> IMO using a fixed conversion would be the easiest way to do this

If there is a ready-made function from PostGIS it should be just as easy.

> (e.g. 10px in Konva = 1m in the real world)

This alone won't do as there is a zoom functionality?

> I have started to use degrees in the base layer for now.

Can you please create a proper documentation for the geometry? (In a new PR solving this issue.)

**Comment by markus2330** [comment]
@badnames Please use 1px = 1cm, i.e. 100 px = 1m. It is needed for the common spacing of 15cm (without having floating points).

**Comment by badnames** [comment]
Sure no problem.
