### ISSUE TITLE
Map creation

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#304]
Let users create and delete maps.
Implements [map creation and deletion use case.](https://github.com/ElektraInitiative/PermaplanT/blob/df25c5691321c7f324302fd35994e5dc8f4d71e8/doc/usecases/map_create_delete.md)

- [x] Overview page for the maps of an user.
- [x] Backend API for adding a new map to the database.
- [x] Frontend form for creating a new map.

**Comment by markus2330** [comment]
Thank you for creating this issue! Looks good to me, the actual deletion of a map can be done later, there are already issues about that.
