### ISSUE TITLE
provide link preview

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#305]
It seems like we don't provide a link preview (image), so various platforms either don't show a link preview or show the react logo.

**Comment by markus2330** [comment]
@tschawax do you have experience with this? Is this an easy task?

**Comment by markus2330** [comment]
Would be great to see this one day! Is low-prior, though.

For me the main use case is actually to see the PermaplanT logo in the preview when sending the link via Signal or Telegram.

**Comment by markus2330** [comment]
@danielsteinkogler do you have experience with this?

**Comment by markus2330** [comment]
@absurd-turtle looks like this goes back to you :wink: 

Do you think this is an easy task?

**Comment by absurd-turtle** [comment]
Not sure how it works. Would have to look into it.
