### ISSUE TITLE
Map undo redo

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#306]
A user should be able to undo or redo her actions on the map.
Implements [Map Undo Redo](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/map_undo_redo.md)

- [X] Undo an action
- [X] Redo an action
  Currently supported actions:
  - [x] create
  - [x] update single-element (drag, resize, rotate)
  - [x] update multi-element
- [x] display which action was undone
- [ ] display possible error (I don't know what could go wrong at this point)
- [ ] documentation for frontend devs how to use undo/redo, answering questions like how multiple actions can be merged to a single undo/redo step.

**Comment by markus2330** [comment]
Thank you for creating this issue!

- Please create a PR so the diff can be shown more easily in GitHub.
- Please also write in the documentation how multiple actions can be merged to a single undo/redo step etc. (or what else devs need to know about undo/redo)

**Comment by Bushuo** [comment]
@markus2330 What do you mean by merging multiple actions into a single undo/redo step?
Can you give me an example please?

**Comment by markus2330** [comment]
E.g.: if a group is moved around that the whole group would move back on undo.

Probably nothing needs to be done specifically for undo, but one must be careful in updating the state atomically.

**Comment by Bushuo** [comment]
> E.g.: if a group is moved around that the whole group would move back on undo.
> 
> Probably nothing needs to be done specifically for undo, but one must be careful in updating the state atomically.

@markus2330 Perfect, I already implemented this for the default elements on the map that Giancarlo provided 😄
