### ISSUE TITLE
enum all-lowercase

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#311]
As we translate enums anyway, the key can be all-lowercase, e.g.
Organic -> organic
WATER -> water

@aidnurs will hopefully do most of the work, but the seeds must be updated, too:

[backend/schema_dump/2023-04-23-193148_create_seeds/up.sql](https://github.com/ElektraInitiative/PermaplanT/pull/229/files#diff-04b0dcf8fc0112ec4f72f6511726b8c286da7da363a05347b4e92480012c3f6f)

Afterwards we can hopefully migrate to the squashed schema.

**Comment by markus2330** [comment]
@NurramoX is this something for you?

**Comment by temmey** [comment]
can be closed with #644
