### ISSUE TITLE
npm install for frontend not working on my local machine

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#317]
Since today, running `npm install` in my local frontend fails.
I have not updated NodeJS or npm before these issue appeared and up until now I had no problems whatsoever.
My local repository is up-to-date with origin master from today, 12:22 pm.

I already updated NodeJS and npm to their latest versions and also reverted npm to a version that definitely works for others in a following test.
I also removed node_modules and dist, but it did not solve the issue.
I adapted my environment variables to have npm in a higher priority than NodeJS in case that the internal npm version of NodeJS causes issues, but to no avail.

**Environment:**
- OS: Windows 10
- NodeJS: 18.16.0
- npm: 9.6.3

**Error message:**
![image](https://user-images.githubusercontent.com/101188734/234303767-dab5d5ca-4947-4055-8df2-745f21d061b0.png)

**Comment by markus2330** [comment]
I assume you already searched for the error?

1. Most likely it is some installation problem of mingw/cygwin/whatever Shell emulation system is used (as `rm` is not found). Try to purge all versions you might have and install new.
2. The warnings indicate some weird filesystem problem. Can you try to build on another filesystem? (USB Stick if there is nothing else available.)

**Comment by ThorbenStaufer** [comment]
It actually was the Shell I was using. Until now, I always ran the commands with Powershell and I never had any kinds of problems with it. With Git Bash it works perfectly fine now. Thank you very much!
