### ISSUE TITLE
authentication client for frontend

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#320]

**Comment by markus2330** [comment]
Thank you for creating this issue!

Is https://www.nango.dev/ maybe relevant/useful? (I found it via https://www.nango.dev/blog/why-is-oauth-still-hard)

**Comment by markus2330** [comment]
But maybe something like https://www.npmjs.com/package/keycloak-js is more straight-forward for us.

@kitzbergerg What do you think? Do you have experience with one of these?

**Comment by kitzbergerg** [comment]
Yes, keycloak-js works really well and should be easy enough to set up. However you are then locked into using keycoak. If that is no problem then I would go with that. Otherwise I would suggest using a generic oauth2 library. That way we are easily able to switch from keycoak.

**Comment by absurd-turtle** [comment]
> Yes, keycloak-js works really well and should be easy enough to set up. However you are then locked into using keycoak. If that is no problem then I would go with that. Otherwise I would suggest using a generic oauth2 library. That way we are easily able to switch from keycoak.

I have looked into a more generic oidc library called [oidc-client-ts](https://github.com/authts/oidc-client-ts) which also has a wrapper for react called [react-oidc-context](https://github.com/authts/react-oidc-context)

**Comment by markus2330** [comment]
As migration from Keycloak is rather unlikely/impossible (changing the clients would probably be rather minor compared to migrating all the users etc.) we could use something tied to keycloak. But [react-oidc-context](https://github.com/authts/react-oidc-context) seems to be quite comfortable, as it seems to already do a transparent renewal. If this works as promised, we can go for it. But keycloak-js is okay, too. Whatever lib is more robust and easier to use.

If the choice is not so clear and/or change is not easily possible, please write up a decision.
