### ISSUE TITLE
link checker for mdbook

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#321]
before we get too many broken links, we should use a link checker for mdbook

https://github.com/Michael-F-Bryan/mdbook-linkcheck

**Comment by kitzbergerg** [comment]
One thing to keep in mind here is that once the link checker is in place it is no longer possible to reference files anywhere outside of the `doc/` folder (e.g. [this](https://github.com/ElektraInitiative/PermaplanT/blob/dc46fc6b93d1ddad3e05c79e298af596bec7da1d/doc/architecture/backend.md?plain=1#L28) will not be possible).
All such URLs that reference any files apart from the markdown files in the `doc/` folder need to be prefixed with the full URL.

I'll unassign myself as discussed with @markus2330.
