### ISSUE TITLE
"Main Features" @github.com

### ISSUE THREAD

**Issue by HappyPony** [ElektraInitiative/PermaplanT#322]
Hi,

in the section "Main Features" here https://github.com/ElektraInitiative/PermaplanT is in sentence 
> positions and distances relate to the real word, e.g. you can use GPS coordinates

probably means "real world"?

**Comment by markus2330** [comment]
Yes, good catch, thank you for telling us! :heart:

**Comment by markus2330** [comment]
Should be fixed in #325, together with many other documentation fixes.
