### ISSUE TITLE
design guideline about keybindings and "submit data" button

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#324]
When reviewing #244 some more general points came up:

- Do we need "submit data" buttons? Isn't there an easy way to directly use input or does this make problems for undo/backend communication? @Bushuo what do you think?
- Documentation of key bindings: this is actually already something relevant to end users. Maybe we can put it to mouse-over text? Anyway we should have a central document for it, so that keybindings get consistent.

**Comment by markus2330** [comment]
Let us use vim bindings.

@absurd-turtle what do you think about describing them in a Markdown document which we embed in PermaplanT?

**Comment by absurd-turtle** [comment]
> Let us use vim bindings.
> 
> @absurd-turtle what do you think about describing them in a Markdown document which we embed in PermaplanT?

My suggestion is to create a json or yaml configuration file for global keybindings.
And one keybinding configuration file for each component.
This makes them easily changeable.
We can then generate some markdown document from those configuration files if needed.
We could use a prefix like "KB_" to easily find all the configuration files and then generate one markdown.

**Comment by markus2330** [comment]
We already use several JSON files (e.g. translation) so better stick with this format.

> This makes them easily changeable.

More important is that they will be consistent: the same bindings for the same actions.

> We can then generate some markdown document from those configuration files if needed.

No, Markdown files are not needed. But showing the bindings in the UI is needed.

**Comment by markus2330** [comment]
- We don't use submit data.
- key bindings has follow up #421
