### ISSUE TITLE
plant search in frontend

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#327]
Follow up of #244

**Comment by badnames** [comment]
@markus2330 Th objective of this issue is to wire up the plant search for the plants layer with the backend, correct?

**Comment by markus2330** [comment]
Exactly, both in seed and in the plant layer the search should be fully functional. Actually they should be identical.

**Comment by badnames** [comment]
@markus2330 The plant search was apparently already implemented in the frontend.
The language issue was declared as a floss issue.

What is still missing from this issue before it can be closed?

**Comment by markus2330** [comment]
Please test it (if not already done) and move the usecase to done.
