### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#329]
We have to implement authentication for PermaplanT.

This involves multiple steps:

- [x] frontend (#320)
- [x] #336 
  - [x] fix backend CORS configuration (is only necessary for local dev)
- [x] Keycloak (no code changes just deployed)
- [ ] add/refactor documentation #412 
- [ ] describe how to run benchmarks (@kitzbergerg) #392 

We have to set up all of them in one step otherwise they won't work together (e.g. backend requires auth but frontend hasn't yet implemented.

@markus2330 I would start with a setup in the backend that works locally. I'll leave it disabled and then once frontend oauth2 is ready we just have to enable it in that PR.

**Comment by markus2330** [comment]
> I would start with a setup in the backend that works locally. I'll leave it disabled and then once frontend oauth2 is ready we just have to enable it in that PR.

Yes, that is fine. I assume frontend and backend auth are more or less independent anyway?

As said, important is that it does not get more difficult to write (integration) tests. People should **not** need to learn how the tokens work just to write an (integration) test. There are too many potential problems, like expiration. So it should be possible to disable the whole auth. This could be done, e.g., by setting `REMOTE_AUTH_URL` to a special string (e.g. what the uid should be used, see comment in #330). If you find a better way, please first tell it here in the issue before you start rewriting all tests.

**Comment by kitzbergerg** [comment]
> > I would start with a setup in the backend that works locally. I'll leave it disabled and then once frontend oauth2 is ready we just have to enable it in that PR.
> 
> Yes, that is fine. I assume frontend and backend auth are more or less independent anyway?
> 
> As said, important is that it does not get more difficult to write (integration) tests. People should **not** need to learn how the tokens work just to write an (integration) test. There are too many potential problems, like expiration. So it should be possible to disable the whole auth. This could be done, e.g., by setting `REMOTE_AUTH_URL` to a special string (e.g. what the uid should be used, see comment in #330). If you find a better way, please first tell it here in the issue before you start rewriting all tests.

#330 is already a finished PR. So from my side this PR could be merged and auth would be working. Setting a special URL doesn't work, as auth the way I implemented it (and I believe its the way you are supposed to do it with Actix) is deeply linked with actix. The only thing we can do is keep the feature flag.
Tests also have auth integrated. However from the point of view of somebody writing simple tests it should be easy enough. From the init function they get a token back that is valid for another 5min (see code in PR).

**Comment by markus2330** [comment]
I linked #392 above.
