### ISSUE TITLE
basic component documentation

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#333]
Add documentation for all components in [/frontend/src/components](https://github.com/ElektraInitiative/PermaplanT/tree/master/frontend/src/components)

- [x] IconButton
- [x] SimpleCard
- [x] InfoMessage
- [x] CreateableSelectMenu (@Bushuo)
- [x] PlantSuggestionList (@Bushuo)
- [x] PlantListItem (@Bushuo)
- [x] PaginatedSelectMenu
- [x] SearchInput
- [x] SelectMenu
- [x] SimpleFormInput
- [x] PageTitle
- [x] Footer
- [x] Navbar
- [x] NavContainer
- [x] PageLayout
- [x] WidePageLayout
- [x] ImageModal
- [x] ModalContainer
- [x] SimpleModal
- [x] SimpleButton
- [x] TransparentBackground

And finally:

- [x] The folder doc/ui_components should be removed

**Comment by markus2330** [comment]
Thanks for creating this issue!

@Bushuo @buenaflor @badnames Can you please say which of these components you feel responsible for (you will be maintainer for)? Please make sections for who will maintain which component in the top post.

And then please document these components by-and-by with the next PRs, ticking them from above list. Who is maintainer should be also written in the documentation.

@Bushuo do you have an idea how we can document bigger components which are most likely not reused but which are relevant for basically everyone doing something in the frontend  (e.g. sidebars)?

**Comment by absurd-turtle** [comment]
@markus2330 What's the purpose for a dedicated maintainer of a single component?

**Comment by markus2330** [comment]
So that I know whom to ask.

**Comment by Bushuo** [comment]
> @Bushuo do you have an idea how we can document bigger components which are most likely not reused but which are relevant for basically everyone doing something in the frontend (e.g. sidebars)?

@markus2330 Sorry for not answering. I missed this somehow. Yes, also in storybook. I think @absurd-turtle already did it like this.

**Comment by markus2330** [comment]
I added above:

- [ ] SimpleButton
- [ ] TransparentBackground

And finally:

- [ ] The folder doc/ui_components should be removed

**Comment by markus2330** [comment]
@badnames which of the left-overs can you do? And you please (re)move `doc/ui_components`?

**Comment by markus2330** [comment]
I added

- [ ] PlantSuggestionList
- [ ] PlantListItem

as suggested in #436
