### ISSUE TITLE
describe ways how to gain permacoins

### ISSUE THREAD

**Issue by HappyPony** [ElektraInitiative/PermaplanT#338]
Have read the article https://linuxnews.de/interview-markus-raab-von-elektra/. Is there any way to find out how this works with valuing and recording participation with permacoins?

Could it possibly be a problem that the term permacoin is already in use - see https://golden.com/wiki/Permacoin [1] and https://www.microsoft.com/en-us/research/publication/permacoin-repurposing-bitcoin-work-for-data-preservation/ [2]? Or are _PermaplanT_ Permacoins identical to [2]?

**Comment by markus2330** [comment]
Thank you for sharing! I did not know that the term "permacoins" is already used. Our permacoins have nothing to do with bitcoins or related technologies but it seems it is easily mistaken as such, so good to have an issue about this.

Our permacoins are simply a fancy word for the "points" collaborators collect for community tasks.

The details for gaining permacoins are not yet clarified, and the rules probably will continue to change in the first years (but of course not during the year) until we established a more or less fair system, independent of which specific way users choose to gain permacoins. The current use case about this can be reviewed in #288.

You can also contribute ideas for how permacoins can be collected. We currently do not have a system for how developers get permacoins. What do you think about 10 permacoins  for every merged PR? I also think that creating relevant issues (like this one) should lead to gained permacoins.

**Comment by HappyPony** [comment]
IMHO it would be beneficial if "Permacoin" valued contribution is described in a similar stringent transparent taxonomy as [glossary.md](/ElektraInitiative/PermaplanT/blob/master/doc/architecture/glossary.md) is for biological terms. This could facilitate: a) the decisions to participate for potential contributors a) decisions about the recognition of "Permacoin" contributions for responsible association members c) possibly automating the calculation for "Permacoin" contributions.

Superficially offers could consider using a blockchain based infrastructure. Whereby it is not necessary that such an infrastructure is developed in the PermaplanT project. The project https://fair-coin.org/en/contact, for example, was started with the goal of establishing FairCoin as an barter system for micro businesses with a circular economy.

**Comment by markus2330** [comment]
We decided to first improve PermaplanT to be good enough to be used by others before we work on this feature. We close it for now, but we will reopen and work on this later.

For now, please contact us per email if you want to work on PermaplanT and we will find an individual solution.
