### ISSUE TITLE
Save a snapshot of a map as a version

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#341]
I am adding this issue as a clarification and follow-up to #323.
As stated in the [map versioning](https://github.com/ElektraInitiative/PermaplanT/blob/49062110405c49c76da3aaa4b36bf870e66d104f/doc/usecases/map_versioning.md) use case, there should be a functionality to save the current state of the map and create a new version from this snapshot. The barebones framework for creating a map version already exists, but it is still missing the storing and linking of the placed canvas elements with the version entry.
This will be implemented as soon as the most essential layers are finished.

**Comment by markus2330** [comment]
> to save the current state of the map

:+1:

> create a new version from this snapshot.

See glossary: the version = named snapshot. Users can load any version (= named snapshot). They cannot create another version from a version other than manipulating the map and saving the current state again.

**Comment by ThorbenStaufer** [comment]
Map version are currently no longer in scope for this project.
