### ISSUE TITLE
Map Timeline Single Date Selection

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#342]
This issue implements the usecase [Map Timeline Single Date Selection](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/map_timeline_single_date_selection.md)

**Comment by Bushuo** [comment]
There is a library that looks promising but has other peer dependencies that I do not want to bring into the project.
https://github.com/namespace-ee/react-calendar-timeline

**Comment by markus2330** [comment]
I already looked at it and didn't even find an option so that looks like how we want it. Did I miss something?

**Comment by Bushuo** [comment]
I think like this, it looks quite similar.
https://codesandbox.io/s/timeline-demo-sticky-header-forked-3t7hm0?file=/CustomTimeline.jsx
![image](https://github.com/ElektraInitiative/PermaplanT/assets/9990578/50241b2b-fed6-4513-9d74-50b643358bf7)

**Comment by markus2330** [comment]
It is also quite different, we don't need that the day is split in smaller units and we also don't need text per day but a graph of how many occurrences were at which day. So something like what video-players have, e.g. youtube where you see the number of watches (but we need number of changes in the map on that day).

Maybe we can reuse something from video players, and change the scale from seconds to days?

**Comment by markus2330** [comment]
There are some small updates about this UC (basically what we already said) in #454

**Comment by markus2330** [comment]
A probably more simple (than what we originally imagined but not more simple than a date picker) implementation of timeline could be done via server-side SVG.  See https://alexplescan.com/posts/2023/07/08/easy-svg-sparklines/ for inspiration.

We would basically write the dates with an SVG path below/around (indicating how many actions on the elements happened each day). The question is how clicking on the dates then actually would lead to the right action. Is this possible with react-svg?

If you think this makes somewhat sense, please write this as implementation hint linked the left-over of the use case.

**Comment by Bushuo** [comment]
I would then prefer to use a graphing library that comes with click handling on datapoints.
One that I already used is [react-charts](https://react-charts.tanstack.com/).

**Comment by markus2330** [comment]
Yeah, if you already used it the choice is obvious. Then let us forget the idea with SVG. Anyway, we won't do it for this user study.
