### ISSUE TITLE
Additional properties for map creation

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#345]
As stated in todays meeting, some more customization options are needed for map creation.
Additional properties:

- [ ] privacy settings
- [x] description
- [x] location

**Comment by ThorbenStaufer** [comment]
From what I can see, if we want the user to be able to pick their location through a user friendly interface instead of manually typing the lat/long coordinates, we would need to use the official Google API. This requires us to register the app with Google, get an API key and pay a small fee per API call. There is also another API provider, Geoapify, which offers a very limited amount of API calls for free but then costs us for predetermined numbers of API calls per day. Unfortunately, I have not found any other solution as of now.

**Comment by markus2330** [comment]
Do you know which provider https://www.openstreetmap.org/ uses?

As written in #402 we might directly let the user select the location via an embedded map.
