### ISSUE TITLE
CI pipeline seems to be broken

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#347]
## Steps to Reproduce the Problem

Push a new commit to the pipeline.

## Expected Result

The pipeline builds the commit and reports any errors.

## Actual Result

The system fails to connect to the docker deamon, resulting in build failures after each push.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/ef25618c-fb27-48ed-835e-38b5db8b23f0)

## System Information

- PermaplanT: any branch

**Comment by lukashartl** [comment]
Can you give me a Jenkins Log URL from within the last 3 hours?

I noticed that the docker daemon on H1 was stopped. I added a step called `start and enable docker` for all jenkins agents.

**Comment by markus2330** [comment]
Seems to work again.

@lukashartl I think nobody will complain if you use any PR and restart the build job there. You can definitely use my PRs.
