### ISSUE TITLE
use NC image loading

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#348]
Once the Nextcloud integration is done, we need to rewrite the logic for loading base-layer images.
This includes handling and displaying errors such as:
- image not found
- unsupported file format 

We should also decide if base layer images have to exist in Nextcloud before.

**Comment by markus2330** [comment]
Yes, good idea to have a common way to work with images/files (and to have all of them in Nextcloud and not in our database).

@absurd-turtle will you provide common util functions for this?

**Comment by absurd-turtle** [comment]
Yes. I started working on this when testing the authentication with Nextcloud in #320.

We can start writing more sophisticated util functions for Nextcloud as soon as authentication is merged.
