### ISSUE TITLE
Set borders of map (frontend)

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#349]
Fence of an area within a base layer to tell PermaplanT where the borders of the background image are.

**Comment by markus2330** [comment]
Thanks for creating the issue :heart:

**Comment by badnames** [comment]
# Summary of changes
Because this is a bigger PR/issue than usual, I decided to summarize all new features in this comment.

![grafik](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/467f535b-0bc8-4fdf-b77a-0bf681d49083)

The current map polygon is shown every time the user is one the base layer screen.
To manipulate it, there are three new buttons available in the right toolbar.

![grafik](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/4998d54f-a037-414c-90e4-c32d2687aef1)
After pressing the first button, the user can move any point of the map geometry by dragging it.
This edit edit mode (as well as all other edit modes described below) can be cancelled by either pressing the 'x'-button in the status panel, switching to another layer or activating the auto scale workflow.

![grafik](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/fe88f58c-3832-46ef-b655-94536f0629d3)
After pressing the second button, new points can be added to the polygon by clicking anywhere on the map.
New points will always be inserted between the nearest pair of points (measured using the sum of the distance between the new point to the first point and the distance between the new point and the second point).

![grafik](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/3ce3d5bb-b1ac-470e-9bc9-c393ae5f34b1)
Using third and final button, undesired points can be deleted via a simple mouse click.
