### ISSUE TITLE
Frontend restructuring

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#355]
As discussed in #352 and https://github.com/ElektraInitiative/PermaplanT/pull/352#discussion_r1192925554 the structure in our frontend code is not always clear.
This issue will clear up the following:
- [X] (WONTDO) Create a `lib` folder that holds the configurations for libraries (to follow bulletproof react - see [Frontend Architecture Pattern Decision](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/decisions/frontend_architecture_pattern.md))
- [x] Merge the `bindings` and `generated` folder. Such that there is only one `generated` folder that holds all generated code.
- [x] Rename `bindings` to `api_types` in the new folder structure
- [x] Remove `src/asset` and `src/icons`, instead have in `public` `icons` etc. subfolders
- [x] add all icons not drawn by us in .reuse/dep5

**Comment by Bushuo** [comment]
@markus2330 Yes we conform to the above conventions.
Except for the `export default` one, which is controversial.
Here are two sources that explain the shortcomings 
https://basarat.gitbook.io/typescript/main-1/defaultisbad
https://stackoverflow.com/questions/46913851/why-and-when-to-use-default-export-over-named-exports-in-es6-modules 

I think we currently use a mix of both.
Should I update the code to just named exports?

**Comment by markus2330** [comment]
Yes, I agree, we should prefer named exports. For now it is enough if we create a guideline for this and an issue about left-overs. We first need to concentrate on getting the main functionality done.

**Comment by markus2330** [comment]
I added:

- [ ] Remove `src/asset` and `src/icons`, instead have in `public` `icons` etc. subfolders.

above.

**Comment by markus2330** [comment]
There seems to be a problem with `Remove src/asset and src/icons`

In #881 there is now the warning:

```
Assets in public cannot be imported from JavaScript.
Instead of /public/icons/archive-off.svg, put the file in the src directory, and use /src/icons/archive-off.svg instead. (x3)
```

(although the icon is shown?)

@Bushuo What do you think about removing `src/assets` and have everything in `src/icons`? (And also all svgs in `public` would be moved there)?

**Comment by markus2330** [comment]
I updated `- [ ] add all icons not drawn by us in .reuse/dep5` above.

**Comment by badnames** [comment]
> Merge the bindings and generated folder. Such that there is only one generated folder that holds all generated code.

I could not find a folder called 'generated' in the frontend so is it save to assume that this point is no longer needed?

**Comment by badnames** [comment]
> add all icons not drawn by us in .reuse/dep5

This is the only licensing information that tabler icons provided on the website. 
I will copy what it says there into the mentioned file for now unless anyone else finds a better solution.

**Comment by Bushuo** [comment]
> I could not find a folder called 'generated' in the frontend so is it save to assume that this point is no longer needed?

Typedoc generates this folder under `src/generated`. I am not up to date but I found the typedoc config where it's written.

**Comment by markus2330** [comment]
For me #946 unfortunately now has plenty of warnings.

**Comment by badnames** [comment]
> > I could not find a folder called 'generated' in the frontend so is it save to assume that this point is no longer needed?
> 
> Typedoc generates this folder under `src/generated`. I am not up to date but I found the typedoc config where it's written.

Ok thanks for the answer

**Comment by badnames** [comment]
> > I could not find a folder called 'generated' in the frontend so is it save to assume that this point is no longer needed?
> 
> Typedoc generates this folder under `src/generated`. I am not up to date but I found the typedoc config where it's written.

Since SVG are technically source code, they need to be imported from the src folder.
Would it be a problem if we put all SVGs e.g. into src/svg?

**Comment by markus2330** [comment]
It is what the warning suggests to do and which I also thought about above. The question is if files in `src/svg` can also be used in the other ways they are currently used?
