### ISSUE TITLE
Map: user/owner validation

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#360]
As part of the auth change (#351) I had to add security annotations to the map endpoints. There were some other issues there regarding utoipa/Swagger that I fixed as well (e.g. we don't need the user_id in the path).

Apart from that we have to change the map owner_id to be `Uuid` instead of `i32` as Keycloak uses `Uuid`'s to identify users. I added a TODO referencing this issue in code and also a print statement showing how/that the id can be extracted from the request.

@ThorbenStaufer Once #351 is merged I would ask you to do the following:

- [x] Change owner_id to be `Uuid`
- [x] Completely remove `owner_id` from `NewMapDto`. Instead extract the `Uuid` from the request and pass it to the service and db impl. Instead of `NewMap::from(new_map)` do something like: `NewMap::from_dto_and_owner(new_map, owner_id)`
- [ ] Validate on every request that the owner_id matches the current user's id.

**Comment by ThorbenStaufer** [comment]
> Validate on every request that the owner_id matches the current user's id.

I don't think we should do that, since a map can be opened and in some cases edited by users that are not the owner.
