### ISSUE TITLE
bug: auth breaks landing page when backend is down

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#365]
The AuthProvider expects the correct configuration. We can delay the initialization of the AuthProvider and wait for the configuration from the backend and then intitialize it.
If the backend is down the AuthProvider never receives the config and we can return an error message.
This was our first approach. This leads to the problem that nothing except an error message is displayed because the AuthProvider can't be initialized.

We tried to fix this by passing a default config.
Then wait for the config from the backend (until it is online again) and then rerendering the AuthProvider component.
This can achieved by providing a key prop:

const config = data ?? defaultConfig;
return <AuthProvider key={config.authority} {...config}>{children}</AuthProvider>;

Now the problem is that once the configuration has changed and the AuthProvider is reloaded the login does not work anymore.

**Comment by markus2330** [comment]
Thanks for the write up! I marked it as wontfix for now.
