### ISSUE TITLE
plant search broken (in seeds dialog)

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#373]
- [x] No seeds are displayed if the search field is empty.
- [x] The search is way too insensitive, e.g. different kinds of wheat will only be display if "whea" is entered into the search field.

**Comment by badnames** [comment]
I have looked at this feature yesterday and today.
It seems to work in general with two major bugs:
- No seeds are displayed if the search field is empty.
- The search is way too insensitive, e.g. different kinds of wheat will only be display if "whea" is entered into the search field.

@markus2330 please let me know if there is anything I've missed.

**Comment by badnames** [comment]
Both issues should be fixed in #406

**Comment by markus2330** [comment]
I created a follow up #418
