### ISSUE TITLE
nextcloud integration: chat utils

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#380]
- [x] Implement util functions to interact with Nextcloud talk chat
- [x] Implement chat prototype component

## API documentation
https://nextcloud-talk.readthedocs.io/en/latest/

**Comment by markus2330** [comment]
Did you find some frontend code that you can use? It would be great if we don't need to implement it from scratch.

**Comment by absurd-turtle** [comment]
> Did you find some frontend code that you can use? It would be great if we don't need to implement it from scratch.

Nope, I haven't looked into it yet but I doubt that there will be any readily available solution. Maybe some components that can be used as a base.

**Comment by markus2330** [comment]
Implementing a fully-featured chat from scratch is quite huge, hopefully you find something.

Why won't the official Nextcloud spread work?

**Comment by absurd-turtle** [comment]
I mean it could work but the frontend code is written in Vue.
I don't know if such a big integration as well as mixing frontend libraries that serve the same purpose is wise in the long run.

**Comment by markus2330** [comment]
How can we bring this to an end? How can we merge your two long-open two PRs?
