### ISSUE TITLE
keycloak: sign in to swagger UI broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#383]
https://auth.permaplant.net/realms/PermaplanT/protocol/openid-connect/auth?response_type=code&client_id=markus&redirect_uri=https%3A%2F%2Fdev.permaplant.net%2Fdoc%2Fapi%2Fswagger%2Fui%2Foauth2-redirect.html

```
We are sorry...

Client not found.
```

**Comment by lukashartl** [comment]
client_id = markus?

**Comment by markus2330** [comment]
Which one should it be?

**Comment by markus2330** [comment]
https://github.com/ElektraInitiative/PermaplanT/pull/351#discussion_r1203730743

**Comment by markus2330** [comment]
https://auth.permaplant.net/realms/PermaplanT/protocol/openid-connect/auth?response_type=code&client_id=swagger-ui&redirect_uri=https%3A%2F%2Fdev.permaplant.net%2Fdoc%2Fapi%2Fswagger%2Fui%2Foauth2-redirect.html

**Comment by markus2330** [comment]
@lukashartl ping

**Comment by lukashartl** [comment]
There is one problem:

* We have 3 instances (dev, www, pr)
* Swagger-UI is deployed on all three of them, but I can only set one rootUrl/adminUrl.

/cc @kitzbergerg

**Comment by kitzbergerg** [comment]
> There is one problem:
> 
> * We have 3 instances (dev, www, pr)
> * Swagger-UI is deployed on all three of them, but I can only set one rootUrl/adminUrl.
> 
> /cc @kitzbergerg

First of I think we would only need the client for local-dev (so maybe `localhost-swagger-ui`, if you want something different than `swagger-ui` keep in mind to update the doc).
For dev, pr and www it should automatically work with the corresponding clients as the URL is the same. So for https://dev.permaplant.net/ swagger is at https://dev.permaplant.net/doc/api/swagger/ui/ and you can therefore use the client 
`PermaplanT-Dev` for that as it is the same root URL (maybe add documentation for that?).

@markus2330 @lukashartl  Apart from that there is a different unrelated issue I noticed while testing this:
There seems to be some caching issue (at least on my browser). When I open https://dev.permaplant.net/doc/api/swagger/ui/ a broken version of https://dev.permaplant.net/ appears. After I clear the browser cache it works. When I then open https://dev.permaplant.net/ and afterwards https://dev.permaplant.net/doc/api/swagger/ui/ it is broken again (and clearing the cache fixes it again). So it seems that somehow `https://dev.permaplant.net/` caches the page for all subpaths even though it shouldn't.

**Comment by markus2330** [comment]
Thx for the update! @kitzbergerg maybe you can already write the docu which user for which service etc, it then would probably be easier for @lukashartl to actually implement the changes.

**Comment by markus2330** [comment]
I can reproduce the caching problem. For both https://pr.permaplant.net/doc/api/swagger/ui/ and https://dev.permaplant.net/doc/api/swagger/ui/ the frontend loads if it was loaded before.

**Comment by kitzbergerg** [comment]
> localhost-swagger-ui

Done as part of #412.

**Comment by lukashartl** [comment]
@kitzbergerg 
I've created the following client:

```json
    {
       "clientId" : "local-swagger-ui",
       "name" : "Lokale Swagger UI Instanz",
       "description": "Für Entwickler um lokal Swagger UI zu testen",
       "publicClient": true,
       "rootUrl" : "http://localhost:8080/",
       "adminUrl" : "http://localhost:8080/",
       "redirectUris" : [ "/*" ],
       "webOrigins" : [ "+" ]
    }
```

Is this correct?

**Comment by lukashartl** [comment]
Caching Problem can be discussed here: #415

**Comment by markus2330** [comment]
> I've created the following client:

Is this consistent with the other client-ids? Shouldn't it have "localhost" in its name?

As said, it is probably best to first write down everything that should be done in document ci.md to see if it altogether is understandable/consistent/...

**Comment by kitzbergerg** [comment]
> @kitzbergerg I've created the following client:
> 
> ```json
>     {
>        "clientId" : "local-swagger-ui",
>        "name" : "Lokale Swagger UI Instanz",
>        "description": "Für Entwickler um lokal Swagger UI zu testen",
>        "publicClient": true,
>        "rootUrl" : "http://localhost:8080/",
>        "adminUrl" : "http://localhost:8080/",
>        "redirectUris" : [ "/*" ],
>        "webOrigins" : [ "+" ]
>     }
> ```
> 
> Is this correct?



@lukashartl I get an error while testing. I think you have to remove the slash at the end so change it to `"rootUrl" : "http://localhost:8080"`. You can remove the adminUrl completely. And please also set the checkmark on `Direct access grants` otherwise the password grant in swagger-ui doesn't work.

**Comment by lukashartl** [comment]
Login for pr,dev,prod works now (if you provide the correct client id).
Maybe this can be set inside the backend? @kitzbergerg

**Comment by markus2330** [comment]
Yes, that would be best. But if it is written in the docu which client_id to use, it is fine, too.

**Comment by kitzbergerg** [comment]
> Login for pr,dev,prod works now (if you provide the correct client id). Maybe this can be set inside the backend? @kitzbergerg

I don't think you can set this in the backend.

> Yes, that would be best. But if it is written in the docu which client_id to use, it is fine, too.

Already done. So I think this can be closed.

**Comment by markus2330** [comment]
Yes, great, doc/backend/03api_documentation.md contains all the information.
