### ISSUE TITLE
document relevant http headers we use

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#384]
- [ ] `Accept-Language`
- [ ] auth token

**Comment by kitzbergerg** [comment]
@markus2330 Is this still relevant? The only one we use is `Authorization` and that is done automatically by Keycloak.

**Comment by markus2330** [comment]
Yes, very relevant. We also use a header for the language, didn't you use it for implementing the search?

**Comment by kitzbergerg** [comment]
> Yes, very relevant. We also use a header for the language, didn't you use it for implementing the search?

No I never implemented that. I wrote a comment about that, after which you mentioned the search works great so I assumed it was fine without language and you merged it. So no the language isn't considered.

Maybe it is used somewhere else, but at least I haven't ever seen a header apart from auth being used in the backend.

**Comment by markus2330** [comment]
> No I never implemented that. I wrote a comment about that, after which you mentioned the search works great so I assumed it was fine without language and you merged it. So no the language isn't considered.

This was a misunderstanding. In general you are responsible to fully implement and test the use case (ideally with integration tests to verify it). So I didn't think I need to do a full functional test but I can do for you in future. Everything from the use case must be considered unless we remove/change the use case (or at least write something about a missing feature in the notes). Also in the left-over issue it was not mentioned, so I assumed it was done.

> Maybe it is used somewhere else, but at least I haven't ever seen a header apart from auth being used in the backend.

Then please document this header as first step.
