### ISSUE TITLE
Use Priority Sorter in Jenkins

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/PermaplanT#386]
To prioritise jobs in Jenkins I found this plugin (https://plugins.jenkins.io/PrioritySorter/). With this plugin we can create groups of jobs with different priorities, to handle large builds. 

Is it alright for you @markus2330 and @lukashartl if I install this plugin?

**Comment by markus2330** [comment]
Yes please, go ahead.

**Comment by fel115** [comment]
I installed the plugin and tested it. Now I have a problem with setting the priorities especially with the Multibranch-Plugin, there isn't an option for setting the job group. I think to solve this problem we have two options. 

1. Installing the Multi-Branch priority sorter (https://plugins.jenkins.io/multi-branch-priority-sorter/)
2. or create views for libelektra and PermaplanT, so we can attache them the priorities

I already tested it with regular expressions, but it didn't worked because every branch has an individual name.

**Comment by markus2330** [comment]
As said, please go ahead and install Multi-Branch priority sorter if you are convinced that it is somewhat maintained and will not create problems in future updates.

**Comment by markus2330** [comment]
@fel115 This has quite high priority, as now nearly everyday the build queue is very long. The maintainability of the plugin is actually not really important, as we can also remove the plugin again in the summer when build queue is empty anyway.

**Comment by fel115** [comment]
@markus2330 I already installed both plugins (https://plugins.jenkins.io/PrioritySorter/ & https://plugins.jenkins.io/multi-branch-priority-sorter/), but the behaviour of both plugins is not like expected. The Multi-Branch Priority Plugin is only to prioritize different branches in on repository, but in our case we want to  prioritize the repositories. So I tried to solve this problem by using view and created a view for PermaplanT and liberlektra. For some reason the jobs in the Permaplant-View and Multibranch Pipeline only get the default priority assigned and I haven't found a solution till now.

**Comment by markus2330** [comment]
If we give higher priority to branches called

```
feature/<issue_nr>
bug_fix/<issue_nr>
documentation/<name>
meeting/<date>
```

it would already help (this is convention for PermaplanT and you can simply use it for opensesame, too).

**Comment by markus2330** [comment]
Btw. you can simply use:

```
feature/*
bug_fix/*
documentation/*
meeting_notes/*
```

to match the branches.

If this doesn't work, we can also change the guideline how to name branches.

**Comment by fel115** [comment]
The priority will only be assigned, if I set the full branchname like meeting_notes/30.03.2023_polyculture. If I set meeting_notes/* then a job like meeting_notes/30.03.2023_polyculture, wouldn't get a higher priority. So I can set all manually, but if there are new branches in meeting_notes they would have the default priority.

**Comment by markus2330** [comment]
What a pity, seems to be quite unsuitable for our job. So both branch names and views don't work?

Did you also check the groups and folders?

**Comment by fel115** [comment]
Yes, branch names only work with the full name of the branch and views don't work as well. 
The problem with Groups is, that there is no Option to assign a group to Multibranch Pipelines. 
Folders cloud be the last option, which I'm trying.

**Comment by fel115** [comment]
Now I created a Folder "PermaplanT-Folder" and copied the Multibranch Pipeline and the PermaplanT-Release job into it. And it seems to work, I started a job and got the highest priority in the logs.

**Comment by markus2330** [comment]
Great!
