### ISSUE TITLE
Base Layer

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#388]
TODOs for base layer:
- [ ] implement image scaling UI in map
- [x] remove old base layer creation UI
- [x] integrate map state refactoring (depends on #378)
- [x] get images from Nextcloud (depends on #381)
- [ ] connect base layer to backend
- [ ] use proper DB tables
- [x] fix UI (layer vs. element properties)
- [ ] add tests
- [ ] add borders

**Comment by markus2330** [comment]
@badnames

Above I added:

- [ ] fix UI (layer vs. element properties)
- [ ] use proper DB tables

We will talk about the UI today, please have some questions prepared to get this finally done.
