### ISSUE TITLE
Refactor map api

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#389]
- [x] Remove map version from api
- [x] Create layers during map creation

**Comment by ThorbenStaufer** [comment]
I think it would be a good idea to initialize all (standard) layers during map creation, so we don't have to keep track of which layers of the current map already have an entry in the database and which we'd have to create later during map planning. 
In order to do so, I would suggest we define a custom Rust trait for layer initialization/creation. 
This enables us to write a general logic for initializing the layers during map creation and future layer (backend) developers would only need to implement the trait in their DB entity and add an initial layer object in an iterable data structure in the map service.

**Comment by markus2330** [comment]
> I think it would be a good idea to initialize all (standard) layers during map creation, so we don't have to keep track of which layers of the current map already have an entry in the database and which we'd have to create later during map planning.

I fully agree (all of them should initialized as needed).

> In order to do so, I would suggest we define a custom Rust trait for layer initialization/creation.

Do you need help from @kitzbergerg to do so?
