### ISSUE TITLE
testing strategy

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#39]
Should be kicked-off as part of #158:

- [x] backend unit tests
- [x] frontend unit tests
- [x] backend integration tests
- [x] #38 
- [ ] manual tests (before releases etc.)
- [ ] UI component tests (storybook)

**Comment by markus2330** [comment]
Do we need to split frontend testing strategy from this issue?

**Comment by Bushuo** [comment]
> Do we need to split frontend testing strategy from this issue?

@markus2330 I don't think so. If we use Jest for testing it could be a benefit because of compatibility with Storybook. 
But it is not a must. We can go another route with the tests as well.
I do not really have that much experience with UI testing, and I just used Jest as a default.

**Comment by badnames** [comment]
So, since frontend tests have been assigned to me, can we go ahead and add jest or do we still need a decision about that?

**Comment by markus2330** [comment]
As you want it, I assigned you here for now.

**Comment by kitzbergerg** [comment]
After looking through the code a bit I don't think we need unit tests currently. There isn't really any complicated functionality in any specific function that would require such in depth testing.

Integration tests however are very much necessary. According the [rust book](https://doc.rust-lang.org/book/ch11-03-test-organization.html) you should write integration tests entirely separate from your actual implementation. 
This would however mean we would have to split our current code into a library part and a binary part. The main function (binary part) would then only contain very simple stuff like reading config and then calling a function in the library that actually starts the server, while the library contains basically everything else.

I'll look around a bit to see how this is handled in other crates.

In the end I think for the backend we need a decision regarding that.
Separate from that I'll write a doc article where I explain when unit tests are necessary and how to properly set them up (although like I said we currently don't have/probably don't need unit tests).

**Comment by kitzbergerg** [comment]
If you want to have a look at what splitting into binary and library in its simplest for looks like I did that for the mdbook preprocessor: https://github.com/kitzbergerg/mdbook-generate-summary/tree/main/src. If you look at the [main.rs](https://github.com/kitzbergerg/mdbook-generate-summary/blob/main/src/main.rs) there is actually no module defined. Instead the functions are imported from the `lib.rs` file.

**Comment by markus2330** [comment]
Please write the testing strategy in a document in the repository, at least the things that are clear or we already do. It is better to continue discussion from a point where the basics/terminology are made clear first.

I would actually call tests that test a library unit tests, and only frontend code that works together with backend code integration tests. Anyway, please add such terms to glossary, as here terminology is currently quite contradicting.

Yes, a decision about API testing could be useful, as I intuitively would have not done it that way. What benefits does this library approach has? Why not directly test the API by starting up our server?

Btw. please also fix https://github.com/ElektraInitiative/mdbook-generate-summary/issues/1 before people start trying out mdBook next week.

**Comment by kitzbergerg** [comment]
See #289 about backend testing strategy.
