### ISSUE TITLE
document node/npm version

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#395]
v19.4.0 the default npm version is v9.2.0

**Comment by markus2330** [comment]
What about if we let the build server  fail if [frontend/package-lock.json](https://github.com/ElektraInitiative/PermaplanT/pull/376/files/ebef04f7d99ef1061d553dc023152cc8c5fb02fd#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62a) was created from a wrong npm version? Can this somehow be checked?

Maybe too drastically would be that we check if frontend/package-lock.json is unmodified after `npm i` on the buildserver?

A quite easy check would be that the file is still present (so that it does not get removed by accident).

**Comment by 4ydan** [comment]
So in the documentation it says 

```
### Installing Node + Npm

If you are using unix, macOS, and windows WSL, consider using [nvm](https://github.com/nvm-sh/nvm)
to manage your node environment:

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
nvm install --lts
nvm use --lts
```

When I do `nvm use --lts` it selects:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/c89ee0a1-011f-4ee3-9d78-d3c69c03e707)
So does `nvm install --lts`, also install 18.16
I think this should be just changed to our desired version.

**Comment by 4ydan** [comment]
> What about if we let the build server fail if [frontend/package-lock.json](https://github.com/ElektraInitiative/PermaplanT/pull/376/files/ebef04f7d99ef1061d553dc023152cc8c5fb02fd#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62a) was created from a wrong npm version? Can this somehow be checked?
> 
> Maybe too drastically would be that we check if frontend/package-lock.json is unmodified after `npm i` on the buildserver?
> 
> A quite easy check would be that the file is still present (so that it does not get removed by accident).

We could do a grep on the lock file
```
cat package-lock.json | if grep -q 'node": "^19.4"'; then exit 0; else echo "Wrong version of node detected. Please make sure you have 19.4"; exit 1; fi
```
What do you think about this.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/e4b27e5a-3f62-4d40-b0f7-6f5f81da21d0)

**Comment by markus2330** [comment]
> We could do a grep on the lock file

This would probably already avoid the worst?

@Bushuo what do you think?
