### ISSUE TITLE
Membership application

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#400]
A not yet registered user should be able to register via Keycloak. Additionally, there are some user properties we want to gather during the registration process and save in our database. We should also modify the self registration form to include a billing address or other neccessary information for the membership fee (in case not enough coins for a contributing membership are gathered throughout a year). It's also worth considering enabling email verification so that we have a guaranteed channel for communication in case the membership fee is not paid in time.

**Comment by ThorbenStaufer** [comment]
Unfortunately, Keycloak does not allow to set different redirect URLs between login and signup. That means if we want to do a two step registration as proposed in todays meeting, we would need to check in the frontend application if the user already has data in the database or not. We might also set the redirect URL to an to be implemented profile page so that we can perform this database check at the same location where we already would be fetching the user data, thus not needing to share the api implementation with the rest of the app and having a cleaner seperation of concerns.

@markus2330 what are your thoughts on this?

**Comment by markus2330** [comment]
We will implement everything in PermaplanT and store everything in our DB. Yvonne is investigating which data should be asked for. Please tell us in which format you want the information.

Keycloak and Nextcloud (e.g. change amount of available space) will be done manually after registration in PermaplanT (at a later point API calls to Keycloak/Nextcloud might be used to avoid the manual process).

To make sure to not confuse data submitted initially with the up-to-date data in Keycloak, we will use `registration_*` in the table names, e.g. `registration_email` for the email as written in the registration. (Which cannot be seen or changed later in the settings. But obviously it will be removed when a user deletes the account.)

To get a notification when someone registered, we will write something to a Nextcloud chat for now (once #380 is ready).

Email verification ideally should be done with Keycloak (iiuc a password link will be send on temporary accounts).

For the uid we will search for a solution when we configure Nextcloud to work with Keycloak. Maybe it is possible to set the uid manually in Keycloak with the value we already have in PermaplanT.

**Comment by markus2330** [comment]
@ThorbenStaufer The improved version of onboarding is now described in https://github.com/ElektraInitiative/PermaplanT/pull/425/commits/b9e653463c64ee4b17aff28c0cbf83df5b5a4c32

@ThorbenStaufer The forms of Yvonne are still valid, only a few photos (for user and for maps) etc. got added.

@kitzbergerg can you also take a look if this makes sense (especially from Keycloak point of view).
