### ISSUE TITLE
Pre-commit ESlint no empty function error

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#407]
While trying to commit changes I made to the frontend, I was stopped by a pre-commit error that supposedly occured during the `no-empty-function` rule.

<img width="1073" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/207285d4-2b82-4627-b429-fdba960c7d99">

Interestingly enough, there is neither an empty function nor a reference to `getTokens` in the code that somehow raises this error. I don't believe this error stems from my changes, since it also occurs when nothing changes besides an additional new line.
Anyone having an idea what could cause this?

**Comment by Bushuo** [comment]
`getTokens` is a function inside `eslint`. Somehow the sourceCode variable is undefined in there.
Could you share your `MapCreateModal.tsx` file please.

**Comment by ThorbenStaufer** [comment]
The same issue happens in `MapOverview.tsx` which is smaller in size, so I will share that:

<img width="500" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/f968ef79-e464-4618-8740-db6556486869">

**Comment by ThorbenStaufer** [comment]
Fix incoming with PR resolving #345.
