### ISSUE TITLE
Complete schema description for plants

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#408]
Currently, there is no description of how elements of the plant layer, or any other layer that draws shapes in the frontend will be saved to the database.
Also, a naming convention for such elements would be good.
We could call an element of the plant layer simply `PlantLayerElement`

I would like the entity to look like this
```rust
/// Note: `add_date` and `remove_date` are for handling visibility in the timeline feature.
/// A plant can be created but not added (visible) on the map, the same holds for removed but not deleted.
pub struct PlantLayerElement {
    /// The database id of the record.
    pub id: uuid,
    /// The plant that is planted.
    pub plant_id: i32,
    /// The x coordinate of the position on the map.
    pub x: f32,
    /// The y coordinate of the position on the map.
    pub y: f32,
    /// The width of the plant on the map.
    pub width: i32,
    /// The height of the plant on the map.
    pub height: i32,
    /// The rotation of the plant on the map.
    pub rotation: f32,
    /// The x scale of the plant on the map.
    pub scale_x: f32,
    /// The y scale of the plant on the map.
    pub scale_y: f32,
    /// The date the plant was created.
    pub creation_date: NaiveDate,
    /// The date the plant is supposed to be deleted.
    pub deletion_date: Option<NaiveDate>,
    /// A path to the icon that is used to draw the plant.
    pub icon_path: String,

    /// The date the plant seed was put into the ground (maybe not yet on the map).
    pub seed_date: NaiveDate,
    /// The date the plant was added to the map.
    pub add_date: NaiveDate,
    /// The date the plant was harvested.
    pub harvest_date: NaiveDate,
    /// The date the plant was removed from the map.
    pub remove_date: Option<NaiveDate>,
}
```

**Comment by markus2330** [comment]
Great work, looks already very good. PR would be awesome :+1: 

- coordinates should be i32, as we have a fixed raster in cm and elements (like plants) cannot be placed in between
- begin/end -> add/remove, see glossary
- remove_date is Option
- harvest != removal of plant

**Comment by Bushuo** [comment]
@markus2330 
> Great work, looks already very good. PR would be awesome 👍
>
Yes, I will add this as a follow-up PR for #393 also implementing the database layer

> coordinates should be i32, as we have a fixed raster in cm and elements (like plants) cannot be placed in between
>
Then this means we need to handle rotation differently. Because based on my short research and experience, konva shapes have their origin point in the top/left corner.
Rotating with the transformer rotates them around the center of the transformer but that also changes the x/y of the shape to some fraction.

> begin/end -> add/remove, see glossary
remove_date is Option
harvest != removal of plant
>
Perfect, I integrated that above.

**Comment by markus2330** [comment]
> Then this means we need to handle rotation differently. Because based on my short research and experience, konva shapes have their origin point in the top/left corner.
> Rotating with the transformer rotates them around the center of the transformer but that also changes the x/y of the shape to some fraction.

Isn't it possible to simply discard such small variations (while the user rotates)? Having deterministic floating point calculations is a big topic on its own which I would prefer to avoid. I don't know to which extent Konva already solves it?

Otherwise simply removing everything after the comma when the user ended the rotation/movement/... actions sounds to me like the easiest solution?

>  Perfect, I integrated that above.

Thx!

One more thing: the common data about Elements on the map should be separated. What about:

```rust

/// Represents elements on a map.
/// This is usually not directly used but part a more specific element (depending on layer) instead.
#[typeshare]
#[derive(Serialize, Deserialize, ToSchema, Clone)]
pub struct ElementDto {
    /// The database id of the element.
    pub uuid: String,
    /// The x coordinate of the position on the map.
    pub x: i32,
    /// The y coordinate of the position on the map.
    pub y: i32,
    /// The rotation of the plant on the map in degrees (0-360).
    pub rotation: f32,
    /// The x scale of the plant on the map.
    #[serde(rename = "scaleX")]
    pub scale_x: f32,
    /// The y scale of the plant on the map.
    #[serde(rename = "scaleY")]
    pub scale_y: f32,
}

/// Represents plant planted on a map.
/// E.g. a user drags a plant from the search results and drops it on the map.
#[typeshare]
#[derive(Serialize, Deserialize, ToSchema, Clone)]
pub struct PlantLayerObjectDto {
    /// General element data.
    pub element: ElementDto,
    /// The plant that is planted.
    #[serde(rename = "plantId")]
    pub plant_id: i32,
    /// The width of the plant on the map.
    pub width: i32,
    /// The height of the plant on the map.
    pub height: i32,

    /// The date the plant seed was put into the ground (maybe not yet on the map).
    pub seed_date: NaiveDate,
    /// The date the plant was added to the map.
    pub add_date: NaiveDate,
    /// The date the plant was harvested.
    pub harvest_date: NaiveDate,
    /// The date the plant was removed from the map.
    pub remove_date: Option<NaiveDate>,
}
```
