### ISSUE TITLE
Caching Problem

### ISSUE THREAD

**Issue by lukashartl** [ElektraInitiative/PermaplanT#415]
@markus2330 @lukashartl  Apart from that there is a different unrelated issue I noticed while testing this:
There seems to be some caching issue (at least on my browser). When I open https://dev.permaplant.net/doc/api/swagger/ui/ a broken version of `https://dev.permaplant.net/` appears. After I clear the browser cache it works. When I then open https://dev.permaplant.net/ and afterwards https://dev.permaplant.net/doc/api/swagger/ui/ it is broken again (and clearing the cache fixes it again). So it seems that somehow `https://dev.permaplant.net/` caches the page for all subpaths even though it shouldn't.

_Originally posted by @kitzbergerg in https://github.com/ElektraInitiative/PermaplanT/issues/383#issuecomment-1572597451_

**Comment by markus2330** [comment]
Thank you for creating a separate issue. As already said in #383 I was able to reproduce it.

As it is only affecting dev, I think it is low-prior. For now we can "fix" it by simply documenting that a clear cache is needed to have a look at swagger/ui/.

Btw. I think we should remove the `cache-control: no-cache` header. It creates inconsistency to the productive system and also does not really seem to help.

**Comment by lukashartl** [comment]
The `Cache-Control` header is set on all environments at the moment. The fact that it doesn't work leads me to the conclusion, that something happens BEFORE the browser uses it's HTTP Cache.

And it seems that the Service Worker also has it's own sw-cache (see [this link](https://web.dev/service-worker-caching-and-http-caching/)).

So probably there is something in React/Vite/etc. we have to configure for it to work. I know that in some frameworks you have to actively increase the `version` attribute inside the `package.json`, so the service worker knows when an updated version is available on the server.

**Comment by markus2330** [comment]
It works for me now, please reopen on any further troubles.
