### ISSUE TITLE
disable pages when not logged in

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#417]
When logged in, the user should see a selection page (not the landing page), where:

- [x] seeds
- [x] maps

are shown.

Also only when logged in, it should be allowed to visit these two endpoints (directly going there without being logged in should be 401).

**Comment by absurd-turtle** [comment]
@markus2330 I redirect the user to the overview page when they are not logged in and try to visit a restricted site.
The overview page prompts the user to log in.
After successfully logging in the content of the overview page is displayed.

**Comment by markus2330** [comment]
For maps something was done in #482
