### ISSUE TITLE
Links to tutorials of React/Zustand/design etc.

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#43]
Please add links to getting started/learning tutorials in the contribution guidelines for all of our essential technologies.

**Comment by markus2330** [comment]
@Bushuo can you add a few links in our documentation that you recommend to learn the technologies we use (in particular React)?

**Comment by Bushuo** [comment]
Sure, I will add them later today or tomorrow.

**Comment by markus2330** [comment]
Thank you!

**Comment by Bushuo** [comment]
@markus2330 I think we can close this. I added all the relevant links to the contribution docs.
