### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#430]
hey @absurd-turtle, would it easily be possible to

## 1

have a butterfly on the landingpage following the mouse arrow similar to https://codesandbox.io/s/framer-motion-spring-transition-e6c8dm?from-embed=&file=/src/App.tsx

On a click on the butterfly it should stop following the mouse.

Obviously super-low priority :wink: 

## 2

A possibly a bit more "useful" animation would be for the layer selection, https://www.framer.com/motion/layout-animations/ at the very bottom

## 3

Top most one on https://www.framer.com/motion/animate-presence/ for the full-screen images in the gallery

**Comment by absurd-turtle** [comment]
Except the butterfly it should be easy enough.
It's a cute idea but I don't think we have the time for it and if it's poorly implemented it could be more annoying than nice.

**Comment by markus2330** [comment]
Yes, I agree, (1) easily could be annoying, so let us better not do it anytime soon. It is probably more an Easter egg on a specific day in the year.

**Comment by markus2330** [comment]
@tschawax do you have experience with such animations?
