### ISSUE TITLE
Nextcloud Image gallery pagination

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#434]
Implement pagination for the [Nextcloud image gallery](https://github.com/ElektraInitiative/PermaplanT/blob/master/frontend/src/features/landing_page/components/PhotoGallery.tsx).
Content from Nextcloud can be requested by using the utility functions in /src/features/nextcloud_integration/

- subdivide directory content of Nextcloud into pages 
- request one page of images at a time
- the amount of images one page includes can be selected by the user

- [ ] page UI
  - [ ] next and previous page buttons
  - [ ] clickable page number including first, last and a max of 3 pages before and 3 pages after the current one
  - [ ] selection of images per page
  - [ ] display a loading spinner while the image is still loading

For an example implementation of pagination have a look at the SeedsOverviewList component.

**Comment by markus2330** [comment]
Thanks for creating the issue!

**Comment by markus2330** [comment]
I close it for now, as FLOSS was cancelled. We will reopen when needed.
