### ISSUE TITLE
3 high severity vulnerabilities

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#441]
Should be fixed before release:

```
# npm audit report

fast-xml-parser  <4.2.4
Severity: high
fast-xml-parser vulnerable to Regex Injection via Doctype Entities - https://github.com/advisories/GHSA-6w63-h3fj-q4vw
fix available via `npm audit fix --force`
Will install webdav@2.10.2, which is a breaking change
node_modules/fast-xml-parser
  webdav  >=3.0.0
  Depends on vulnerable versions of fast-xml-parser
  node_modules/webdav

vite  3.0.2 - 3.2.6
Severity: high
Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//) - https://github.com/advisories/GHSA-353f-5xf4-qw67
fix available via `npm audit fix`
node_modules/vite

3 high severity vulnerabilities
```

**Comment by 4ydan** [comment]
I have never done this, but is the fix for this npm audit and pushing the new package-lock.json?

**Comment by markus2330** [comment]
I am also no expert in npm but generally if there are no API changes in the packages something like this should be everything.

@Bushuo do you maybe have further insights in `npm audit`?

**Comment by Bushuo** [comment]
I think, updating both vite and webdav should be no problem.
I would do it manually though.

webdav (fast-xml-parser) vulnerability is fixed in version 5.2.2
vite vulnerability is fixed in version 3.2.7

**Comment by 4ydan** [comment]
maybe add a high vulnerabilities check to CI?

**Comment by markus2330** [comment]
@4ydan it can be done manually before releases, so it is not urgent
