### ISSUE TITLE
Send unauthenticated requests to Nextcloud through backend/middleware

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#452]
Currently users who are not logged in cannot get information from Nextcloud.
Public information like public shares for images and public chats should be available for unauthenticated users.
To enable this we need a middleware which offers endpoints for unauthenticated users.
The middleware should fetch the required resource from Nextcloud and forward it to the user.
The middleware should be as restrictive as possible to avoid potential security vulnerabilities.
The resources for unauthenticated users should be read-only. As of now there is no need for unauthenticated users to change any resources!

**Comment by absurd-turtle** [comment]
Well, I kind of did that and they said no, it was related to the CORS issue we were having but it is a very similar use case.
https://github.com/nextcloud/spreed/issues/9616

**Comment by markus2330** [comment]
IMHO this was a different question. We want documentation about how their app is already handling unauth API requests (publicly shared conversations) so that we don't need to reverse engineer what they are doing.

**Comment by absurd-turtle** [comment]
I have opened an issue:
https://github.com/ElektraInitiative/PermaplanT/issues/452#issuecomment-1596985829

**Comment by markus2330** [comment]
They already gave an answer and it somehow sounds it should be simple?
