### ISSUE TITLE
Backend plants layer placing: relations and heatmap

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#457]
Implement the plants layer heatmap. Follow up to:
- #420

**Comment by markus2330** [comment]
See previous comment https://github.com/ElektraInitiative/PermaplanT/pull/427#discussion_r1229568362: the heatmap should not be separated from relations. I renamed the issue.

**Comment by markus2330** [comment]
Btw.: Unless we have one API call that returns an image (file), and not JSON, then separated API calls might make sense.
