### ISSUE TITLE
problems in practicalplant database

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#46]
- [x] some plants have sandy and heavy clay but some values in between are missing

Suggestions/value to be checked from Nursultan:

- [x] mature size height and width. remove inexact entries e.g. `8-10`. values should be fixed numbers without any non-numeric characters (add TODO)

To be checked/fixed by Yvonne:

- [x] Prunus avium: self fertile, self sterile
- [x] check FLOWER_TYPE
- [x] fix mature size height and width

**Comment by aidnurs** [comment]
Suggestions/value to be checked from Nursultan:

- [ ] mature size height and width. remove inexact entries e.g. `8-10`. values should be fixed numbers without any non-numeric characters

**Comment by markus2330** [comment]
Thanks! I added it at top-post (then GitHub counts tasks and counts which of them are checked. Feel free to check the points when done.). As discussed it is probably most efficient if @aidnurs adds TODO markers in the CSV and Yvonne checks and decides. Yvonne will need to do several adjustments anyway.

**Comment by markus2330** [comment]
To be checked if permapeople.org fixes these issues #102
