### ISSUE TITLE
remove variety in SeedDto

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#462]
There is a left-over in SeedDto: variety should be completely removed, as it is already contained in plant_id.

**Comment by markus2330** [comment]
still present in backend/src/model/dto.rs

**Comment by horenso** [comment]
variety should also removed from the database tables seeds, correct?

**Comment by markus2330** [comment]
Yes, exactly! :heart:

(line 380 of backend/migrations/2023-07-01-152628_squashed_setup/up.sql is useless but a new migration is needed to remove it)
