### ISSUE TITLE
improve build time

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#472]
- [ ] comment out all not needed columns in plants

**Comment by 4ydan** [comment]
Is it ok if I add this to  #241 and close this issue?

**Comment by markus2330** [comment]
Yes, is okay. But you can also add this issue as one of the tasks in #241, depending on if specific discussion is needed or an extra PR will be created.

**Comment by 4ydan** [comment]
I tried doing this https://doc.rust-lang.org/cargo/reference/timings.html, but my graph was empty, maybe I need to be on the nightly/unstable toolchain for this

**Comment by 4ydan** [comment]
So once I get the permission on every node, I would cache what is recommended [here](https://rustwiki.org/en/cargo/guide/cargo-home.html) on /root/, which I would assume to be around 10gb, and then use it across all jobs by mounting it as volume inside each container.

**Comment by markus2330** [comment]
/root is not a good choice, maybe /var/cache/rust

> then use it across all jobs by mounting it as volume inside each container.

Is it safe to do so? Afaik Cargo locks its registry somehow, I don't know which locking mechanism they use and if this is safe across containers. Better to have independent copies per container/node/....

> And yea reducing the columns would be one of the biggest gains for sure, there seems to be a 2-3 years ongoing issue inside diesel, which states that they have a recursive macro that explodes on big tables.

Yeah, it is not easy to fix and also not a long-term solution: eventually we need most of the columns.

**Comment by temmey** [comment]
i commented out 55/101 properties from the plants table for now. see #644

**Comment by markus2330** [comment]
Great job, we can close this.
