### ISSUE TITLE
import sizes of plants

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#479]
- [ ] 3 classes for width

**Comment by temmey** [comment]
The 'plants' table currently includes 'width', 'height', and 'spread' columns, with the first two having rough size data in meters, while 'spread' is blank.

For the import, We've planned to use enum types such as 'narrow', 'medium', 'wide', 'na' and 'low', 'medium', 'high', 'na' to provide a general size estimation.

Should I import the data from the .ods file in the existing 'height' and 'spread' columns, or create a new 'plant_height' column in the 'plants' table? I'm open to other suggestions for naming this new plant height column.

**Comment by markus2330** [comment]
Replace existing columns, as the current ones are strings and cannot be used like this. We also need to reduce the columns and not increase them :wink:

**Comment by temmey** [comment]
right now we import sizes of plants with our `mergedDatasets.csv`, i extended the `scraper/src/merge_datasets.js` for that.

**Comment by markus2330** [comment]
Ok perfect, so will simply update our `mergedDatasets.csv`. Unfortunately then we also need to update @yvonnemarkl's created small DB #633

**Comment by temmey** [comment]
when #644 is accepted i can create a pr for the extended scraper script

**Comment by markus2330** [comment]
You can always create new PRs on the top of older ones.

**Comment by markus2330** [comment]
@temmey did you already add the unique names for the sizes?

**Comment by temmey** [comment]
> @temmey did you already add the unique names for the sizes?
yes i implemented `plant_spread` with 'narrow','medium','wide'

**Comment by markus2330** [comment]
Please connect issues with PRs, otherwise it is unclear what happens where. I assume this issue is about #692?

Let us coordinate here about the process of importing sizes of plants:

0. Yvonne will do a few fixes in plants.csv
2. @temmey runs `npm run merge:datasets` (with the updated plants.csv when Yvonne gives the ok) once manually and then copy the new mergedDatasets.csv to Nextcloud.
3. Yvonne will then check.
4. @4ydan or I will then copy the updated file to all nodes (pr, dev and www.permaplant.net).

**Comment by markus2330** [comment]
Step 0 was done, Yvonne created plants.csv with 

0e2b1666d8edeb86b12e9d85f9fbb17ddf86da87fa4304737f8f5f253a193b87  plants.csv
847547673e283a3e63adca215d09769a97c75dde57ba57667c4ff52239afd515  plants.ods

@temmey now mergedDatasets can be created, please tell us here when it is ready

**Comment by markus2330** [comment]
Yeah, and it seems like @temmey is already on holidays, so the plan already seems to have failed...

@4ydan can you try to merge the CSVs?

**Comment by 4ydan** [comment]
Ok, does this look good? What now?
```
root at ☁️ f8200a04ec8a in /workspaces/PermaPlant/scraper/data on master
$ npm run merge:datasets

> scraper@1.0.0 merge:datasets
> node src/merge_datasets.js

[INFO] Merging datasets...
[INFO] practicalPlants:  6219
[INFO] permapeople:  8785
[INFO] reinsaat:  939
[INFO] Merged practicalPlants and permapeople:  8901
[INFO] Writing merged dataset to CSV file...
[INFO] Total number of plants:  9810

root at ☁️ f8200a04ec8a in /workspaces/PermaPlant/scraper/data on master
$ sha256sum plants.csv 
0e2b1666d8edeb86b12e9d85f9fbb17ddf86da87fa4304737f8f5f253a193b87  plants.csv
```

**Comment by markus2330** [comment]
Great!

Does it now include the sizes?

If yes, you can copy it to Nextcloud/Database

If you import it, does the Plants table have the sizes, too?

**Comment by 4ydan** [comment]
There is no column with the name size or similar in `mergedDatasets_new`

**Comment by temmey** [comment]
> There is no column with the name size or similar in `mergedDatasets_new` 

they are called spread and height

**Comment by 4ydan** [comment]
> they are called spread and height

Thank you, yes these two exist as columns.

**Comment by temmey** [comment]
> `import` as in migrate and open the webapp and see it on the map page?

im not sure if that feature is already implemented in the frontend (see #686 ), but `SELECT spread, height FROM Plants;` shows me the correct values

**Comment by temmey** [comment]
>  Thank you, yes these two exist as columns. There is also width.

only in the csv, we dont import all values from the csv into the database.  
We only import to columns defined in 'scraper/src/helpers/dp_plants_columns.js'

**Comment by markus2330** [comment]
We won't include that feature for the release.

**Comment by markus2330** [comment]
@temmey @4ydan can you please update what the current status is? Please always write if you changed/updated sthg in Nextcloud. E.g. it is unclear to me what `a6b8d981a7023e0d7e53a13788468db15e2cf8a397c1a5b83d8d7911a7d52ed8  mergedDatasets_new.csv` is?

Unfortunately, @temmey did not clearly document it, afaik we need to create mergedDataset.csv using the scraper of #692 and then merge #721 to get the sizes?

**Comment by temmey** [comment]
Without #692, there won't be any spread values in our database. It translates the numerical values we have to our defined enum types. #721 depends on these spread values to change the size of the plants on the map; otherwise, all plants will have their standard size (50px).

From #692 

> The pipeline is failing because I added the translation process to the mergeDatasets.js file, but we're not running npm run merge:datasets in our CI pipeline. As a result, the values are not getting translated, leading to the failure.
> So we either:
need to run npm run merge:datasets (and copy the necessary files too) so that the translation process can take place and the pipeline will run successfully.
> OR
> I implement the translation step into the npm run insert step.

**Comment by temmey** [comment]
>     1. @temmey runs `npm run merge:datasets` (with the updated plants.csv when Yvonne gives the ok) once manually and then copy the new mergedDatasets.csv to Nextcloud.

our scraper cant do that, it only merges 
`data/detail.csv` // Practical plants dataset
`data/permapeopleRawData.csv` // Permapeople dataset
`data/reinsaatRawData.csv` // Reinsaat dataset

but plants.csv isnt used. 

so know im not sure how i should implemnt @yvonnemarkl changes, while also using the mergeDataset.csv....
In nextcloud its written that:
```
The source of mergedDatasets.csv are:

8bbc5bb97c8519244db422fb0ddb2e7aef073941df037b6395a67c08bd1d13c4  plants.csv
dc884bd9ba75003c41d78dd3a935e1813e4006f4c912537b36705aca2e272c11  plants.ods

but how are they the source? They look like a database data dump.

**Comment by 4ydan** [comment]
I cant tell, I tried to do what you described here https://github.com/ElektraInitiative/PermaplanT/issues/479#issuecomment-1647342571
I got the data from NC, and performed a merge on rebased master with plants.csv having the desired checksum.

**Comment by temmey** [comment]
>  I got the data from NC, and performed a merge on rebased master with plants.csv having the desired checksum. 
What exactly did you do with plants.csv? Am I missing something?

**Comment by markus2330** [comment]
> What exactly did you do with plants.csv? Am I missing something?

@temmey This was something in use between aidnurs and @yvonnemarkl, let us see if we can reconstruct how to use it. The idea was to manually overwrite some old/wrong data. This isn't highest priority now, though. As first step we want a mergedDatasets.csv with the sizes.

The other needed files for merging are in the Nextcloud folder (in subfolders of the Database folder), so you still should be able to merge it (without Yvo's updates). Please compare then if there are any differences to our current mergedDatasets.csv

mergedDatasets_new.csv from @4ydan looks quite identical to mergedDatasets.csv, it only has an additional useless column subfamily in it (we decided we don't need it, see doc/database/hierarchy.md for latest information about which data we need).

Please also copy Sizes.csv to the Database folder and update the README.md with this information.

**Comment by temmey** [comment]
Okay, but since `npm run merge:datasets` does not use `plants.csv`, I need to do something here. I think refactoring `merge_datasets.js` to use `plants.csv` as a base and also replace all null values with values from `mergedDatasets.csv` to create a new, correct `mergedDatasets.csv`.

**Comment by markus2330** [comment]
> Okay, but since npm run merge:datasets does not use plants.csv, I need to do something here. I think refactoring merge_datasets.js to use plants.csv as a base and also replace all null values with values from mergedDatasets.csv to create a new, correct mergedDatasets.csv.

Yeah, but I think this cannot be done today. Please create a issue about having a manual process with overrides.

And I also think that `mergedDatasets.csv` doesn't have @yvonnemarkl's changes, it looks to similar to @4ydan's `mergedDatasets_new.csv` which obviously doesn't have changes from `plants.csv`.

**Comment by temmey** [comment]
> Yeah, but I think this cannot be done today. Please create a issue about having a manual process with overrides.

ok i will create an issue for that. 

> And I also think that mergedDatasets.csv doesn't have @yvonnemarkl's changes, it looks to similar to @4ydan's mergedDatasets_new.csv which obviously doesn't have changes from plants.csv.

Yes, I think so too. But this should be fixed with the refactored merge_datasets.js. Maybe I can manage to finish it today. I will upload the `mergedDatasets.csv` without @yvonnemarkl changes for now.

**Comment by markus2330** [comment]
> will upload the mergedDatasets.csv without @yvonnemarkl changes for now

Yes, exactly. And please:

- diff with the previous mergedDatasets.csv which changes there are.
- document everything in the README.md how to merge datasets at the moment (without plants.csv).
- include sha256sums of all the input+output

I think this is a perfect example why documentation is important, so let us do better from now on :+1:

**Comment by temmey** [comment]
I did all that, you can use mergedDatasets_newisher.csv or mergedDatasets_new.csv, but should use the same data source for now, since plant.csv isn't used atm.

I will try to finish #726 asap so we can import all changes from 'plant.csv' into our database.

**Comment by markus2330** [comment]
Please first finish comparison, documentation etc.

If mergedDatasets_newisher.csv is like mergedDatasets_newisher.csv but with spread, this issue would be finished.

#726 is a rather big problem and needs a clear process how to work with the csvs. And it probably gets heavily influenced once the hierarchy gets implemented, so better not to do fast shots there. Better to fix further small usability bugs.

**Comment by markus2330** [comment]
I replaced mergedDatasets.csv in NC with the newest variant.

Please also tell us the sha256 of all the input.

**Comment by temmey** [comment]
> I replaced mergedDatasets.csv in NC with the newest variant.
> 
> Please also tell us the sha256 of all the input.

i also wrote it into the nextcloud/database/README.md

permapeopleRawData.csv b83c1a445a057275a3c818f7b9baaf34e756b27df00eeff74ba0f2072f981819

reinsaatRawData.csv 7cd60ffe597602f96310ddaacb53ef4153e5af5e04cb45a47714a7d87a9f245f

detail.csv cef77a1a7893e199f24c4d7a0d114fce901541afa55323a27aa4504d41da31f4

**Comment by markus2330** [comment]
Mmh, so where is the Sizes.csv from Pavlo?

**Comment by temmey** [comment]
> Mmh, so where is the Sizes.csv from Pavlo?

I don't know; I can`t find it. 
@yvonnemarkl sent me a file called `Copy of Calculations dynamic Polyculture design tool - vegetables.xlsx`, where some data regarding height and spread is inside. But since it only has 100 entries, I think it's faster to manually put them into plants.csv instead of extending the `merge_dataset.js`.

**Comment by markus2330** [comment]
Where did you get the spread data from? In the mergedDatasets.csv used to be only 9 entries that contained spread

**Comment by temmey** [comment]
There are the values for width and height. Width describes the spread of the plant. So I just translated them to the enum value and called them spread.

**Comment by markus2330** [comment]
> But since it only has 100 entries, I think it's faster to manually put them into plants.csv instead of extending the merge_dataset.js.

But then it would be problematic when we reimport them.

I think #692 doesn't make sense without Pavlo's data (it would make more sense to simply use the number as spread). I'll ask @yvonnemarkl what the plan was...

Can you check if Pavlos's data and the data we got from width is different?

**Comment by temmey** [comment]
> But then it would be problematic when we reimport them.

When we use `npm run insert:plants`, it will override all values if `plants.unique_name` already exists and update the `plants.updated_at` value.

So in the future, when we implement #726 and it's going to use `plants.csv` as a base, it would overwrite all values.

> I think #692 doesn't make sense without Pavlo's data (it would make more sense to simply use the number as spread). I'll ask @yvonnemarkl what the plan was...
> 
> Can you check if Pavlos's data and the data we got from width is different?

Well, I can write a quick script for that.

**Comment by temmey** [comment]
There are differences, but `Copy of Calculations dynamic Polyculture design tool - vegetables.xlsx` seems kinda confusing. For example:
Arugula has two different height values: low & medium
Summer Squash has two different spread values: medium & wide.

**Comment by markus2330** [comment]
Ok, thank you for your investigations.

We were not careful enough in our preparations, Copy of Calculations dynamic Polyculture design tool - vegetables.xlsx is useless. The value of 0.25 (as was in mergedDatasets.csv) is much more useful than the array of categories low & medium.

So we will, at a later time, use the width as number in the map editor.
