### ISSUE TITLE
Set Nextcloud Env Variable in Frontend

### ISSUE THREAD

**Issue by lukashartl** [ElektraInitiative/PermaplanT#486]
Is the Nextcloud base URL set correctly on pr.permaplant.net?

_Originally posted by @badnames in https://github.com/ElektraInitiative/PermaplanT/issues/465#issuecomment-1595761147_

**Comment by markus2330** [comment]
@lukashartl any update on that? Can you confirm that it is (not) set?

**Comment by lukashartl** [comment]
It is not set at the moment.
I'll prepare a PR for that.

**Comment by lukashartl** [comment]
Fixed in #486
