### ISSUE TITLE
plants layer UI-UX improvements

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#492]
- [x] icons display on/off
- [ ] sort layers: #478 
- [ ] touch screen: #512 
- [x] remove plant name
- [x] default icon for plants
- [x] display name of plant on hover
- [x] add titles for icons
- [x] planting notification border color secondary
- [ ] redraw on resize (can't reproduce the bug)
- [x] add the first plant to selection on drag

**Comment by markus2330** [comment]
Thanks for creating the issue!

I added #478 above next to "sort layers" (I think we mean the same by that).

Touch screen support is not urgent, as we can communicate the beta testers with devices to use (or even exclude people without computer for first round). A separate issue describing the issues we have should be enough for now.
