### ISSUE TITLE
Set borders of map (backend)

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#494]

**Comment by markus2330** [comment]
@badnames please at least add a list of tasks so that is clear what an issue includes

@kitzbergerg does the backend endpoint already exist?

**Comment by kitzbergerg** [comment]
> @kitzbergerg does the backend endpoint already exist?

The map polygon (boundaries of the map) are implemented as part of #566 (heatmap). To get the actual boundaries I think you just have to loop through the points in the polygon and take the (x_min,y_min,x_max,y_max) with would then be the boundaries of the map.
How this interacts with the base layer I don't know (and there is nothing in that direction implemented in the base layer PR as far as I understand).

**Comment by markus2330** [comment]
I don't see an endpoint to get/set the polygon (boundaries of the map):question:  How is the endpoint called and how to use it?

**Comment by kitzbergerg** [comment]
> I don't see an endpoint to get/set the polygon (boundaries of the map)❓ How is the endpoint called and how to use it?

The polygon is part of the map itself. So it would be part of the map get endpoint. For create you are able to set the polygon, however there is currently no way to update the polygon. This can however be easily achieved later on simply by adding it to the `UpdateMapDto` as `Option` (but I would wait with that for the frontend as it currently isn't even clear if/where that would be possible/sensible).

**Comment by markus2330** [comment]
This issue is about providing a way to update the boundaries (polygon).
