### ISSUE TITLE
Base-Layer: integrate with backend

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#495]
- [x] send state to backend on apply
- [x] fetch state from backend on map initialization
- [ ] fetch state from backend on sse signal
- [ ] fix docs (ER, function docs etc.)
- [ ] filter baseLayerImage for layerId in find endpoint
- [x] create one baseLayerImage on map creation

**Comment by markus2330** [comment]
Looking forward to see it! You can write here how you want to call the table and the API so that you already get feedback befor creating a PR.

**Comment by markus2330** [comment]
Assigned @kitzbergerg for backend part

**Comment by markus2330** [comment]
@badnames can we unassign @kitzbergerg here?
