### ISSUE TITLE
LayersChanged Notification for copies/alternatives of layers

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#498]
We do not want to refetch the layers all the time, so adding an alternative, or removing one should trigger a LayerChangeNotification over SSE.
On retrieval of the notification, the layers should be refetched.

Depends on alternatives to be implemented.

**Comment by markus2330** [comment]
Thanks for creating the issue! So nothing here is to be done before alternatives/copies of layers exist?

**Comment by Bushuo** [comment]
> Thanks for creating the issue! So nothing here is to be done before alternatives/copies of layers exist?

Yes, I think so.
