### ISSUE TITLE
DB on Dev is not in sync with schema

### ISSUE THREAD

**Issue by lukashartl** [ElektraInitiative/PermaplanT#502]
## Steps to Reproduce the Problem

???

## Expected Result

Pipeline builds successfully.

## Actual Result

Pipeline fails since 5 days ago on Dev, because

```
# diesel migration run --locked-schema
Command would result in changes to /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend/src/schema.rs. Rerun the command locally, and commit the changes.
```

The difference is actually:

```diff
288a289
> diesel::joinable!(plantings -> layers (layer_id));
```

Did someone modify the database schema directly or is something missing here?
Could only be @markus2330 or me.

## System Information

- PermaplanT: master
- Operating System: Dev Instance

ping /cc @markus2330

**Comment by markus2330** [comment]
Thanks for bringing it up. See in #471 what I needed to do, so that we were able to do plantings on the weekend.

**Comment by lukashartl** [comment]
```
$ cat 2023-06-11-122400_plantings/up.sql
-- Your SQL goes here
CREATE TABLE plantings (
    id UUID PRIMARY KEY,
    layer_id INTEGER NOT NULL,
    plant_id INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    rotation REAL NOT NULL,
    scale_x REAL NOT NULL,
    scale_y REAL NOT NULL,
    FOREIGN KEY (layer_id) REFERENCES layers(id), <-- is missing in dev
    FOREIGN KEY (plant_id) REFERENCES plants(id)
);
```

In #471 @markus2330 did:

```sql
ALTER TABLE plantings DROP CONSTRAINT plantings_layer_id_fkey;
```

So I'll revert it by doing

```sql
garden=# DELETE FROM plantings WHERE layer_id = 2;
DELETE 15
garden=# ALTER TABLE plantings ADD FOREIGN KEY (layer_id) REFERENCES layers(id);
ALTER TABLE
```

And pipeline is running: [master 233](https://build.libelektra.org/job/PermaPlanT-Folder/job/PermaplanT/job/master/233/)

**Comment by ThorbenStaufer** [comment]
> The layer_id in plantings was probably only some leftover from earlier versions?

layer_id is critical for plantings to work. It currently violates foreign key constraints, because the frontend does not fetch the layer ids on master yet. This feature is part of #488.

**Comment by markus2330** [comment]
@ThorbenStaufer Great, so then it should be fixed now.
