### ISSUE TITLE
Plants relations import scrapper and db design

### ISSUE THREAD

**Issue by temmey** [ElektraInitiative/PermaplanT#508]
I'm creating the insert script for the plant relation scraper right now, so I also need a table to insert it into. 

The document [/usecases/assigned/add_plant_relationships.html](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/assigned/add_plant_relationships.md) claims the following properties of a relation:

> The two sides of the relationship can be:
> - Specific plants
> - Taxonomic ranks which are not specific plants
>
> The type of the relationship can be:
> - Companion
> - Antagonist
> - Neutral
> Confidence
> A description providing information on the why's and how's.

Given these requirements, I'm proposing the following table:

```sql
CREATE TYPE public.relationship_status AS ENUM (
    'companion',
    'antagonist', 
    'neutral'
);

CREATE TABLE plants_relations (
    unique_name_plantA  TEXT NOT NULL,
    relationship relationship_status  NOT NULL,
    Confidence SMALLINT,
    unique_name_plantB TEXT NOT NULL,
    description TEXT
);
```
The part "Taxonomic ranks which are not specific plants" could be implemented in the backend, in a way that every unique plant from that taxonomic rank gets an entry into the plants_relations table.

Furthermore, it should be assumed that every plant which has no relationship with another plant in that table, should be considered neutral. The enum type "neutral" only exists in the case of  [/usecases/assigned/review_plant_relationships.html.](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/assigned/review_plant_relationships.md).  If a user disagrees with the current state of a relationship, it should be changeable to neutral.

What are your opinions on that? If it's okay, I would start writing the necessary migration file for the import.

**Comment by markus2330** [comment]
Thanks for writing it up!

The migration script is already part of #487 and, except of if we should use ids or text to refer to the plants, already without dispute. So I think you should put your work on top of #487 and simply use the migration that is already there.

Btw. we recently decided not to include confidence, where is it still mentioned?

**Comment by temmey** [comment]
> Btw. we recently decided not to include confidence, where is it still mentioned?
in this userstory https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/assigned/add_plant_relationships.md

> The migration script is already part of #487 and, except of if we should use ids or text to refer to the plants, already without dispute. So I think you should put your work on top of #487 and simply use the migration that is already there.

ok should i close this issue then?
