### ISSUE TITLE
plants: use proper icons

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#509]
from Nextcloud via #474

**Comment by absurd-turtle** [comment]
We implemented three icons: tomato, onion and potato in #492.
Are there more already?

**Comment by markus2330** [comment]
Yvonne says the vector-file is missing (in the folder "Vektordaten"): Gurke 'Cucumis sativus_vector_transparent_background.svg'

**Comment by markus2330** [comment]
The project  says this is in review but I cannot find a PR associated with it?

**Comment by absurd-turtle** [comment]
I guess we can close it. I just left it open for you to check if the icons are correct now.
