### ISSUE TITLE
show frontend+backend version number

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#510]

**Comment by markus2330** [comment]
At the top so that it is also visible when you are in the map etc. The "GitHub" can be moved at the bottom as the link is actually not always (e.g. when editing maps) needed.

**Comment by markus2330** [comment]
Please make sure to not make extra API calls. There are already too many config API calls (if easily possible, try to reduce them).

**Comment by 4ydan** [comment]
Is this ok? On the top left
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/4be3cf51-efa1-4240-9392-bc2ae32e75e5).
and Github on the footer with a logo 
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/c92d264d-cb53-458e-8715-ee478104a5f9)

**Comment by kitzbergerg** [comment]
Since the backend is already done I'll assign this to @4ydan.

**Comment by 4ydan** [comment]
done in #574
