### ISSUE TITLE
add yourself to team

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#511]
@temmey @4ydan please add yourself to doc/AUTHORS.md and [frontend/src/features/landing_page/components/Team.tsx](https://github.com/ElektraInitiative/PermaplanT/pull/432/files#diff-c56af96ef00c42eb10feb56ddb00cb03b58acfdae2ec1c953f298ed9d5eb1d6a)

**Comment by 4ydan** [comment]
Should be done when #519 is merged

**Comment by markus2330** [comment]
As there is no overlap in files, you can also easily create several PRs via different branches all forking from master.

If there is some overlap, you can also branch of existing branches to create several PRs with (slight) changes between the PRs.

**Comment by temmey** [comment]
should be done when #601 is merged, and can be closed then.

**Comment by markus2330** [comment]
Please write in the commit messages that it `closes #601`, then this happens automatically.
