### ISSUE TITLE
touchscreen support

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#512]
Tracking issue for touchscreen device support.

- [ ] select plant
- [ ] delete button

**Comment by markus2330** [comment]
@tschawax is touchscreen support something you are interested in/you have experience with?

**Comment by markus2330** [comment]
Great, it would be amazing to have Touch, Tablet and macOS support. :heart:

**Comment by markus2330** [comment]
Can you add this to your responsibilities in authors.md?

**Comment by markus2330** [comment]
Not a priority at the moment.
