### ISSUE TITLE
plant relations enhancements

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#514]
The implementation of plant relations (#487) have the following left overs.

Missing features are:
- [ ] hierarchy
- [ ] limiting to plants on maps (which is only relevant once hierarchy is actually implemented, then there are hundreds of matches. Without hierarchy there are only a few matches anyway.)

Like described in the PR description of #487 limiting the returned relations might be complicated as there would be multiple joins involved. It might also be necessary to execute subqueries. 
I'm not entirely sure, but it might be necessary to use raw SQL here instead of diesels abstractions.

**Comment by markus2330** [comment]
Thank you for summarizing the left-overs and including implementation hints. :+1: 

As probably @temmey will work on it, we most likely will switch to raw SQL.

**Comment by markus2330** [comment]
@tschawax to actually limit the query is nice-to-have, important is the hierarchy for plant relations.

**Comment by markus2330** [comment]
@tschawax Yes, sorry. #739 might be for you, but this one is for @temmey
