### ISSUE TITLE
document prerequisites needed for compilation

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#520]
- [ ] RAM Size: > 8GB with 8GB swap; or better 16GB
- [ ] we only support Linux

Original Issue by @4ydan:

## Steps to Reproduce the Problem

Have a docker container and run cargo build --release in the backend folder.
## Expected Result

A normal build without problems

## Actual Result

Compiling diesel eats my ram. It goes up to my whole wsl memory and freezes my wsl.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/764e1f72-5bc3-4e53-ab81-f77ba4010675)

## System Information

- PermaplanT: master
- Operating System: Windows 10 devcontainer mcr.microsoft.com/devcontainers/rust:1-1-bullseye image
- Browser: none

neofetch

OS: Debian GNU/Linux 11 (bullseye) on Windows 10 x86_64 
Kernel: 5.10.16.3-microsoft-standard-WSL2 
Uptime: 13 mins 
Packages: 436 (dpkg) 
Shell: bash 5.1.4 
 Terminal: vscode 
 CPU: 12th Gen Intel i5-12600K (4) @ 3.686GHz 
Memory: 2338MiB / 13993MiB 

diesel 2.0.1
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

## Note

This could potentially cause problems in Jenkins maybe?

Not sure if related
https://github.com/rust-lang/cargo/issues/10583

possible solution?
https://github.com/LukeMathWalker/cargo-chef

or maybe this if we dont need 128 columns? 
[32-columns config in diesel](https://docs.diesel.rs/2.0.x/diesel/index.html#:~:text=32%2Dcolumn%2Dtables%3A%20This,minimize%20your%20compile%20times.)

**Comment by markus2330** [comment]
I am afraid that compiling our backend and its dependencies simply is very memory intensive, your report doesn't surprise me. I just tested and the compilation sometimes used more than 9G RES, 11G VIRT for me, so with 14GB it might easily run out of memory.

Is there some way you can increase the memory size? If there is, we should simply document which size is needed and close that issue.

> or maybe this if we dont need 128 columns?

This is most likely the main cause of the build time but I don't think it causes the memory problem. Compilation of diesel etc. itself needs more resources than compilation of our backend. (As also indicated in our screenshot and I was able to verify it locally.)

We currently need the 128 columns but we could temporarily comment out some columns to come below 64 columns, I already created  #472 for that. Unfortunately, @temmey didn't report any success in that regards.

**Comment by 4ydan** [comment]
Yea I slowly came to realize, that there is not much that can be done. I just increased my VMEM for now. Maybe adding
```
ENV RUSTFLAGS="-C link-arg=-fuse-ld=lld"
```
improved my performance on compiling a bit, but I m not sure.
Mentioning it in the requirements would be awesome, so people are not surprised like me.

**Comment by markus2330** [comment]
I reopened so that we don't forget documenting.

> I just increased my VMEM for now. 

To which value did you increase it?

We have one CI agent (i7) which has 8GB Ram with 8GB swap, it seems to compile there, too?

**Comment by 4ydan** [comment]
My wsl2 vmem is now at 14GB. When I compile the backend I reach up to 13GB.

**Comment by 4ydan** [comment]
> I reopened so that we don't forget documenting.
> 
> > I just increased my VMEM for now.
> 
> To which value did you increase it?

My wsl2 vmem is set now to 16GB.

> We have one CI agent (i7) which has 8GB Ram with 8GB swap, it seems to compile there, too?

Interesting, maybe there is a difference when running it in wsl2, idk.
