### ISSUE TITLE
Map Grid

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#522]
Display a reference grid that gives the user a visual queue of distances on the map.

**Comment by badnames** [comment]
@markus2330 
Is this the kind of grid you had in mind?
Colors and styling are still work in progress and easily changed.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/5b8f90dc-4081-4933-820d-56c840812851)

**Comment by markus2330** [comment]
Thank you for asking up front! A 1m grid sounds like a good idea. I don't know how it will work on various zoom levels, though.

Styling: We would prefer that only the intersections get a dot (not lines that go through everything)

A user should be able to enable/disable the grid via the grid-dots icon, see  #363 on the left toolbar.

Btw. the frog was funny in the beginning but we should now **really** start using real maps with realistic plantings on them. Otherwise the danger that use cases are misunderstood is **very high** as we already experienced several times.

**Comment by badnames** [comment]
> Thank you for asking up front! A 1m grid sounds like a good idea. I don't know how it will work on various zoom levels, though.

I forgot to add, there are currently three zoom levels:
- 10 cm
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/047afb13-e7e6-4f03-9a3f-acabc793fff6)
- 1 m (like in the image above)
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/cd1d79c3-56f3-4394-833c-260287137ac5)
- 10 m
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/29cdbf8a-4609-414e-9743-e9f745a2fb2c)

**Comment by badnames** [comment]
> Styling: We would prefer that only the intersections get a dot (not lines that go through everything)
Ok here is the grid with a little less obnoxious coloring for comparison:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/d8d87730-a860-4137-b494-8d91b2d7c41e)

And with dots instead of lines it would look like this:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/fd76c992-009c-434c-9c7f-a5248fa619af)

**Comment by markus2330** [comment]
We like dots much more. The color should be our standard blue (as visible in Layers).

**Comment by badnames** [comment]
> We like dots much more. The color should be our standard blue (as visible in Layers).

I assume you mean sea blue, correct?
(FYI, we also have a shade called 'bondi' if you prefer)

**Comment by markus2330** [comment]
@badnames please always check if issues are correctly in the project (this one was not in the project at all)

**Comment by markus2330** [comment]
> @markus2330 how will we handle controlling the grids visibility/opacity?
>    Like any other layer, perhaps without making it selectable?
 >   Not at all (the grid is always visible)?
 >   Using some other mechanism?

Using the left toolbar with a grid icon, I already wrote that in some comment.

**Comment by markus2330** [comment]
> I assume you mean sea blue, correct?

Let us try the main color, see doc/guidelines/ui.md "Colors".
