### ISSUE TITLE
CI: job cacher

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#527]
```
+ npm run format:check

> permaplant@0.2.0 format:check
> prettier --check .

sh: 1: prettier: not found
```

https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/master/240/pipeline

**Comment by 4ydan** [comment]
Looks like a disk space issue?
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/4de4a92a-a627-4400-9b6e-66c3414deef8)

**Comment by markus2330** [comment]
Thank you for the triage! @lukashartl can you have a look at which containers are affected and clean them?

**Comment by lukashartl** [comment]
I've wiped all the servers, caches, etc 😀

**Comment by 4ydan** [comment]
Do we have this plugin in jenkins? [Jobcacher](https://plugins.jenkins.io/jobcacher/)

**Comment by markus2330** [comment]
> I've wiped all the servers, caches, etc 😀

Thank you :heart: 

> Do we have this plugin in jenkins?

We can install any plugin if it somehow reasonably maintained (in particular: won't break future updates of Jenkins)

> [Jobcacher](https://plugins.jenkins.io/jobcacher/) Might come handy with this https://github.com/ElektraInitiative/PermaplanT/issues/241.

Great, if you have experience with it we can give it a try. What would it cache that we don't cache yet?

**Comment by 4ydan** [comment]
> > [Jobcacher](https://plugins.jenkins.io/jobcacher/) Might come handy with this #241.
> 
> Great, if you have experience with it we can give it a try. What would it cache that we don't cache yet?
I dont have experience with it, I just thought maybe it can solve the caching problem and autoclean up or just restrict the cache space.

**Comment by markus2330** [comment]
@lukashartl @fel115 What do you think?

**Comment by 4ydan** [comment]
Also possible solution, write a script that fails when the disk space is about to get short. With a soft and hard limit for example.

**Comment by markus2330** [comment]
We already have monitoring and automatic regular cleaning but sometimes it hits the CI pipeline nevertheless.

A script that does some environmental checks is a good idea but I think it is rather low-prior. @4ydan can you start an issue with ideas what we could do? Also take the features and issues from Elektra into account.

**Comment by 4ydan** [comment]
> A script that does some environmental checks is a good idea but I think it is rather low-prior. @4ydan can you start an issue with ideas what we could do? Also take the features and issues from Elektra into account.

Alright. #543
