### ISSUE TITLE
staged deployment

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#53]
1. pr.permaplant.net building (all) PRs: Just for quick testing before merging PRs. If there are bugs in the database migration scripts, we will wipe the database (`diesel database reset`)
2. dev.permaplant.net (building master) should already work stable enough that reset is only rarely needed (and if it is needed, we will fix it manually as we have production data there as long as we don't have a release)
3. (later) www.permaplant.net definitely should never reset the database, should only build&deploy releases

**Comment by markus2330** [comment]
In 1. we should consider to always wipe the database as there is no guarantee that two different PRs have different migration scripts. The disadvantage of this is that the pr CI runs don't actually test if the migration will work.

**Comment by markus2330** [comment]
If we remove the database, we should also reinsert everything. This works by running `npm run insert data/detail.csv` in the folder scraper.

**Comment by lukashartl** [comment]
pr.permaplant.net has it's own vhost and it's own certificates. Proxy setup works and the backend server is 100% ansible so far 😄

Currently preparing the deployment scripts and ansible for pr/dev 🚀 

I'll keep you updated.
