### ISSUE TITLE
Testing tools decision

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#531]
Add all used testing tools in doc/decisions/backend_testing_strategy.md and frontend_testing_strategy.md

**Comment by markus2330** [comment]
Thanks for creating the issue! Btw. you don't need to create a decision about the strategy, only about which tools we use.

**Comment by 4ydan** [comment]
This can be closed with #619 I guess?

**Comment by markus2330** [comment]
Yes, you can write in a git comment `closes #531` and it will automatically close.
