### ISSUE TITLE
Hover tooltip for map edit buttons

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#536]
Use case: doc/usecases/current/map_creation.md

Follow-up to #515.

- [ ] Add title attribute to edit/duplicate buttons on the MapCard Components.
- [ ] Text should describe function of those buttons.

**Comment by markus2330** [comment]
Thanks for creating the issue. I've added the info which use case the issue refers to to and've put the tasks in todo-items.

Are you not assigned on purpose? Are these bigger tasks?

**Comment by ThorbenStaufer** [comment]
> Are you not assigned on purpose? Are these bigger tasks?

No, the tasks are pretty easy. I simply forgot to assign myself.
