### ISSUE TITLE
Diesel migration says invalid char in unquoted filename

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#540]
I'm trying ubuntu for the first time now and I get this problem.
Anyone had this before and knows the solution? Did I forget something?

## Steps to Reproduce the Problem

```Dockerfile
# docker build -t permaplant_ubuntu .
# docker run -it --rm permaplant_ubuntu
# docker run -it --rm --network permaplant_devcontainer_permaplant-dev permaplant_ubuntu

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV RUSTFLAGS='-C link-arg=-fuse-ld=lld'
ENV RUST_LOG='backend=info,actix_web=info'
ENV RUST_BACKTRACE=1
ENV POSTGRES_USER=permaplant
ENV POSTGRES_DB=permaplant
ENV POSTGRES_PASSWORD=permaplant
ENV PGPASSWORD=permaplant
ENV DATABASE_URL=postgres://permaplant:permaplant@db/permaplant
ENV BIND_ADDRESS_HOST=0.0.0.0
ENV BIND_ADDRESS_PORT=8080

RUN apt-get update && \
    apt-get install -y --no-install-recommends sudo tzdata locales ssh && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update \
    && apt-get -y install --no-install-recommends \
    sudo \
    curl \
    git \
    make \
    strace \
    python3-pip \
    clang \
    lld \
    libpq-dev \
    libssl-dev \
    pkg-config \
    postgresql-client \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf -y https://sh.rustup.rs | sh
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Add .cargo/bin to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install diesel_cli@2.0.1 --no-default-features --features postgres && cargo install typeshare-cli

ENV PERMAPLANT_PATH /home/batman/permaplant
RUN mkdir -p ${PERMAPLANT_PATH}
WORKDIR ${PERMAPLANT_PATH}
RUN git clone https://github.com/ElektraInitiative/PermaplanT

```

After the container is started:
```sh
cd PermaplanT
typeshare ./backend --lang=typescript --output-file=./frontend/src/bindings/definitions.ts
cd backend && LC_ALL=C diesel setup && LC_ALL=C diesel migration run
```

## Expected Result

diesel to do migration

## Actual Result

error parsing patch: invalid char in unquoted filename
## System Information

- PermaplanT: master
- Operating System: Docker container ubuntu:20.04
- Browser: -

**Comment by markus2330** [comment]
Thank you for reporting this issue. The issue is new to me.

Can you give a bit more context in the Actual Result? Is there no other line printed at all? (If it isn't we probably need a strace to see which file it was looking at.)

Is the output from `LC_ALL=C diesel setup` or from `C_ALL=C diesel migration run`?

**Comment by 4ydan** [comment]
Its from `C_ALL=C diesel migration run`. Yes thats the only output, how could I get that strace?

**Comment by markus2330** [comment]
` C_ALL=C strace -o strace.log diesel migration run` and if we are lucky, the program exits shortly after opening a migrations file (or schema file). Maybe there are better diagnostic/debug utilities within diesel? (I didn't see anything in `--help` though)

You could also try `--locked-schema` maybe this gives some insight.

**Comment by 4ydan** [comment]
Thank you very much. I will have a look at it soon.

**Comment by markus2330** [comment]
Btw. I assume you have a fresh setup? Otherwise you maybe want to do `diesel database reset` (warning: wipes the whole PermaplanT database)

**Comment by 4ydan** [comment]
I logged the trace. It has to do with backend/src/schema.patch

```
poll([{fd=4, events=POLLIN|POLLERR}], 1, -1) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "2\0\0\0\4T\0\0\0\307\0\6column_name\0\0\0003\263\0\4\0\0"..., 16384, 0, NULL, NULL) = 1038
openat(AT_FDCWD, "/workspaces/PermaplanT/backend/src/schema.patch", O_RDONLY|O_CLOEXEC) = 6
statx(6, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_BASIC_STATS|0x1000, stx_attributes=0, stx_mode=S_IFREG|0777, stx_size=1085, ...}) = 0
lseek(6, 0, SEEK_CUR)                   = 0
read(6, "diff --git a/backend/src/schema."..., 1085) = 1085
read(6, "", 32)                         = 0
close(6)                                = 0
close(5)                                = 0
sendto(4, "X\0\0\0\4", 5, MSG_NOSIGNAL, NULL, 0) = 5
close(4)                                = 0
sendto(3, "X\0\0\0\4", 5, MSG_NOSIGNAL, NULL, 0) = 5
close(3)                                = 0
write(2, "error parsing patch: ", 21)   = 21
write(2, "invalid char in unquoted filenam"..., 33) = 33
write(2, "\n", 1)                       = 1
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7f4953bf7000, 12288)           = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```


I tried to reset.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/2cd8d19d-1e66-48a6-86f7-14145fa50e9a)

**Comment by markus2330** [comment]
weird, `backend/src/schema.patch` is only ASCII? Can you check with `file backend/src/schema.patch`?

Is the `git` repo in a clean state? `git checkout backend/src/schema.patch`

`sha256sum backend/src/schema.patch`
a4a6ea7ccaf777b787204c1cde5b46472d4c416b6740c0d8f4d4512fa973ef5b  backend/src/schema.patch

**Comment by 4ydan** [comment]
Very weird, it works now. I updated the top post with a Dockerfile

**Comment by markus2330** [comment]
> Very weird, it works now.

In which folder do I need to be to run `docker build -t permaplant_ubuntu .`?

> Only thing I changed was installing rust myself inside the dockerfile instead of through vscode remote container features.

Maybe it was a different version of rust?

We use `rustc 1.67.1 (d5a82bbd2 2023-02-07)`

**Comment by 4ydan** [comment]
> > Very weird, it works now.
> 
> In which folder do I need to be to run `docker build -t permaplant_ubuntu .`?
> 
In the folder with that Dockerfile inside.

> > Only thing I changed was installing rust myself inside the dockerfile instead of through vscode remote container features.
> 
> Maybe it was a different version of rust?
> 
> We use `rustc 1.67.1 (d5a82bbd2 2023-02-07)`

I used that one too before.
```json
"ghcr.io/devcontainers/features/rust:1": {
      "version": "1.67.1"
    }
```
And now it worked with rust latest.

**Comment by markus2330** [comment]
> In the folder with that Dockerfile inside.

Which is that folder? And which branch? But if I understood you correctly it it not possible to reproduce it it anymore?

> And now it worked with rust latest.

So then it might be some file tempering/corruption?

Anything else we can do in this issue or we close it?

**Comment by 4ydan** [comment]
> > In the folder with that Dockerfile inside.
> 
> Which is that folder? And which branch? But if I understood you correctly it it not possible to reproduce it it anymore?
> 

My bad, it's on my local machine. I just put it for copy and paste.

> > And now it worked with rust latest.
> 
> So then it might be some file tempering/corruption?
> 
> Anything else we can do in this issue or we close it?

I guess we can close this.
