### ISSUE TITLE
Codecoverage

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#542]
Analyze the codecoverage of the backend code.
- [ ] Locally and in jenkins.
- [ ] Generate a report in jenkins.
- [ ] Have a 80% coverage check (for the backend) in CI.
Not sure yet, which tool to use. Will look into this some time soon.

**Comment by markus2330** [comment]
@kitzbergerg do you know some tool?

Are there also codecoverage tools for frontend? (maybe separate issue)

**Comment by kitzbergerg** [comment]
> @kitzbergerg do you know some tool?
> 
> Are there also codecoverage tools for frontend? (maybe separate issue)

I have never looked into that no. After a quick look something like the following might be usable (although I haven't tested it)
- https://github.com/xd009642/tarpaulin
- https://github.com/taiki-e/cargo-llvm-cov

**Comment by markus2330** [comment]
not urgent, can also be done locally as needed for now
