### ISSUE TITLE
CI: clean workspaces

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#543]
From time to time, the pipeline on node a7 seems to run out of space and fail silently.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/e989af11-a65c-43fe-b5bd-7ecfc5eadb01)

Silently, because no error about the diskspace is thrown and it seems as if a package was just not installed.

Possible solutions for this:
- [Medium-Hard] A [jenkins](https://plugins.jenkins.io/jobcacher/) plugin that manages the cache.
- [Easy] Write a script in jenkins that checks the diskspace with a soft- and hardcap. Throws an error when the softcap is reached, so it can be cleaned manually before a real error like above happens.

**Comment by markus2330** [comment]
The cache plugin sounds better and better :wink:

**Comment by markus2330** [comment]
@lukashartl @fel115  What do you think?

**Comment by lukashartl** [comment]
Yeah, if the cache plug-in works it might be worth to give it a shot.

We also have the workspace cleaner plug-in installed, so we should add cleanWs to the/all pipeline(s).

**Comment by lukashartl** [comment]
The workspaces for PermaplanT are already around 7GB large (`backend/target`).
Starting today, I'll automatically wipe all workspaces older than 1 day during the night hours.

We should still implement `cleanWs`.

**Comment by 4ydan** [comment]
> We should still implement `cleanWs`.
Good idea, I added it to the list #544

**Comment by markus2330** [comment]
Is this really low prior? We should avoid trapping into out-of-disc again.

**Comment by 4ydan** [comment]
Good point, I dont remember why I put prio.

**Comment by markus2330** [comment]
@4ydan is this issue still needed? If the cache plugin is still a thing, we probably should track it differently.

**Comment by 4ydan** [comment]
I havent seen the error again, so I guess the diskspace is managed well currently.
