### ISSUE TITLE
Left-over issues template reorder and small changes

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#559]
- [ ] Something is wrong in the indentation of the tasks here 
- [ ] A few more items is probably a good idea. And space between [ ] was missing.
- [ ] Also reorder: first tasks, then use cases then related pull requests.

Maybe also change the input field to a text area where autocompleting PR's by `#` works.

**Comment by markus2330** [comment]
Thx for splitting up the issues.
