### ISSUE TITLE
[h1] CI diesel times out

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#565]
I realized that sometimes compiling diesel times out in the pipeline.

_Originally posted by @4ydan in https://github.com/ElektraInitiative/PermaplanT/issues/555#issuecomment-1618542913_

**Comment by 4ydan** [comment]
https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/PR-555/12/pipeline

here for example

**Comment by markus2330** [comment]
I think this improved now. Please reopen if it occurs again.

**Comment by 4ydan** [comment]
https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/doc%2F520-prerequisites/1/pipeline

**Comment by markus2330** [comment]
@lukashartl did you restart h1 or something?

**Comment by lukashartl** [comment]
Not in the last few days

**Comment by 4ydan** [comment]
another timeout on h1
[https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/PR-653](https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/PR-653/3/pipeline)

**Comment by 4ydan** [comment]
multiple timeouts on master today, all on h1, but also one manually started that passed on h1.

**Comment by markus2330** [comment]
@4ydan maybe we remove h1 until @lukashartl finds a solution?

**Comment by markus2330** [comment]
Why 3 nodes? You simply deactivate just the h1 node?

**Comment by 4ydan** [comment]
Yes, sorry wrong word. I meant executors. It is one node with 3 executors.

**Comment by lukashartl** [comment]
> > Do we know how much RAM h1 has ?
> 
> I don't know, infrastructure docu unfortunately is still quite minimal.

Has been updated in the current infrastructure PR.

**Comment by markus2330** [comment]
Do we know something about the circumstances when these errors happen? Is it maybe heavy load? Logging this before a step starts might help to identify the issue.

Wild guess: We could try  to reduce the number of executors?

**Comment by lukashartl** [comment]
I've checked the logs and I can see that the kernel OOM killer is killing some rustc processes. So Rust is deliberately allocating lots of memory.

So setting executors to two might be worth giving it a try.

**Comment by lukashartl** [comment]
I've set it to 2. Let's observe.

**Comment by markus2330** [comment]
> kernel OOM killer

Thx for finding out!  Why not increasing swap?

> I've set it to 2. Let's observe.

Thx.

The error happened 16 hours ago in https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-677/2/pipeline

I restarted there.

**Comment by 4ydan** [comment]
> Do we know something about the circumstances when these errors happen?

It happens always on cargo build. My first guess would be a ram issue when compiliation happens.

**Comment by markus2330** [comment]
Seems to work now. Please reopen on problems.
