### ISSUE TITLE
Introduction Tour: Map Editor v.1

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#575]
We want to add an interactive introduction tour to the map editor, explaining its core features to the user.
The first iteration should include a "road to your first plant", guiding the user through all steps needed to place their first plant.
The introduction tour should award a blossom upon completion.

- [x] Create a new table for backend managed user data, including a flag for the completion of the introduction tour.
- [ ] Implement a small guided tour for the map editor in the frontend.
- [ ] Lay out the foundations for gaining blossoms (backend API + frontend notification)

**Comment by markus2330** [comment]
Looks great!
