### ISSUE TITLE
backend: say goodbye on exit

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#578]
### Tasks

- [ ] The server should send a goodbye to all connected clients via server-sent events (SSE) on exit. After this message, users need to refresh their frontend (and hopefully the backend is already online before the user manage to refresh)
- [ ] The server should also log a message when being terminated (Currently only "Starting server" is being logged many times).

### Use case

offline

### Related Pull request

#574

**Comment by markus2330** [comment]
I also added "- [ ] The server should also log a message when being terminated (Currently only "Starting server" is being logged many times)." above. Unrelated but should be trivial.

@Bushuo this is part of the read-only functionality. I hope it isn't a big thing, please say if it is.

**Comment by Bushuo** [comment]
@markus2330 
Should be no problem.

> The server should send a goodbye to all connected clients via server-sent events (SSE) on exit. After this message, users need to refresh their frontend (and hopefully the backend is already online before the user manage to refresh)

Should the frontend reload itself or should there be a button that enables a reload (in a toast for example).
The only problem I see with this approach is, that a SSE connection is only established, once the user navigates to the map.
So for all other parts of the application this mechanism will not work.

What is the reason behind this mechanism?
If it has to do with updates and versions, maybe we can send the version via http header and validate it on the backend.
If the respective error is returned the frontend can display such a message centrally.

**Comment by markus2330** [comment]
>  Should the frontend reload itself or should there be a button that enables a reload (e.g. in a toast)?

I was thinking about that it should be read-only mode, so hopefully no extra frontend implementation for this issue.

> The only problem I see with this approach is, that a SSE connection is only established, once the user navigates to the map.
> So for all other parts of the application this mechanism will not work.

Which other parts do you mean?

> What is the reason behind this mechanism?
> If it has to do with updates and versions,

Yes, exactly, it is about updates or maintenance.

> maybe we can send the version via http header and validate it on the backend.
> If the respective error is returned the frontend can display such a message as part of a central error handling.

Yes, that would probably be a better solution, as it would also work when the SSE doesn't reach the clients and suddenly there is a new API. For now the SEE goodbye+/config request when going online again should be enough.

**Comment by Bushuo** [comment]
> Yes, that would probably be a better solution, as it would also work when the SSE doesn't reach the clients and suddenly there is a new API. For now the SEE goodbye+/config endpoint request (with version check) when going online again should be enough.

Ok, let's do it with SSE first.
