### ISSUE TITLE
Improve Continuous Integration

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#586]
### Tasks

My goal was to refactor and improve the continuous integration process and speed up the feedback loop.
By creating a devcontainer, the environment was made more transparent.
By creating the Makefile, developers can perform the same tests locally as in the pipeline, therefore possibly reduce the feedback loop and load on the pipeline.
By creating the Makefile we can remove the ci/build-script folder and encourage everyone to use the same routines.
By reducing the images in the pipeline to only one, we have to only maintain one image and save space.

The below PR's summarize the main goal of unifying the process and increasing the feedback loop.

### Related Pull request

 - [x] #552 
 - [x] #549 
 - [ ] #585
 - [ ] #588
 - [x] #557 
 - [ ] Add fail fast support
 - [ ] Update documentation

**Comment by markus2330** [comment]
Amazing work! :heart:

**Comment by 4ydan** [comment]
I will merge these ideas into #544.
