### ISSUE TITLE
Additional mouse keys not working on Konva canvas

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#598]
### Describe the Bug

This is a pretty minor thing, but I noticed that extra mouse buttons (further than MB3) do not provide their expected functionality.

### Steps to Reproduce the Problem

Open the map editor and use a mouse button other than left-click, right-click and mouse-wheel in the main canvas area.

### Expected Result

I use my MB4 and MB5 buttons for quick browser history navigation.
When pressing MB5 I expect to navigate back to the last visited page (in this case the map overview).

### Actual Result

Nothing.
The button does not navigate back, but it registers as a beginning drag action.

### PermaplanT version

master

### Operating System

Windows

### Browser

Microsoft Edge

**Comment by markus2330** [comment]
Thanks for testing! Good to know that also Microsoft Edge is being used.

> The button does not navigate back, but it registers as a beginning drag action.

Was this added by accident?

**Comment by markus2330** [comment]
I don't have these buttons on the mouse, so I'll close it for later.
