### ISSUE TITLE
Enable external link check

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#605]
If this is something we want to have, with mdbook-linkcheck we can enable `follow-web-links` inside book.toml. Currently there is many errors before we can put this to CI.

**Comment by markus2330** [comment]
Yes, we definitely want this, it is great if all links are known to work.

**Comment by 4ydan** [comment]
The URL's seem to be unauthorized for nextcloud and even permaplant.net
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/f6c6e5c6-cb82-4322-a90b-51002e5af3fc)
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/8da99395-2173-4ddd-b36e-7f3ec16e9571)

I also experienced this with https://pr.permaplant.net when performing e2e tests.

**Comment by 4ydan** [comment]
Also it seems to return not found when the links exist.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/e53e475a-33ea-4612-9a87-efe2730d09cb)

[rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer)
[Prettier ESLint](https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint)

**Comment by 4ydan** [comment]
I see https://github.com/Michael-F-Bryan/mdbook-linkcheck/issues/30

**Comment by 4ydan** [comment]
I don't think we will benefit from this addition, if we merge this functionality, developers will need to blacklist links from the checker that just don't work and it will slow down merging because of pipeline failures. Obviously only for docu stuff, but still.

**Comment by markus2330** [comment]
>  Hard to automate it then, since it's inside mdbook build, will need two different book.tomls?

I would simply modify book.toml locally.

> We could do that if there is no real benefit from it.

I think so, what actually was done should be in our code/documentation.

**Comment by 4ydan** [comment]
So we can close this and maybe write a line to the release doc to perform this external link check manually?

**Comment by markus2330** [comment]
Thx, will add it in the release doc.
