### ISSUE TITLE
Small blue rectangle in map editor

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#610]
### Describe the Bug

There is a small blue rectangle in the bottom center of the map editor.
I believe it is connected to the "placing plant" info box, since the rectangle dissapears while the info box is open.

### Steps to Reproduce the Problem

Open the map editor and look at the bottom center of the canvas.

### Expected Result

No blue rectangle.

### Actual Result

There is a blue rectangle.

### PermaplanT version

master

### Operating System

Windows

### Browser

Microsoft Edge

**Comment by markus2330** [comment]
Thanks for reporting. I also see it now, it is super-tiny.

**Comment by Bushuo** [comment]
@markus2330 @ThorbenStaufer Will be fixed by #546

**Comment by markus2330** [comment]
Was fixed, thx!
