### ISSUE TITLE
create a map with same name

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#614]
### Steps to Reproduce the Problem

- create a map with the name "test" for one user
- create another map with the (same) name "test" for another user

### Expected Result

the second user should get an error that the map is already created

### Actual Result

you cannot press the "Erstellen" button. It gets blue surrounded, but nothing happens:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/2a6c9e3f-ba55-4a30-b3ee-f4ff365b95e1)

### PermaplanT version

a3230f03b717535bfd4c58d07a107c71cf02b105 on feature/435-plant-relationship-lines

### Operating System

Linux

### Browser

Tried with Firefox and Vivaldi

### Additional info/logs

The server log says:

```
[2023-07-11T15:56:52Z ERROR backend::error] Error executing diesel SQL query: doppelter Schlüsselwert verletzt Unique-Constraint »map_unique_name«
```

**Comment by ThorbenStaufer** [comment]
Error notification for that was part of #599 and works as intended on [master](https://dev.permaplant.net).
Your feature branch does not include the changes I made for error notifications yet.
