### ISSUE TITLE
Mdbook link checker warning policy

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#615]
Currently the warning policy is set to ignore (inside book.toml).
There is two more levels:
- warn: Displays warnings. (E.g when you use brackets in .md and it's not a link)
- error: Every warning is an error.

We want to get to the error level eventually.

**Comment by markus2330** [comment]
Thanks for creating the issue! Hopefully we have the "error" setting soon, so that broken links don't creep in again. :bug:
