### ISSUE TITLE
"Sorry! I couldn't load the image. ..." is always displayed.

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#617]
### Describe the Bug

The toast with the image loading error is always displayed.

### Steps to Reproduce the Problem

Open the landing page.
Check the network tab, all images are loading.

### Expected Result

The message only appears if a image fails to load.

### Actual Result

The message appears anyway.

### PermaplanT version

master

### Operating System

MacOS

### Browser

Chrome Version 114.0.5735.198 (Official Build) (arm64)

**Comment by markus2330** [comment]
Thank you for reporting! I also noticed it recently and thought it might be because I had foreign domains disabled (which cloud.permaplant.net is seen from localhost).

Must be a quite recent change?

@4ydan is it possible to check in the smoke test for absence of errors?

**Comment by markus2330** [comment]
I added it to the milestone as it would be quite ugly to have this in the user study.

**Comment by 4ydan** [comment]
I have this bug too.

> @4ydan is it possible to check in the smoke test for absence of errors?
I will have a look. Probably we can assert there is no toast message, when we don't expect one.

**Comment by markus2330** [comment]
> I will have a look. Probably we can assert there is no toast message, when we don't expect one (maybe only for error messages).

:+1:

We need to collect such requirements for the decision so that we can find the best suitable e2e framework.

**Comment by ThorbenStaufer** [comment]
I pushed a potential fix to this bug. Can't test it locally, since my local requests to NC always fail, but it should solve the issue.
