### ISSUE TITLE
productive deployment fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#620]
### Describe the Bug

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/78470ef5-7faa-4181-97a0-b50861d009e1)

### Steps to Reproduce the Problem

trigger release

### Expected Result

:partying_face: :tada: 

### Actual Result

:cry: `No such saved stash ‘mdbook’`

### PermaplanT version

813bd98bcd952af9596fa62c26408c734fdf5e06

### Operating System

Linux

### Browser

NA

**Comment by 4ydan** [comment]
It seems like there is no mdbook stage

**Comment by markus2330** [comment]
note that for production the ci/Jenkinsfile.release is used

**Comment by 4ydan** [comment]
oh.. yea that's release

**Comment by 4ydan** [comment]
so there is no mdbook in prod, I just remove it I guess?

**Comment by markus2330** [comment]
Great that you are already working on it :heart: :rocket: 

Yes, eventually we want an mdbook also for production.

Would be great if we can do the release today, I already prepared the after-release PR  #622 with current date. I am now off for about 2h.

**Comment by markus2330** [comment]
It worked :partying_face: 

v0.2.2 released

now with version indication https://www.permaplant.net/

but also with #617

**Comment by 4ydan** [comment]
oh no : (, I was just wondering if that fix was already merged, I also have it in my tests ^^

**Comment by 4ydan** [comment]
I will go fix the broken links again, before more can squeeze in.

**Comment by markus2330** [comment]
Yes, important is that CI fails on newly introduced problems. This is often the only way that really works :wink:
