### ISSUE TITLE
Base Layer: connect to backend

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#627]

**Comment by markus2330** [comment]
Did you see that there is already #584? Please review it.

**Comment by badnames** [comment]
> Did you see that there is already #584? Please review it.

Yes, I already made a few changes to get it ready for review.

**Comment by markus2330** [comment]
@badnames can we unassign @kitzbergerg here?

**Comment by markus2330** [comment]
Is something missing here?

**Comment by badnames** [comment]
The base layer is connected to the backend, therefore this issue should be done.

Other components of the base layer such as the borders should be part of their own follow up issues.
