### ISSUE TITLE
CI Backend

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#63]
After #55 we can now also run `cargo clippy` in the CI. It should be executed in docker context before it gets deployed on our agents. 

- [ ] cargo clippy `cargo clippy -- -Dwarnings` (so that it fails on errors)
- [ ] cargo check/fix¹
- [ ] cargo fmt (needs #62)¹
- [ ]  build docu (`cargo doc`)
- [ ] treat warnings as error, see https://github.com/ElektraInitiative/PermaplanT/pull/72#issuecomment-1464906301
- [ ] tests (`cargo test`)

Check with `git diff` if any changes occurred in the source dir, if yes, fail.

**Comment by markus2330** [comment]
@kitzbergerg is this everything the CI needs to do for backend/Rust?

**Comment by kitzbergerg** [comment]
All commands:
```shell
RUSTFLAGS="-D warnings"
RUSTDOCFLAGS="-D warnings"

cargo fmt --check
cargo check
cargo clippy
cargo doc
cargo test
```

This fails basically every time anything is wrong (wrong format, some warning while compiling, when clippy complains, when doc or doc links are broken, when a test fails).
That way you don't have to mess with `git diff`.
