### ISSUE TITLE
improve plant relations import

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#636]
### Tasks

- [ ] duplicates should be removed from CSV (@yvonnemarkl)
- [ ] implement hierarchy

### Use case

plants_layer

### Related Pull request

#606

**Comment by markus2330** [comment]
@temmey why is this in review? I don't think it is implemented yet.

**Comment by temmey** [comment]
> @temmey why is this in review? I don't think it is implemented yet.

sorry, i thought this was leftover issue from #606
