### ISSUE TITLE
frontend: use&scale heatmap while planting

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#637]
### Tasks

 - [ ] retrieve heatmap when clicking at plant (before relations are fetched)
 - [ ] scale heatmap correctly
 - [ ] display it

### Use case

plants_layer

### Related Pull request

#566

**Comment by markus2330** [comment]
Probably duplicate to #592

**Comment by badnames** [comment]
> Probably duplicate to [#592](https://github.com/ElektraInitiative/PermaplanT/issues/592)

Correct. 
Lets close this issue to avoid unnecessary confusion.
