### ISSUE TITLE
i18n backend decision

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#64]
In https://opensesame.libelektra.org/ we use gettext-rs for i18n.

Does gettext-rs support hot reloading?

Do you know any better i18n lib?

(Btw. for the frontend we were thinking to use https://react.i18next.com/)

**Comment by kitzbergerg** [comment]
I have never done anything related to i18n so the best I could would be to look through some crates <https://lib.rs/internationalization>.

What do you mean by 
> Does gettext-rs support hot reloading?

gettext-rs uses GNUs gettext (by default statically linked as far as I understand, see <https://crates.io/crates/gettext-rs>). We could switch to dynamic linking and then swap out/update gettext independently of gettext-rs

**Comment by markus2330** [comment]
> so the best I could would be to look through some crates https://lib.rs/internationalization.

I also looked at a few alternatives when deciding for gettext-rs, namely fluent (LangNeg), ICU.  I didn't check for support for hot reloading.

>   Does gettext-rs support hot reloading?
>
> swap out/update gettext independently of gettext-rs (although I have never done that as well and have no idea how/if it would work)

I was mainly thinking about hot reloading the message catalogs, which must always fit with our own code.

But this is low priority, I thought maybe you already know. The probably simpler way is to store the translations in the database. It is actually mostly about translating the enums, which cannot simply have additional translation columns (afaik).

First #65 and #60 should be done.

**Comment by markus2330** [comment]
@Bushuo @badnames @Benjaminimal @absurd-turtle Does someone have experience with i18n in React (Frontend)?

**Comment by absurd-turtle** [comment]
> @Bushuo @badnames @Benjaminimal @absurd-turtle Does someone have experience with i18n in React (Frontend)?

no

**Comment by Bushuo** [comment]
> Does someone have experience with i18n in React (Frontend)?

I have tried out i18next in react once. But do not consider myself as experienced with it.
I have some experience with i18n in angular, as we use this at work. So I know a little bit about how I would not do it 😂

**Comment by Benjaminimal** [comment]
I have only worked with i18n in a python backend project so far.

**Comment by markus2330** [comment]
>  I have tried out i18next in react once. But do not consider myself as experienced with it.

Was it a good experience? Do you think we can simply use it or should we better investigate in options (write a decision)?

**Comment by Bushuo** [comment]
> Was it a good experience? Do you think we can simply use it or should we better investigate in options (write a decision)?

@markus2330 Like discussed in the frontend meeting, I think we can simply use it. Should I attach a PR to this issue?

**Comment by markus2330** [comment]
This issue is also about i18n backend and probably the SQL enums are the only thing left, so probably it is not even worth pulling in an i18n lib. It is not yet decided yet. Anyways, let us focus in this issue on the backend.

For frontend, you are right, we'll simply use i18next and you can attach to the better suited issue #150, I assigned it to you.

**Comment by Bushuo** [comment]
The enums are now being translated via i18next as shown in #235. 
@markus2330 Are there any other tasks to do regarding translation?

**Comment by markus2330** [comment]
Enums are translated perfectly, good job! :heart: There are a few other leftovers, I created #266.
