### ISSUE TITLE
`add_date` is not sent over SSE

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#641]
### Describe the Bug

The PlantDto field `add_date` is not replicated via SSE.

### Steps to Reproduce the Problem

1. Open two browsers with different users.
2. Navigate to the same map e.g. http://localhost:5173/maps/1
3. Add a plant
4. Increase the date by one day
5. Add a plant

### Expected Result

The second plant should only be visible on the browser that added it.
Because the add_date was one day in the future.

### Actual Result

The other browser sees both plants

### PermaplanT version

master

### Operating System

MacOS

### Browser

Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/9990578/a8f8c41a-9cb4-442d-a813-0c61fd33017b)

**Comment by markus2330** [comment]
Thank you for reporting the problem! Probably we also ran into it when I wanted to demonstrate concurrent edit to my mother :wink:
