### ISSUE TITLE
400 Error when fetching plantings in map editor

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#646]
### Describe the Bug

The fetch request for plantings in the map editor throws a Bad Request error.

### Steps to Reproduce the Problem

Open the map editor for any map.

### Expected Result

Map editor loads without issues and if plantings are already placed, they get shown.

### Actual Result

Screen goes blank on load and when plantings are refetched, until the request is completed. No plantings are shown on the map editor, even when there should be some placed.

### PermaplanT version

master

### Operating System

Windows 11

### Browser

Microsoft Edge

### Additional info/logs

Error message from failed plantings request:

``Query deserialize error: missing field `relative_to_date` ``

**Comment by markus2330** [comment]
Thank you for reporting the bug! :heart: 

I cannot reproduce on neither local build of master, pr.permaplant.net, dev.permaplant.net. Probably there is something else that needs to be done (more than opening any map). (maps open nicely and in the local build I verified that there is no 400 Error in the backend)

Can you reproduce it on pr.permaplant.net or dev.permaplant.net.

Did you try to reset the database?

**Comment by ThorbenStaufer** [comment]
I tried it on dev.permaplant.net and permaplant.net before I wrote the issue and encountered this problem, but now it works fine on both.
I don't guess there was a new production release in the meantime, so I don't know what could be the cause of that.
But we should look out in the future if this happens again.
