### ISSUE TITLE
Jenkinsfile: mark duplicated code

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#647]
There is a bit too much repeating inside the two Jenkinsfiles. Also the file will not grow as big as libelektras, but a modularization of the different stages, might make it more readable and maintanable.

Repeated:
- build backend/frontend
- functions node_info and wait_for_db 

Basically all the lines of code from 1 to line 90 are repeated code. Which is around 90% of repeated code in that file.

**Comment by markus2330** [comment]
Would be great if you find a solution for that! :heart:

**Comment by markus2330** [comment]
Btw. both Jenkinsfiles are entry points for different pipelines and this should stay that way.

**Comment by 4ydan** [comment]
> Btw. both Jenkinsfiles are entry points for different pipelines and this should stay that way.

Yes, I will not change that.

**Comment by markus2330** [comment]
As discussed we only want markers what is duplicated.

**Comment by 4ydan** [comment]
Dev/Prod deployment is also very duplicate, could be put in one functin in the future maybe?

## Dev
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/82c62ac5-3803-4dda-af41-cfd62e22c2e8)

## Prod
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/6cb08137-251a-4309-9dc2-141dd8d6fe13)

**Comment by markus2330** [comment]
I still think it is a viable option to keep the duplication. It also makes the Jenkinsfiles independent and we better see if changes actually affect the releases.

But if  #906 works, it is also fine. In any case we should documenting carefully which parts are used where (www, dev, and pr).

**Comment by 4ydan** [comment]
> I still think it is a viable option to keep the duplication. It also makes the Jenkinsfiles independent and we better see if changes actually affect the releases.

I totally agree, for a moment I was also thinking to just close this PR.

**Comment by markus2330** [comment]
We still can revert if you see that the release pipeline is totally broken now.

**Comment by 4ydan** [comment]
We should revert it, I completely forgot that the pipeline is not encapsulated and by importing the other Jenkinsfile the normal pipeline gets executed.
The functions would need to be a in a separate Jenkinsfile.common or something.

**Comment by markus2330** [comment]
Done. So this issue is now as its title say: just mark what is duplicated.
