### ISSUE TITLE
backend architecture

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#65]
We should have full architecture description of how the code in the backend should be structured.

Please use arc42 and a similar style as already started (and also used in Elektra) with Markdown files per chapter.

**Comment by markus2330** [comment]
@kitzbergerg Did you already read through the whole backend code? Are there obvious improvements?

**Comment by kitzbergerg** [comment]
I haven't looked into it in detail, but I noticed a few things.
One thing I remember is:  We should use `From<Error>` or `.map_err()` more often to convert errors and then use `?`. There are quite a few long and somewhat unreadable match statements that could be removed with changes like that.

How do we want to handle that? Can I just start and change the code how I think it would make sense and book it to either this ticket or #60. While doing so I would also create a style guide. Although I'll try to mostly use clippy lints.

For a higher level overview we could use <https://github.com/rust-lang/mdBook> and for code documentation `cargo doc`. Both generate webpages that look in my opinion quite nice (mdBook is used for the [rust book](https://doc.rust-lang.org/book/) and `cargo doc` is what is used in crates.io)

**Comment by markus2330** [comment]
"Obvious" improvements (like making code shorter/more readable/...) you can directly do (simply create PR(s)). For bigger restructuring it is needed to first create architecture/docu/decisions so that I can give my okay first.

> For a higher level overview we could use https://github.com/rust-lang/mdBook and for code documentation cargo doc. 

Sounds good to me! :rocket:

**Comment by kitzbergerg** [comment]
@markus2330 Is there a reason why we use routes instead of macros (see <https://actix.rs/docs/getting-started>). Otherwise I'll refactor that as well in a sensible way.

**Comment by markus2330** [comment]
I don't think there is a special reason for this. (@buenaflor?)

Feel free to refactor if it leads to easier comprehensible code.

**Comment by kitzbergerg** [comment]
Do we want path normalization? (See <https://actix.rs/docs/url-dispatch#path-normalization-and-redirecting-to-slash-appended-routes>)

Currently there we get 404 if we call e.g. `http://localhost:8080/api/seeds/`.  
With normalization both `http://localhost:8080/api/seeds` and `http://localhost:8080/api/seeds/` would match (as well as e.g. `http://localhost:8080/api//seeds/`)

**Comment by markus2330** [comment]
@kitzbergerg  If it doesn't cost performance or doesn't require much additional code it is handy for manual testing (when using curl etc.).

**Comment by kitzbergerg** [comment]
Just found this: https://github.com/actix/examples/blob/f8e3570bd16bcf816070af20f210ce1b4f2fca69/diesel/src/main.rs#L64-L70. Maybe I can build something out of that (although that seems a lot more complicated than just using a different crate).

There is also a lot of discussion here about async diesel: https://github.com/diesel-rs/diesel/issues/399.
Another option would be to switch to [diesel_async](https://github.com/weiznich/diesel_async) (see [here](https://docs.rs/diesel-async/0.2.0/diesel_async/) for doc).

**Comment by markus2330** [comment]
Thank you, these are great investigations!

> This however need further investigation. Unless PermaplanT should really be able to scale with lots of concurrent connections this probably doesn't make a difference.

If PermaplanT gets successful, we hopefully have to deal with many concurrent connections. Uptime is most important (no crashes, no restarts etc.), good performance is 2nd most important non-functional goal (after UI related goals in README.md). These non-functional goals specific to the backend should be also part of the mdBook.

> I have heard some good things about [sqlx](https://github.com/launchbadge/sqlx).

Can you please write a decision for the compile-time checked queries in doc/decisions. Just that we have documented pros/cons of Diesel and alternatives. Changing to [sqlx](https://github.com/launchbadge/sqlx) is not totally off the table if it really is strongly superior. The main questions are if it also supports migrations and postgis datatypes like Diesel does (https://lib.rs/crates/postgis_diesel).

>  https://github.com/actix/examples/blob/f8e3570bd16bcf816070af20f210ce1b4f2fca69/diesel/src/main.rs#L64-L70.
>  According to actix doc we should use web::block: https://actix.rs/docs/databases

These two ways should also be listed as possibilities in the decision.

**Comment by kitzbergerg** [comment]
@markus2330 I think we can close this in favour of #158.
I'll create a new issue for the ORM decision.
