### ISSUE TITLE
CI: Installing mdbook-generate-summary fails

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#655]
I am trying to understand how this error came into existence. Anyone got some insight for me?
This seems to happen inside the docker building stage, which was not really changed for months until this step where the error occurs.
@kitzbergerg 

3months ago:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/9c425a77-e300-46d5-806a-7ef629d23650)

currently:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/db46ebbc-6144-4dd1-ba87-8a461e1e07fd)

And it fails at the fifth line right now.
```
cargo install --git https://github.com/ElektraInitiative/mdbook-generate-summary mdbook-generate-summary
````
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/c681e644-5781-4eb2-a28b-5b8065db04ee)

**Comment by markus2330** [comment]
@4ydan maybe we need to deactivate building of mdbook again so that I can do a release today. Let us discuss it in the meeting.

**Comment by kitzbergerg** [comment]
@4ydan You can change it to the following:

```Dockerfile
FROM rust:1.67.1-slim

RUN apt update && apt install -y libpq-dev curl pkg-config ca-certificates build-essential make perl gcc libc6-dev
RUN cargo install mdbook mdbook-mermaid mdbook-linkcheck
RUN cargo install --git https://github.com/ElektraInitiative/mdbook-generate-summary mdbook-generate-summary --locked
```

There seems to be some breaking change introduces in a version, `--locked` says to use the exact version mentioned in the `Cargo.toml` in the repo.

**Comment by markus2330** [comment]
@kitzbergerg thx for helping out here! :heart:
