### ISSUE TITLE
concurrent editing of maps with the same user

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#658]
### Describe the Bug

concurrent editing of maps does not work with the same user

### Steps to Reproduce the Problem

with two browsers:

1. log in in each of them
2. go to the same map
3. do changes

### Expected Result

that the changes are also shown in the other browser

### Actual Result

the changes are not shown

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by markus2330** [comment]
@Bushuo does concurrent editing of a map works for you? Are there some restrictions someone should know?

**Comment by Bushuo** [comment]
> @Bushuo does concurrent editing of a map works for you? Are there some restrictions someone should know?

Currently it only works with different users.
