### ISSUE TITLE
improve documentation about patch file

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#659]
The patch file itself is just a git diff file, that is read by diesel to make custom adaptations to the schema file.
There are two ways you could fix it:
1. manually update the patch file, so it can correctly detect the location in the schema file, that needs to be updated.
2. delete the old patch file, run diesel to get a filled schema file, manually make the changes in the schema file and then run `git diff -U6 > src/schema.patch` to let git generate a new diff file from your manual changes.

_Originally posted by @ThorbenStaufer in https://github.com/ElektraInitiative/PermaplanT/pull/644#discussion_r1265963174_

**Comment by markus2330** [comment]
The information should be added to https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/backend/05updating_schema_patch.md

**Comment by temmey** [comment]
In general, the information provided by @ThorbenStaufer is accurate, but it takes a long way around to generate a new schema.patch file. However, the way described in the documentation is correct and easier. Therefore, I will make minor adjustments to our current documentation.
