### ISSUE TITLE
Debounce base layer form

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#661]
### Tasks

 The text fields for the base layer need to be extended with Pauls debouncing facilities.
 
At the moment their data is only updated once the user deselects a textfield (=> reacts onBlur event)

### Use case

Base layer

### Related Pull request

https://github.com/ElektraInitiative/PermaplanT/pull/584

**Comment by markus2330** [comment]
Thank you for creating this issue! It is one of the rather urgent issues. I added it to milestone etc.

**Comment by markus2330** [comment]
Looking forward to this.

**Comment by markus2330** [comment]
This is probably the most important left-over of base layer.

**Comment by markus2330** [comment]
Debouncing should be the same as for dates (with green ticks).

**Comment by markus2330** [comment]
@absurd-turtle does it make sense to fix this in #760?

**Comment by absurd-turtle** [comment]
I put it in the current sprint again.

**Comment by absurd-turtle** [comment]
Oh I think this is done already.

**Comment by absurd-turtle** [comment]
I think we should open another ticket with more detailed specification.
I am not 100% sure what needs to be done here.
The hook is already in use instead of the onBlur debounce.
I guess there are no visual indications yet. Is this the only thing that is missing here?

**Comment by markus2330** [comment]
Probably the visual indication is the only user-visible part. But the goal is to unify it that the debouncing works the same everywhere (with the same hook).

**Comment by absurd-turtle** [comment]
I have created a new issue for this #778.
