### ISSUE TITLE
deployment on master fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#665]
### Describe the Bug

https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/master/304/pipeline

### Steps to Reproduce the Problem

trigger master build

### Expected Result

all green :green_circle: 

### Actual Result

```
+ sudo /usr/local/bin/permaplant-deploy.sh dev /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master
+ INSTANCE_PATH=/opt/permaplant/dev
+ BACKEND_BINARY=/home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend/target/release/backend
+ SERVICE=permaplant-dev
+ [[ ! -d /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master ]]
+ [[ ! -d /opt/permaplant/dev ]]
+ cd /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend
+ LC_ALL=C
+ diesel --version
diesel 2.0.1
+ cd /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend
+ LC_ALL=C
+ diesel migration run --locked-schema
Running migration 2023-07-03-165000_heatmap
Failed to run 2023-07-03-165000_heatmap with: column "geometry" of relation "maps" contains null values
script returned exit code 1
```

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by 4ydan** [comment]
I have seen this error in a PR that was probaly merged now.

**Comment by 4ydan** [comment]
This PR https://github.com/ElektraInitiative/PermaplanT/pull/622

**Comment by markus2330** [comment]
Thx! Can you also add the link to the build log?

Btw. the PR must have some changes to migrations...

**Comment by markus2330** [comment]
I agree.

My best guess it that the faulty one is: #595

We don't have yet the #134, so it slipped through (even though being successfully build).

If there are no other ideas, I would revert #595

**Comment by 4ydan** [comment]
I can try some commits out. Up to you.

**Comment by 4ydan** [comment]
I will checkout https://github.com/ElektraInitiative/PermaplanT/pull/595 and test it locally.

**Comment by 4ydan** [comment]
Yes its that branch.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/ff3a19dd-52f6-4dfc-92fa-a6ebbfe57c9d)

**Comment by 4ydan** [comment]
Hm, I cant reproduce it anymore, what should be done after resetting the database to reproduce it?

**Comment by markus2330** [comment]
You cannot reproduce it anymore after your have reset the database, this is in the nature of these migrations.

I created #666 to revert. Unfortunately, it cannot be tested on pr.libelektra.org, so I need to merge to master to see if it works.

**Comment by markus2330** [comment]
Probably the better option is to merge #644 and reset the databases already for this release (and hope we can stay compatible). Let us see if it builds.

**Comment by 4ydan** [comment]
Also should we maybe rethrow the exception to make the pipeline fail or do we leave it like this?

**Comment by markus2330** [comment]
Absolutely! I just noticed that https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/master/303/pipeline also already failed.

As #644 is not ready yet we will probably need to do the resetting of DBs twice.

I already resetted dev.permaplant.net, let us see if https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/master/305/pipeline will work.

**Comment by markus2330** [comment]
Worked! Now release: https://build.libelektra.org/job/PermaPlanT-Folder/job/PermaplanT-Release/13/

**Comment by markus2330** [comment]
Also worked, 0.2.3 is now released!
