### ISSUE TITLE
Use case for versions of layers

### ISSUE THREAD

**Issue by aidnurs** [ElektraInitiative/PermaplanT#67]
**The user should be able to create multiple versions of a layer by executing a simple UI action (duplicate, mark as current)**

---

By transforming this task into an issue, I would like to discuss the topic in detail and not overflow the previous GitHub issue that this task used to belong to.

I suggested the concept of historical tables last time, however, as I've revisited the requirements once again, I would proceed with another proposal. Historical tables store deltas in an additional table and help to rebuild the state to a requested point in time. Such an approach would better suit the undo-redo functionality rather than layers versioning. For the versioning, I suggest keeping all the versions in the same table by allowing the user to name a version and mark it as final. In comparison to historical tables, which would be overkill, this method is simpler and cleaner.

@markus2330 Let me know what you think about it

---

__*EDIT 27.02.2023 18:40:*__

The pseudo-code below represents my idea:

```
DROP TABLE IF EXISTS layers;
DROP TYPE IF EXISTS LAYER_TYPE;

CREATE TYPE LAYER_TYPE AS ENUM (
    'drawing'
    );

CREATE TABLE layers
(
    id                SERIAL PRIMARY KEY,
    type              LAYER_TYPE,
    version_name      VARCHAR,
    is_latest_version BOOLEAN   DEFAULT FALSE,
    created_at        TIMESTAMP DEFAULT now(),
    updated_at        TIMESTAMP DEFAULT now()
)

INSERT INTO public.layers (id, type, version_name, is_latest_version, created_at, updated_at)
VALUES (1, 'drawing', 'v1', FALSE, '2023-02-27 17:33:51.434173', '2023-02-27 17:33:51.434173');

INSERT INTO public.layers (id, type, version_name, is_latest_version, created_at, updated_at)
VALUES (2, 'drawing', 'v2', FALSE, '2023-02-27 17:33:51.434173', '2023-02-27 17:33:51.434173');

INSERT INTO public.layers (id, type, version_name, is_latest_version, created_at, updated_at)
VALUES (3, 'drawing', 'v2.1', TRUE, '2023-02-27 17:33:51.434173', '2023-02-27 17:33:51.434173');
```

**Comment by markus2330** [comment]
Great to hear from you!

> By transforming this task into an issue, I would like to discuss the topic in detail and not overflow the previous GitHub issue that this task used to belong to.

Good idea :+1:

> Such an approach would better suit the undo-redo functionality

We also have an undo functionality, which is more commonly used than the versions. If undo also works after lost network connection, it would be brilliant.

> For the versioning, I suggest keeping all the versions in the same table by allowing the user to name a version and mark it as final.

Yes, I thought along the same lines.

> In comparison to historical tables, which would be overkill, this method is simpler and cleaner.

The question is if it is still overkill, if we can benefit from historical tables anyway because of undo-redo?

> The pseudo-code below represents my idea:

I think this does not yet cover deleted items?

Why would we need `is_latest_version` in every row? (A single place which says that "v2.1" is the latest version for this map should be enough?)

**Comment by aidnurs** [comment]
> The question is if it is still overkill, if we can benefit from historical tables anyway because of undo-redo?
Exactly, it is overkill for the current task i.e. layer versioning but is perfect for the undo-redo of data entities(would prefer to discuss it in its own issue)

> I think this does not yet cover deleted items?
Could you please specify what you mean by deleted items? We should distinguish two concepts here to avoid misunderstandings. Reverting deleted items is part of the undo-redo functionality which is universal for every data entity while versions are a concrete property of a layer. From the layers' point of view, the user cannot revert a deletion once it is gone, however, from the undo-redo perspective, it is possible for every data entity. Hopefully, it is clear.

> Why would we need `is_latest_version` in every row? (A single place which says that "v2.1" is the latest version for this map should be enough?)
Right, the functionality of custom naming of versions was just an idea. In case we do not allow the user to give a name to a version, we will then use fixed sequential version numbers

**Comment by markus2330** [comment]
> Could you please specify what you mean by deleted items?

I mean that in one version¹ an item, e.g. a plant on the map, gets removed, in the other it does not.

> Reverting deleted items

It is not reverting, in the one version¹ you would see the item, in the other you would not.

> Right, the functionality of custom naming of versions was just an idea. In case we do not allow the user to give a name to a version, we will then use fixed sequential version numbers

Yes, you are right, in the versioning¹ use case, sequential version numbers won't do, as it is about different alternatives¹/scenarios¹.

¹ From terminology point of view, we should pick one of the words and define it:

- items, objects, entities ...? For the "???" that can be placed on the map
- versions, alternatives, scenarios, ...? For giving a user the possibility to imagine several "alternative" layers (where only one of them is the chosen one and actually has an effect.)
