### ISSUE TITLE
"Failed to execute drawImage" breaks Map Editor

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#672]
### Describe the Bug

When opening the Map Editor on a map with already placed plantings or when placing a planting on a map, the canvas breaks and shows broken, empty or misplaced plantings.

### Steps to Reproduce the Problem

Open the Map Editor and place a plant.

### Expected Result

The plantings gets shown correctly with its current icon.

### Actual Result

either this:

<img width="1453" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/e3095d19-4e4e-4f45-b308-c2e9a82a4014">

or this:

<img width="1452" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/f7c982a7-1a3b-489b-ac6a-c5a40c5ca8f2">

(pictures taken on the same map with no updates in between, just a page reload)

### PermaplanT version

master (locally)

### Operating System

Windows 11

### Browser

Microsoft Edge

### Additional info/logs

Error message in browser console is as following:

<img width="408" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/a19f738b-bfe4-410f-8342-697d75f45159">

Cannot test on deployed builds, since they do not have plants data.

**Comment by Bushuo** [comment]
@markus2330 
Currently it is not really possible to test for such behaviour.
This uses a the public nextcloud image, but having a test that just tries to fetch an image is not optimal IMO.

There are tools to mock third party APIs in tests like https://mswjs.io/
Do we want to bring this in for testing?

**Comment by markus2330** [comment]
> Currently it is not really possible to test for such behaviour.

Were you able to reproduce it manually?

> Do we want to bring this in for testing?

dev deps are not are big problem, so if it helps you to reproduce, why not?

@4ydan what do you think?

**Comment by 4ydan** [comment]
I'm not quite sure I understand this right. Is the image in a wrong format or do we not know how this error happens?

**Comment by Bushuo** [comment]
> I'm not quite sure if I understand this right. Is the image in a wrong format or do we not know how this error happens?

@4ydan 
I would not write a test that depends upon the configuration of a third party app.

For the test to work an image needs to be added, a public folder needs to be configured, nextcloud needs to be reachable. IMO too many things that could break that don't indicate if the image component actually works with a working api. Hope this explains it.

**Comment by 4ydan** [comment]
I need better technical explanation of how this is supposed to work. So it is fetching the images from next cloud every time u select a plant?

**Comment by Bushuo** [comment]
The bug is not related to an entity.

The component gets the path to an image on nextcloud and tries to load it.

**Comment by 4ydan** [comment]
> @4ydan what do you think? How does this fit in the testing strategy?

If you have this regressions often and can find a minimal solution to include this in your automated testsuite, you should definitely do it. Loading images seems also to be a core functionality of this webapp.
