### ISSUE TITLE
map list visual glitch

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#678]
The maps overview looks like:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/b78307b3-0f87-4f36-b9c5-cb7d65c744d6)

_Originally posted by @markus2330 in https://github.com/ElektraInitiative/PermaplanT/issues/672#issuecomment-1644176510_

**Comment by ThorbenStaufer** [comment]
On it, thanks for the report.

**Comment by markus2330** [comment]
Can you reproduce it?

We can comment it out if the implementation is not very easy.

Urgent now is that we prepare the user study.

**Comment by ThorbenStaufer** [comment]
Never happened to me, but I think I know where the issue is.
I wanted to refactor these Icons to Tablericons for a long time anyway, but I will look at it after im finished with #575.
