### ISSUE TITLE
CI: Jenkinsfile remove all groovylint-disabled comments

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#683]
Working on the pipeline is very tedious in VSCode, maybe I have the wrong extensions but I found some pre-commit hooks that could be added to support groovy linting/formatting. There is also a autofix functionality. I think this should speed up coding in groovy, reduce failed pipelines and enable uniform style between multiple developers.

It would be this one https://github.com/nvuillam/npm-groovy-lint

**Comment by markus2330** [comment]
Great suggestion! Please go ahead.

**Comment by 4ydan** [comment]
Most of the warnings got fixed in #685 but four are skipped with `groovylint-disable`. Will have a look at them in the future, since the pipeline structure will change with upcoming merges and we will eventually get rid of them without any separate effort.

**Comment by markus2330** [comment]
I think this is not worth an issue. If you come across them, you can fix it.
