### ISSUE TITLE
sizes of plant in map editor

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#686]
### Tasks

Currently all plants are about 1m when freshly planted, which is larger than most vegetables. Let us reduce it to 50cm for the user study. (Later @temmey will implement 3 different classes of sizes but I think we cannot do this for the user study already starting next week).

@Bushuo can you do it? It is hopefully only changing a number :pray: 

### Use case

plant_layer

**Comment by Bushuo** [comment]
Yes, it's just changing a number. I will do it.

**Comment by temmey** [comment]
The plant.spread column has already been implemented with the values 'narrow' (less than 15cm), 'medium' (15-61cm), and 'wide' (greater than 61cm). 
I will update the documentation in the following days #654

**Comment by markus2330** [comment]
Great, having the right size for the three classes would be even better. Default size (for plants where we don't know the size) nevertheless should be 50px=50cm.

@temmey better focus on the features for the user study first (latin names).

To have this feature that the plants have the right size according the sizes in the table would be brilliant. What is missing for that? Only frontend?

**Comment by markus2330** [comment]
Default size should be fixed with #707

**Comment by temmey** [comment]
I implemented this with issue #721, but as long as issue #692 is not merged, no effects will be visible since we don't have 'narrow,' 'medium,' and 'wide' in the database yet.

**Comment by temmey** [comment]
Now that I looked at it again, 10px is a little small on the map. We should increase it to 25px.

**Comment by temmey** [comment]
![Screenshot from 2023-07-27 09-42-50](https://github.com/ElektraInitiative/PermaplanT/assets/20745903/e50ec4d4-dd7d-47c6-a6f2-b3e87340c0ae)
from left to right:
10px, 25px, 50px, 100px

**Comment by markus2330** [comment]
@temmey Thx, I'll look into it once I have the mergedDatasets.csv. I think, however, it will be okay, as when planting such little plants one probably will zoom in. More likely we should change the default zoom and/or position (currently 0,0 seems to be in the middle, but it should be more in the right below corner so that the map is shown across the whole screen).

@badnames what do you think about that? Do you know where to change it?

**Comment by markus2330** [comment]
Btw. I just manually resized and 10px=10cm is perfect for little plants. The plants are simply so small.
