### ISSUE TITLE
CI: clippy should be part of cargo-check

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#687]
Currently `cargo clippy` is run as part of cargo-build at the end. `cargo clippy` is probably one of the commands that fails the most, so it should fail fast.
I would suggest replacing the `cargo check` command with `cargo clippy` in the cargo-check job (and removing `cargo check` entirely). As far as I understand clippy is a superset of check, so removing it doesn't matter. The only reason check is in the pipeline is because I inserted it in the beginning and didn't think it would increase the build duration by much.

**Comment by 4ydan** [comment]
Good point. This makes totally sense. The reason it was put like that, is because it benefits to run after cargo build for speed. I will have a look again since the pipeline is way faster now.

**Comment by 4ydan** [comment]
Ok so I tried various positions, for now it is really the best to run before cargo doc, later we can give it its own parallel node when we reach faster execution.

**Comment by 4ydan** [comment]
And yea, as a rust lang devel recently wrote
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/5329bb11-8260-4f30-8007-971fcd6be71c)
The sometimes is a bit unclear but I guess we should be fine removing check?

**Comment by kitzbergerg** [comment]
For a bit of explanation as to why it is best with `cargo doc`:
When compiling Rust code you cannot mix between different modes of compilation. Now that means that for debug and release mode there is no way to combine those. So when running `cargo build --release` and afterwards `cargo build` both times you would have to compile everything. The benefit is that Rust knows which mode was executed and saves the result so you don't have to recompile dependencies when executing `cargo build` again.

For us this matters as we have 3 different compilation modes in the pipeline.
1. Debug mode e.g. `cargo check` or `cargo clippy`.
2. Debug mode + tests: There are some dependencies and some code (marked with `#[cfg(test)]`) which are not compiled using normal debug mode.
3. When compiling for release.

**Comment by 4ydan** [comment]
Yea I have heard a bit about it. [This](https://nnethercote.github.io/2023/07/11/back-end-parallelism-in-the-rust-compiler.html) blog post goes into detail about performance in compilations. I was thinking if we should also run `test --release` maybe.

**Comment by markus2330** [comment]
@kitzbergerg thank you for reporting this! :heart: 

> Debug mode + tests: There are some dependencies and some code (marked with #[cfg(test)]) which are not compiled using normal debug mode.

Why do we need this extra mode? For us the debug mode is basically exclusively to run the tests (and dev work)?

How could we reduce it to 2 compilation modes?

> I was thinking if we should also run test --release maybe.

This would only test compiler bugs, won't it? I don't think we need it.

**Comment by 4ydan** [comment]
> This would only test compiler bugs, won't it? I don't think we need it.

Yes it basically has some different settings. The biggest beeing opt-level 3 instead of 0, non incremental builds, [etc..](https://doc.rust-lang.org/cargo/reference/profiles.html#release). This is probably not worth unless we are doing many unsafe things or have some really critical stuff to test, because it will increase the compile time.
