### ISSUE TITLE
Base Layer: fix and enable automatic scaling

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#689]
### Tasks

 Automatic scaling is currently disabled (by commenting out relevant code pieces) since its currently very buggy.
The goal of this issue is to fix and re-enable it. 

### Use case

Base layer

### Related Pull request

N/A

**Comment by markus2330** [comment]
We don't need to do this for the user study, better to have https://github.com/ElektraInitiative/PermaplanT/milestone/4
