### ISSUE TITLE
Backend + Frontend implementation for UC: Layer Alternatives

### ISSUE THREAD

**Issue by temmey** [ElektraInitiative/PermaplanT#697]
### Tasks

 - [ ]  implement API endpoint 
 - [ ] implement in frontend

pr #696 contains a function to copy a layer and all its associated plantings.

### Use case

Layer Alternatives

### Related Pull request

#696

**Comment by markus2330** [comment]
Thank you for creating the issue! Let us discuss today the prioritization.
