### ISSUE TITLE
several seeds from same plant undistinguishable 

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#698]
### Describe the Bug

- [ ] additional name must be added to the seeds, also in the map when planted

### Steps to Reproduce the Problem

create several seeds from the same plant, e.g. several tomatoes with different additional name

### Expected Result

I can recognize in the plant selection which one is which.

### Actual Result

When clicking on one of the plants, all of them get selected.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/0682b43f-adcc-43ea-8a72-15c6b54c6a96)

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by markus2330** [comment]
Sorting is also the wrong way round: the plant with the latest expiration date is first in the list.

**Comment by markus2330** [comment]
This was already discussed in one of the PRs.

**Comment by markus2330** [comment]
> Sorting is also the wrong way round: the plant with the latest expiration date is first in the list.

I made a separate issue for it: #903

**Comment by badnames** [comment]
Fixed in #951.
