### ISSUE TITLE
fix cors configuration

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#70]
@buenaflor wrote in https://github.com/ElektraInitiative/PermaplanT/issues/35#issuecomment-1405824837
> Currently the backend only allows requests from localhost:5173 or 127.0.0.1:5173 due to cors, see [backend](https://github.com/ElektraInitiative/PermaplanT/blob/master/backend/src/server.rs#L20) but this is something we have to change anyway as soon as we deploy it. Preferrably we add a field to the .env so we can configure it

Do we really need a configuration for it? Is there any reason to add any restriction?

I don't see a problem if some 3-rd party uses our backend.

**Comment by markus2330** [comment]
I just checked, it does not work: when going to https://dev.permaplant.net/seeds/new I immediately get an network error.

The code to be adjusted is:

https://github.com/ElektraInitiative/PermaplanT/blob/6173114c2f1101a71bc25984e3777dc235423064/backend/src/main.rs#L90-L98

Probably action in Frontend is needed, too (#49).

@kitzbergerg wouldn't the folder backend/src/config/ be better suited for the CORS configuration?

**Comment by kitzbergerg** [comment]
Yes it probably fits there better. But for now I would leave it. I'll have to restructure the config module anyways (e.g. routes only kind of fits in there, maybe put that in controller, but I'll have to think about that)

**Comment by kitzbergerg** [comment]
@absurd-turtle we should probably set the allowed_origin like the following: 
1. Define an env variable `HOST_URL` (e.g. http://localhost:8080 or https://dev.permaplant.net)
2. Load that variable into Config
3. Use that variable in allowed origin.

That way you can have different allowed origins based on where you are running the server.

**Comment by absurd-turtle** [comment]
Is this even a cors issue right now? Loading resources from the same origin (e.g. frontend and backend hosted under the same domain permaplant.org) is always allowed.
cors comes into play when we want to fetch resources from a server outside that domain.

Server cors configuration is required when other websites want to use our API or when we want to move the server to a different domain.

**Comment by absurd-turtle** [comment]
@kitzbergerg I created a PR for an env file in the frontend #144. This should fix the issue with loading data from the backend.

**Comment by markus2330** [comment]
So the problem on dev.permaplant.net is fixed after the CI sets VITE_BASE_API_URL as introduced in #145?

**Comment by absurd-turtle** [comment]
I suppose so. Is there a way for me to try to deploy to dev.permaplant.net? Or will it be deployed when #145 is merged?

**Comment by markus2330** [comment]
Yes, simply rebase (otherwise it won't build due to merge conflict) and then maybe say "jenkins build please" (on pushes it actually should be done automatically), then it will be available on pr.libelektra.org

dev.libelektra.org is only master builds. The documentation of CI gets updated in #126, then this should be clear.

**Comment by absurd-turtle** [comment]
I think you meant pr.permaplant.net but I got the idea.

**Comment by markus2330** [comment]
Yes, typo thx, fixed it. :ghost:  As long as it is correct in the documentation we should be fine :angel:

**Comment by absurd-turtle** [comment]
@markus2330 Can this be closed or is there something to do?
