### ISSUE TITLE
provide several base maps

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#701]
### Tasks

Create Base Layer Images with:

- [x] 1x2m (Hochbeet)
- [x] 5x3m (Balkon)
- [x] 5x10m
- [x] 10x10m
- [x] 25x25m
- [x] 50x50m
- [x] 100x100m
- [x] 200x50m
- [x] 300x30m

### Use case

Base Layer.

### Related Pull request

None.

**Comment by badnames** [comment]
![Image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/431f6292-68a2-4fbb-8d0a-25740d28779b)

**Comment by markus2330** [comment]
Great but we can do this tomorrow, as this won't be part of the release. We also asked the participants which size they need and wait for their reply.  Please do the bug fixes first.

**Comment by markus2330** [comment]
I wrote the sizes we need in the top post.

Following changes to your image:

- border should be black
- content (in between border) should be plain white, without anything inside
- there shouldn't be the text "1000x1000 px = 10x10m"
- 100 extra pixels should be added below the border for legend
- north arrow smaller (same height as 1m) and it should be below the border (left side)
- 1m symbol should be below the border (right side)
- also add logo in that space below (middle)

**Comment by badnames** [comment]
So the image will be e.g. 1000x1100px with the legend?
I.e. the legend itself is not part of the defined area?

**Comment by markus2330** [comment]
> So the image will be e.g. 1000x1100px with the legend?
> I.e. the legend itself is not part of the defined area?

Yes, exactly. Very strictly seen the image actually should be 1010x1110px with 5px border on each side.

**Comment by markus2330** [comment]
It looks great, we like it a lot! Only the logo should also have the PermaplanT text next to it (without version number):

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/59e75dc5-8be6-4495-96aa-c59dacef03cc)

Please create all sizes like this and upload them to Nextcloud/Maps/Templates with the size as the name.


I already played around a bit:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/341e95bd-a23a-4fa8-8162-c7b4c62e3662)

**Comment by markus2330** [comment]
@badnames thank you, very well done!
