### ISSUE TITLE
E2E tests

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#715]
### Tasks

 Taken from the done use cases in `doc` and ordered by implementation priority (top highest):

 1. #625 
 (misses wrong username/password scenario)
 3. #707 
(misses private/protected map creation)
 5. translation (only english selection is tested)
 6. #751 
 7. #766
 8. #769
 9. #777
 10. #796
 11. #797
 12. [ ] heatmap (probably via pixel-by-pixel regression tests)

**Comment by markus2330** [comment]
I removed "gridlayer" and added a few other E2E tests. Are all of them feasible?

**Comment by 4ydan** [comment]
Yes, this seems all doable now.

**Comment by 4ydan** [comment]
I think `layers visibility` testing will require image capturing or do you maybe have some other ideas? I could check if the plant is gone on opacity 0 with the left sidebar, but hard to verify if the base layer is invisible, since there is nothing to refer to in the dom.

**Comment by markus2330** [comment]
Yes, to actually test visibility we will need image capturing, same for heatmap (which maybe only need image comparison and not capturing?). I think we should keep the number of such tests (especially doing image capturing) as low as possible, maybe we can make these two the only image comparison test?

I reordered the tasks above to make the image comparison tasks the latest. If possible, this should also be the order of execution, as tests without image comparison probably have much more useful output to find the cause of regressions.

So first we should check if all the layers can be used as intended, and only as final step if there is actually a visible change presented to the user.

**Comment by 4ydan** [comment]
#807 leftover reopened.
