### ISSUE TITLE
base layer for shared maps

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#717]
### Steps to Reproduce the Problem

- someone creates a map and selects a base layer map
- someone else visits the map

### Expected Result

that the base layer map is shown

### Actual Result

no base layer is shown. Probably, PermaplanT searches for an image in the folder of the user, and not of the other user.

### PermaplanT version

master

### Operating System

any

### Browser

any

**Comment by markus2330** [comment]
I was thinking about how we can avoid that all shares go to /PermaplanT and how we can fill up new maps with our default base layers. A possibility might be Nextcloud flows. E.g. in https://github.com/kffl/nextcloud-webhooks there is a hook `Share Created` (but not Share received). For https://github.com/nextcloud/workflow_script I also couldn't find out if there is also an event type for receiving shares (probably not, as it seems it is focused on individual files). So more investigations are needed. Probably it doesn't work without writing our own PHP code.

**Comment by absurd-turtle** [comment]
Hmm, interesting.
We could do a feature request and ask if they think its feasible to send notifications whenever a shared directory is added for a user.

If we do it ourselves we could move the directories in the PHP code directly.
So basically writing a plugin to move a directory to a specific location based on the share options.

**Comment by markus2330** [comment]
Being in contact with some Nextcloud devs is definitely worth a shot, probably they have further input. I hope we are not the first who do something like this. (Using Nextcloud Shares as application data).

> If we do it ourselves we could move the directories in the PHP code directly.
> So basically writing a plugin to move a directory to a specific location based on the share options.

Do you mean a flow plugin or a plugin that provides an end point?

**Comment by absurd-turtle** [comment]
I don't know at this point.
Haven't looked into any of the inner workings of Nextcloud yet.

**Comment by absurd-turtle** [comment]
I was thinking about a normal Nextcloud plugin but I actually don't know enough to say if it is possible.

**Comment by markus2330** [comment]
Yeah, probably best to ask Nextcloud devs if they can give us some hints.
