### ISSUE TITLE
No message when plant doesnt exist

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#718]
### Describe the Bug

I thought to share this with you, maybe its not that important, but then we should update the usecase.

From: Use Case: Search Plants

### Steps to Reproduce the Problem

- open https://dev.permaplant.net/maps/1
- select the plant layer-
- type xyxyx into the search.

### Expected Result

  - No match can be found for what the user was searching for.  
    A message will be displayed that nothing was found.

### Actual Result

No message is displayed.

### PermaplanT version

dev.permaplant.net v0.3.0

### Browser

Opera

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/89890d3a-53e9-40c9-8a7c-916bd9950860)

**Comment by markus2330** [comment]
Yes, this is definitely a usability bug, thx for reporting!

If it is easy to do, it would be great to have for this user study, similar priority as #712.

**Comment by badnames** [comment]
![Image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/2a1c744f-75b1-402e-9b44-5e026cb6aff7

Looks now like this.

**Comment by markus2330** [comment]
Looks great. I am off for today.
