### ISSUE TITLE
improve note field for seed

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#722]
### Tasks

 - [ ] create a large text field to be stored with plantings about a plant in the garden (ideally with markdown formatting including todo lists, e.g. https://github.com/remarkjs/react-markdown with https://github.com/remarkjs/remark-gfm)
 - [ ] maybe also #936 if it is easy to be done together

### Use case

plant_layer

**Comment by badnames** [comment]
Where exactly wold the markdown formatted text be displayed?
At the moment it is only accessible via the create/edit seed form.

**Comment by markus2330** [comment]
There are two places where a markdown-formatted multi-line text should be:

1. instead of  the notes in the seed create/edit form 
![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/d3dea74c-3648-494c-b0b8-2794ef62c997)
2. in the left bottom toolbar

In the left bottom toolbar there should be actually two notes: one of the seeds (if it is a plant connected with a seed) and another about the plants themselves.

**Comment by markus2330** [comment]
But let us first fix the problems before adding something.

**Comment by danielsteinkogler** [comment]
i think [react-md-editor](https://uiwjs.github.io/react-md-editor/) looks pretty cool and could fit our needs. It's a markdown editor with toolbar similar to the one provided by github and seems to be very customizeable.

What do you think @badnames @markus2330 ?

**Comment by badnames** [comment]
Looks promising. 
Have checked how well it integrates with our tailwind themes?

**Comment by markus2330** [comment]
Yes, looks great. We like the changing between code, render and side-by-side.

Missing is:

- some way to add emojis
- that lists can be ticked in the preview
 
Is there maybe some extension or similar? Otherwise, these features seem to be small enough that we could try to file an upstream bug so that it eventually gets added.

Formulas and diagrams are not needed, so if you can disable them, please do.
