### ISSUE TITLE
partial dates not stored

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#723]
### Steps to Reproduce the Problem

- [ ] select a plant
- [ ] change "removal date"'s month+year from the date picker (but no day)

### Expected Result

error (that it successfully only stores month + year is not possible without custom date picker, see below)

### Actual Result

feedback with green tick but nothing gets stored, when clicking again on the plant you see that there is no "removal date"

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by markus2330** [comment]
error message is fine, too

**Comment by Bushuo** [comment]
@markus2330 
That won't work without a custom date picker.
The default one only supports full date specifications. 
Everything else is just null.

If you try the same on the timeline there will be an error.
This is because null is a valid value in the context of the left Toolbar.

**Comment by markus2330** [comment]
Thx for the quick reply.

It is a usability problem. It shouldn't have a green tick when there isn't a valid date which it can save.

I had this problem only for the removal date, as the removal date didn't have any day entered. So implementing #724 would fix most of this usability problem.

**Comment by Bushuo** [comment]
> Thx for the quick reply.
> 
> 
> 
> It is a usability problem. It shouldn't have a green tick when there isn't a valid date which it can save.
> 
> 
> 
> I had this problem only for the removal date, as the removal date didn't have any day entered. So implementing #724 would fix most of this usability problem.

The problem is, there is no way of figuring out what the value of the input is if it is only partial.
The value displayed on the monitor inside the native date input is part of a "closed shadow dom" which is a browser internal.

**Comment by markus2330** [comment]
Thx, tagged it as wontfix for now. Is https://github.com/ElektraInitiative/PermaplanT/issues/724 easy to fix?
