### ISSUE TITLE
npm run merge:datasets doesnt support overrides

### ISSUE THREAD

**Issue by temmey** [ElektraInitiative/PermaplanT#726]
### Describe the Bug

Currently, we make manual changes to 'plants.csv', but npm run merge:datasets does not use this data to generate the new mergedDatasets.csv.

So updates from plants.csv don't get imported into our database at the moment.

### Steps to Reproduce the Problem

1. import .csv files from nextcloud to /scraper/data 
2. run `npm run merge:datasets` 

### Expected Result

`mergedDatasets.csv' should contain data from plants.csv

### Actual Result

`mergedDatasets.csv' doesnt contain data from plants.csv

### PermaplanT version

master

### Operating System

Linux

### Browser

all

**Comment by temmey** [comment]
Currently, I'm planning to use all data in plant.csv as the main source and only import data from our other data sources if there are null values in plant.csv. The issue I see with that is, in the future, we may want to fetch data from Permapeople, Reinsaat, and PracticalPlants. If they make changes to their data, theirs won't be included in our dataset anymore. The simplest solution I see is a simple flag, deciding which data source should be the main one and which data shouldn't be overwritten.

It's not an ideal solution, but datasets running parallel is always a difficult issue to keep the data consistent and correct. Do we  have any other ideas?

**Comment by markus2330** [comment]
Thank you for creating this issue!

This issue is out-of-scope for this sprint. We first need to define the process. And probably it makes sense that we implement the hierarchy first.
