### ISSUE TITLE
Change the naming from "variety" to "plant" in the backend 

### ISSUE THREAD

**Issue by aidnurs** [ElektraInitiative/PermaplanT#73]
Hey @kitzbergerg ,

As we already discussed in the meeting, the problem is that renaming the `variety` table into the `plants` table in the database is not reflected in the backend code(PR #48). The backend code still refers to the `variety` table. Please replace all the backend namings(entities, services, etc.) from `variety` with `plants` to make it consistent again. Feel free to push to the same PR!

Thank you,
Nursultan

**Comment by kitzbergerg** [comment]
There are still some field names in the database named variety (plants has a field variety and seeds has a field variety_id). Please change that as well. Afterwards I'll add my changes.

**Comment by aidnurs** [comment]
Hey @kitzbergerg,

thank you very much for pointing it out! I've pushed it to the branch.

**Comment by kitzbergerg** [comment]
I just pushed. Btw the endpoint in the backend also changed from `/varieties` to `/plants`. You probably have to update the frontend regarding that.
I think I got everything in the backend so I'll close this issue.
