### ISSUE TITLE
grid: improve length indicator

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#744]
### Tasks

@4ydan wrote:
> Maybe the usability of the grid scale on a map could be improved.

Can you elaborate?

### Use case

grid

**Comment by 4ydan** [comment]
Most of the times and with no image it behaves well, but sometimes it just "disappears" almost.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/6731aead-767c-44c1-92e8-52c6a19ced5a)
I would suggest moving that information somewhere where it cant be affected by elements on the canvas. Maybe on the bottom row where the date is?

**Comment by markus2330** [comment]
1. The `Step/History length` is simply debugging information which should be removed. Maybe we should remove it for this release already.
2. It is best if you use more realistic base maps for testing (they are mostly white), we have them in Nextcloud below PermaplanT/Maps

Do these 2 points solve the issue or is there more to it?

**Comment by markus2330** [comment]
@Bushuo can we maybe have the `Step/History length` only for local `dev` builds? Like this react symbol on the top left?
Or is it still needed at all? Or can it be integrated to the other debug information?

**Comment by 4ydan** [comment]
Ah ok, I did not know about `Step/History length`. Yea we should def remove it.
I still think there should be a background to the grid scale information. There will eventually be a case with the color gray.
Or we put it outside of the canvas. That would also solve the problem of it moving/jumping around when moving the canvas.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/f99009e4-9457-436d-8b64-585926aa0a40)
Something like that for example.

**Comment by Bushuo** [comment]
@markus2330 I would remove it completly.
The same information can be accessed with a chrome extension called `Redux DevTools`.
I activated it some time ago.

**Comment by markus2330** [comment]
> Or we put it outside of the canvas. That would also solve the problem of it moving/jumping around when moving the canvas.

That doesn't work as long as we don't have a measurement tool, sometimes you have a length on the map and want to check which length it has.

@4ydan can you remove the lines 217-222 in frontend/src/features/map_planning/components/BaseStage.tsx and fix #725?

**Comment by 4ydan** [comment]
Is it really that issue?
