### ISSUE TITLE
E2E: Flaky tests, map creation fails sometimes

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#746]
The map creation tests seem to fail sometimes because the map they are trying to create already exists.

**Comment by markus2330** [comment]
Do we already know something about it? Why would that map exist, everything should be fresh when the tests start.

Is it maybe some parallel issue that two maps are created at the same time?

**Comment by 4ydan** [comment]
It might be that Gherkin Scenario Outlines do not support parallelism. I still havent researched that.

**Comment by 4ydan** [comment]
I will prio this now, as many pipeline executions seem to have that problem.

**Comment by markus2330** [comment]
Yes, it happens quite often, would be great.

The output and also the execution speed looks to me that there is something going on in parallel, that is why I guessed it could be the problem.

Can you reduce to a single map being created? We can merge that and see if it occurs again somewhere.

**Comment by 4ydan** [comment]
I found one issue. I was pressing the save button twice.
