### ISSUE TITLE
sql reformatting

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#757]
### Describe the Bug

To include this in CI, we will need to fix all these errors first.

### Steps to Reproduce the Problem

root folder of the project

```sh
pre-commit run sqlfluff-fix -a
```

### Expected Result

✔️ 

### Actual Result

FAIL

### PermaplanT version

master

### Operating System

devcontainer rust:1.67.1-slim image

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/cd64460a-0f49-4f5c-93b9-575b673bcfef)

**Comment by temmey** [comment]
pr #765

**Comment by 4ydan** [comment]
To resumup my thoughts and avoid misunderstandings.
For CI it would be best to run two separate hooks if I understand the issue correctly.

```
pre-commit run hook1 -a
pre-commit run hook2 -a
```

If one hook will always throw errors/warnings we will need to make sure to ignore the always thrown errors/warnings, maybe with [downgrading](https://docs.sqlfluff.com/en/stable/configuration.html#:~:text=Errors%20%26%20Files.-,Downgrading%20rules%20to%20warnings,-%C2%B6) or some other methods provided by sqlfluff to make sure real errors dont sneak through.

We have also the possiblity to write a hook in pre-commit that is ignored when running pre-commit locally but can be executed manually inside CI like this:
```
pre-commit run --hook-stage manual manualhook -a
```
If this helps in any way.

https://github.com/ElektraInitiative/PermaplanT/blob/f1f26ab4f8e0fb577fdf9fb29b1e506dbb1809af/ci/Jenkinsfile#L103
Appending the hooks after this hook would include them fully to CI.

**Comment by markus2330** [comment]
I still think it would be best if we find a way to fix the problem within pre-commit. It is not ideal if manual sequences are required (even if they can be put into CI). What about our own hook in pre-commit that executes sqlfluff two times?

Alternatively, I still think it is okay that integer etc. is lower-case. This would solve all the troubles the easiest way, won't it?

**Comment by 4ydan** [comment]
The documentation says 
```
use snake_case for everything except database keywords, which should be UPPERCASE
```
why is INTEGER, TEXT, etc. upper and not lower case, it is not a database keyword

[guidelines](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/guidelines/database.md)
