### ISSUE TITLE
CI: E2E tests cant reach backend sometimes

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#768]
Even though we added a curl command to check if the backend is up, it seems that tests still experience issues.

https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/master/361/pipeline/454

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/b32d0be6-aae6-462d-9658-4fe221ff9fa8)

**Comment by markus2330** [comment]
Thank you for reporting the issue! I assume the problem is that some tests need to be retried? Are we sure it is about the backend not fully up? Maybe there are problems when executing them in parallel?

**Comment by 4ydan** [comment]
In the videos taken by the tests it looked like the redirection to the login page did not work. I assumed the backend wasnt active.
