### ISSUE TITLE
Undo after planting a plant leaves select box behind

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#772]
### Steps to Reproduce the Problem

1. Plant a plant
2. Press undo

### Expected Result

- The plants name to be gone from the left side bar
- The blue selected rectangle to be gone.
- 

### Actual Result

Both expected results are visible.

### PermaplanT version

master

### Operating System

Windows 10 wsl devcontainer

### Browser

Opera

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/a1e20248-6a5b-47c4-ac36-919300e550fd)

**Comment by markus2330** [comment]
@Bushuo can you take a look at this? Is this easy to fix? It is minor for the user study but very annoying for automated tests.

**Comment by Bushuo** [comment]
> @Bushuo can you take a look at this? Is this easy to fix? It is minor for the user study but very annoying for automated tests.

I can look into it.
But I suspect that we will need to make a compromise here. Either we deselect the whole selection on undo, or we leave it like this.
So "multiselect -> undo -> still have a selection" will not work.

**Comment by markus2330** [comment]
Thx, it doesn't need to be tonight. I think removing the the whole selection on undo/changing of dates/changing of layers etc. if any of the selected parts is affected, is no usability problem and has less bugs.

**Comment by markus2330** [comment]
@4ydan this works for me now, hopefully you can continue with your tests now. :rocket:

**Comment by 4ydan** [comment]
Yes, tests pass now, thank you.
