### ISSUE TITLE
Layer add, duplicate and delete button

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#773]
Maybe we should hide these layer buttons when there is no functionality behind it yet.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/c71e4ec8-9bf0-43b8-b61a-979e6772803e)

**Comment by markus2330** [comment]
Yes, very good idea.

@absurd-turtle is this maybe something you can do?

**Comment by markus2330** [comment]
Commenting them out would be enough.

**Comment by absurd-turtle** [comment]
> Yes, very good idea.
> 
> @absurd-turtle is this maybe something you can do?

Sure

**Comment by absurd-turtle** [comment]
Done! See https://github.com/ElektraInitiative/PermaplanT/pull/774

**Comment by markus2330** [comment]
Great job, thx! Good that this was fixed for the user study. The participant was very picky :wink:
