### ISSUE TITLE
Scale not saved

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#775]
### Steps to Reproduce the Problem

- Open a map
- Set a background image
- Set the scale to any number different from 100
- Press maps on the navbar
- Go back to the map

### Expected Result

To be the newly set scale

### Actual Result

Scale is 100

### PermaplanT version

master

### Operating System

Windows 10 wsl devcontainer

### Browser

Opera / Chrome

**Comment by 4ydan** [comment]
It seems like I cant set the scale anymore, this bug is maybe only locally.

**Comment by markus2330** [comment]
@absurd-turtle can you take a look. Maybe the fix #760 is incomplete?

**Comment by 4ydan** [comment]
Seems to work on dev.permaplant

**Comment by 4ydan** [comment]
Ok I can reproduce it on dev.permaplant.

**Comment by markus2330** [comment]
Yes, probably simply disabling rotation is the best fix for now. It is a rarely needed feature anyway. But the real problem could be in the validation introduced in #760. At least I constantly get `BaseLayer validation error` in the JavaScript Console when the error is triggered.

**Comment by absurd-turtle** [comment]
@4ydan Thanks for noticing the bug.
It was indeed an error with my validation.

**Comment by absurd-turtle** [comment]
Should be fixed now. But this is still far from optimal.
The validation should be reflected in the UI and there should be a unified way of doing this with the SimpleInput component.
I suggest creating a new issue for this.
