### ISSUE TITLE
cannot directly visit https://www.permaplant.net/maps/2

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#780]
### Steps to Reproduce the Problem

go to https://www.permaplant.net/maps/2

### Expected Result

map opens

### Actual Result

404

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by lukashartl** [comment]
give me 10 minutes

**Comment by lukashartl** [comment]
fix rolled out 😄 (see infra repo)

**Comment by markus2330** [comment]
Great, everything works again! :heart: Let us call it a day :+1:
