### ISSUE TITLE
Selecting a plant from the search list leaves plant(s) in the map selected

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#787]
### Describe the Bug

After selecting a plant from the search list, an existing selection of plant(s) in the map is retained. Placing the found plant anywhere inside that existing selection will fail, i.e. nothing happens.

### Steps to Reproduce the Problem

- Select one or more plants
- Search for a plant in the search input and select one
- The previous selection is still visible
- Try to place the found plant anywhere inside that existing selection

### Expected Result

A previous selection disappears upon selecting a plant from the search list. Placing the found plant anywhere on the map succeeds.

### Actual Result

The previous selection is retained after selecting a plant from the search list. Placing the found plant anywhere inside that previous selection fails in that nothing happens.

### PermaplanT version

master

### Operating System

Linux, Windows 10

### Browser

Firefox, Chrome 116.0.5845.141

### Additional info/logs

Adapted title, description and results of the bug after identifying that it doesnt make sense retaining any selection after selecting a new plant to place. This will also make the previous problem of _failing to place a plant anywhere inside an existing selection_ obsolete.

**Comment by markus2330** [comment]
@Bushuo is this somehow related to #786 or something different?

**Comment by Bushuo** [comment]
> @Bushuo is this somehow related to #786 or something different?

I don't know, I will look into it.

**Comment by Bushuo** [comment]
I can not exactly reproduce the issue.
On my side, the selection is not lost, but the planting mode is disabled again and the selection is focused.
