### ISSUE TITLE
tour guide: bring clarity if something is actionable

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#789]
### Steps to Reproduce the Problem

take the tour

### Expected Result

there are clear indications when you need to do something

### Actual Result

you carefully need to read the text that you understand that something needs to be done

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by markus2330** [comment]
@ThorbenStaufer as this is occurring again and again (and I am also not totally happy with how it is). I see plenty of options and they don't sound like a lot of effort:

- make the sentence what needs to be done bold
- mark the sentence what needs to be done in a color
- give the whole dialog box a different border/color
- add an action icon to the dialog box
- add an extra paragraph that says what should be done

Probably several of these points should be done to make it very clear.  The main question is: what can be done this weekend?

Important is that these actionable dialog boxes should be always styled the same way and it should be easy to add more such boxes in the future.

Monday+Tuesday are the last two participants. So we should do this little release tomorrow or latest Monday.

**Comment by ThorbenStaufer** [comment]
> give the whole dialog box a different border/color

This is already implemented, but I will enlarge the border.
