### ISSUE TITLE
release deployment

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#79]
- [x] adding a booleanParam to our pipeline
- [x] Setup Prod
- [x] split current dev to separate PR and Dev

**Comment by markus2330** [comment]
This is "only" about deploying www.permaplant.net, monit tasks are moved to later ( #139)

**Comment by markus2330** [comment]
@lukashartl this then should be the last task of #182.

**Comment by lukashartl** [comment]
Yes, I'll work on this one next 🫡

Should we make a separate branch for production, which will automatically build once we merge into it?

Something like a branch called `prod`/`production`?

**Comment by markus2330** [comment]
It is best if we simply manually trigger it. And once it runs through, I tag the commit as released.

**Comment by lukashartl** [comment]
Ok, I'll be adding a booleanParam to our pipeline, which will default to false. When we manually execute it in Jenkins Admin UI we can pass in true and it will deploy to production then.

I'll do this and setting up the three nodes until our next meeting ☺️

**Comment by markus2330** [comment]
I think I would prefer an extra pipeline, then we can differently handle artifact lifetimes etc. and it is easier to see what the last builds of the releases were. Or is there a problem with an extra pipeline I don't see?

**Comment by lukashartl** [comment]
The containers for PR and WWW (prod) are created and will be configured later today.

@markus2330 Is it ok, if I also recreate DEV? I'd like to shrink the disk.

**Comment by markus2330** [comment]
Yes, is okay. Please document in the infrastructure repo their names, IDs and IPs, so that I know which is which. :rocket:

**Comment by lukashartl** [comment]
@markus2330 can you please update the A Record of www.permaplant.net to the community server? I'll be setting everything up later today.

**Comment by markus2330** [comment]
I changed the A record. If there are unforeseen complications, please make a redirection to GitHub in the meantime (as it was before my change of the A record, so that the downtime isn't too long).

Redirections for issues.permaplant.net to GitHub would be great, too :wink: (A record already points to community server).

> I'll be setting everything up later today.

Thank you! :rocket:

**Comment by markus2330** [comment]
https://www.permaplant.net/ says "Hello. Please check back later. " and doesn't redirect as wanted. This is a productive page already given to others (who expect to see some page or GitHub), would be great to not have downtime over night in future.

**Comment by lukashartl** [comment]
So I've created another PR #236 , which makes use of the build parameter `DEPLOY_PROD`.

In Jenkins Admin UI it looks like this:

<img width="344" alt="Bildschirm­foto 2023-04-05 um 14 54 10" src="https://user-images.githubusercontent.com/60550303/230152561-d5fbed8f-fbc1-4669-8c94-baa2c6717985.png">

and then you can see all the parameters:

<img width="444" alt="Bildschirm­foto 2023-04-05 um 14 54 16" src="https://user-images.githubusercontent.com/60550303/230152590-926028c8-60cb-483e-ae7b-2ad8cdbd5cae.png">

@markus2330 Would that suffice? Or do we still want an extra Jenkins Job?

You can **only** override these parameters, when you do a manual build inside Jenkins, so a jenkins account is required (which is good).

**Comment by markus2330** [comment]
If the individual pipeline is too complicated¹ I'll live without it. The advantage of having a separate pipeline is that it makes clear when the production builds happened.

¹ Actually we **only** need deployment in the release pipeline.

**Comment by markus2330** [comment]
> Actually we only need deployment in the release pipeline.

Actually only the commands as written in our frontend+backend README would be executed there. Maybe it is not a bad idea to have a separate implementation so that release deployment still works, even if there are some Docker etc. issues.

**Comment by lukashartl** [comment]
Done in #236
