### ISSUE TITLE
Python code formatter prevents commits

### ISSUE THREAD

**Issue by temmey** [ElektraInitiative/PermaplanT#798]
### Describe the Bug

I can't make a commit because I don't have Python 3.9.2 installed for the Python code formatter - https://github.com/psf/black.
I installed pyenv and installed Python 3.9.2, but in my opinion, it should not be necessary.

Is it possible to allow higher versions?

### Steps to Reproduce the Problem

Make a commit with a higher Python version than 3.9.2.

### Expected Result

Pre-commit should not stop me from committing if I have a higher Python version or did not touch the Python files.

### Actual Result

Can't do commits, even if the changes don't affect Python code.

### PermaplanT version

master

### Operating System

Linux-Fedora

### Browser

not related

### Versions of other relevant software/extensions

Python 3.11.4

### Additional info/logs

relevant content from `.pre-commit-config.yaml`

```
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.9.2
```
`git-error` log

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/chris/.cache/pre-commit/patch1691359287-35901.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/chris/.cache/pre-commit/patch1691359287-35901.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/chris/.cache/pre-commit/repobeds73cr/py_env-python3.9.2', '-p', 'python3.9.2')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9.2'
stderr: (none)
Check the log at /home/chris/.cache/pre-commit/pre-commit.log


```

**Comment by markus2330** [comment]
I agree this is a barrier for newcomers. @temmey thx for reporting! :heart: 

Isn't it possible to specify that newer Python versions are okay, too?

@4ydan do you maybe know something about this?

**Comment by 4ydan** [comment]
Thank you for reporting this, I was not aware of that restriction. Changing `language_version: python3.9.2` to `language_version: python` should probably be the fix.

**Comment by markus2330** [comment]
Great job, thank you! :heart:
