### ISSUE TITLE
create Nextcloud Shares on map creation

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#802]
- [x] Create a new directory in Nextcloud when a map is created.
- [x] Create a Nextcloud Circle with the map name 
- [ ] Share this directory with the PermaplanT Nextcloud circle.
- [ ] Change paths for BaseLayer images

**Comment by markus2330** [comment]
As discussed in #824, we will use group folders instead. I close this issue now, to be opened later when we continue work on it.
