### ISSUE TITLE
Small plant icons

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#803]
### Describe the Bug

When I plant, sometimes the icon of the plant is very small.
I think I have seen this bug already a week ago.

### Steps to Reproduce the Problem

Pick different plants and plant them on the map.

### Expected Result

All plants to have the same icon radius.

Okra (Abelmoschus esculentus) is really small.

### Actual Result

Some are very small.

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Opera

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/5d4dc6c9-c30a-4d49-adee-1924a0339403)

**Comment by 4ydan** [comment]
Oh, maybe its on purpose that they have different sizes, but that one is reeeeally small.

**Comment by markus2330** [comment]
Thx for reporting this issue.

Plants have really different sizes. (Tree vs. a small flower) The default zoom is not really suitable for small plants.

But default zoom should become less important once #742 is implemented.
