### ISSUE TITLE
Select plant that is invisible

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#805]
### Describe the Bug

When I plant something and disable the plant layer visibliy, I can still select the plant

### Steps to Reproduce the Problem

Plant any plant
Press the visibility icon
Select the plant (either point click or drag over the whole canvas)

### Expected Result

No plant to be selected.

### Actual Result

Plant is selected.

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Opera

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/87331954-10b9-4447-b56a-a37718d47c06)

**Comment by markus2330** [comment]
Thank you for reporting this issue!

It sounds to me that this behavior is not really harmful but let us see how it interacts with tablet usage.

**Comment by 4ydan** [comment]
I would have liked to use as a testing method selecting the whole canvas, to see if any plants are on the canvas.

**Comment by markus2330** [comment]
I cannot really reproduce. If for me visibility is off, I also cannot select a plant. This looks to me like the behavior you want?

**Comment by 4ydan** [comment]
Did you select across the whole canvas like that? 
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/7547b297-3ff1-45e2-8287-f0e9d7ad448b)

**Comment by markus2330** [comment]
@tschawax as you dived deep into selections, do you have any idea about that behavior?
