### ISSUE TITLE
Automatically install pre-commit on git clone

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#810]
### Tasks

https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

We could also display a message on every commit instead for opt in.
```
git clone -q https://github.com/asottile/pyupgrade
$ cd pyupgrade/
$ git commit -m 'foo'
pre-commit configuration detected, but `pre-commit install` was never run
```

If we want, we could also put a badge on the root readme.
[![pre-commit](https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit)](https://github.com/pre-commit/pre-commit)

**Comment by markus2330** [comment]
> https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

Or alternatively: we could include it in `make install`?

> If we want, we could also put a badge on the root readme.

:+1:

**Comment by 4ydan** [comment]
pre-commit install is in `make install`, do we close this?
Another alternative option I have found is writing a task.json for vscode users and make pre-commit and other dps install on [folderOpen](https://code.visualstudio.com/docs/editor/tasks#:~:text=Run%20Task%20command.-,folderOpen,-%2D%20The%20task%20will)
