### ISSUE TITLE
cleanup of old doc migration files

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#812]
### Problem

Currently when opening the Mdbook you get greeted with a Changelog.
Also the chapters on the left side are way too many.

The reference below has a sidebar that is barely scrollable.

Our book:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/a13ef215-2a0f-4bcc-a392-b0fd3c12b3ec)

Example1:
https://rust-lang.github.io/mdBook/index.html
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/ea102122-766a-47ba-9bc8-f67374313153)

Example2: (a bigger left nav bar)
https://doc.rust-lang.org/nightly/reference/

### Suggested Solution

- Have an Introduction first page showing either a summary of what there is or duplicate the left side bar for better navigation
- Dont show meeting subchapters
- Dont allow 3 nesting levels (X.X.X is fine but not X.X.X.X)
- Or Create multiple different books(Design, Development, Guidelines, Meetings, Use cases, etc.) each with ther own subpath and own nav bar on the left
- Or split the book in frontend/backend/infrastructure for different teams
- Or fold all chapters per default

**Comment by 4ydan** [comment]
There is also so many blank pages
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/79ac680a-9a24-4524-92b4-4caa9e37ab69)
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/84f79181-62d7-460f-8d12-1a064a4f4543)

**Comment by markus2330** [comment]
Thank you for creating the issue!

> Currently when opening the Mdbook you get greeted with a Changelog.

Why is `C` ordered before `a`? Maybe we rename `CHANGELOG.md` to `changelog.md`?

> Dont show meeting subchapters

I think we can simply remove all old meetings.

> Or Create multiple different books(Design, Development, Guidelines, Meetings, Use cases, etc.) each with ther own subpath and own nav bar on the left

I am afraid this will lead to even more duplication and problems where to put what.

> Or split the book in frontend/backend/infrastructure for different teams

We already have separate documentation for frontend (storybook), backend (API docu) andinfrastructure (private repo). :wink: 

> Or fold all chapters per default

This is an excellent idea. Do you know how to do it?

**Comment by markus2330** [comment]
> There are also blank pages

I hope @temmey can clean them up now after we implemented the hierarchy. (Then we don't need these example migrations anymore).

**Comment by 4ydan** [comment]
> This is an excellent idea. Do you know how to do it?

Dont, know, can have a look.

**Comment by temmey** [comment]
> > There are also blank pages
> 
> I hope @temmey can clean them up now after we implemented the hierarchy. (Then we don't need these example migrations anymore).

will ne done #793
