### ISSUE TITLE
E2E tests map names

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#823]
## Problem

Currently every feature has its own Mapnames (like SUTPlanting, SUTBaselayer etc.) and each worker appends its worker id suffix after that and creates a map with that name.

Somehow the same worker got reassigned to a new test in the same feature, resulting in him not beeing able to create a fresh map, because he already created one with his suffix.
[Here](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/master/383/pipeline)

Additionally, because of the above issue, the tests are looking for the "close planting" window, which cant be found, because on the map used by the test, there was already a planting in the middle, which disrupted the test flow.

Usually when inspecting the failed tests, one is the original first failed test and the other two are the repeats. In this case all three tests showed "Sorry I couldnt store my map ..." which points to the problem that the map already existed when the worker grabbed this test, meaning its the same worker that had already performed a test in that feature suite.

This is also generally speaking a problem, whenever a test retries, the worker tries to create a map with the same name, resulting in some tests actually beeing not retryable.

## Possible Solutions
- Changing the distribution of tests in [`pytest xdist`](https://pytest-xdist.readthedocs.io/en/latest/distribution.html#:~:text=%2D%2Ddist%20load%20(default)%3A) might solve this problem.
- We find a better naming strategy.
- Every tests performs an sql script at the end to delete its map.

**Comment by markus2330** [comment]
> We find a better naming strategy.

:+1: 

Yes, sounds to me that uuid or similar would already solve that problem. The worker ID does not seem to be unique enough for our purpose because, as you found out, the same worker might be reused.

> Changing the distribution of tests in [pytest xdist](https://pytest-xdist.readthedocs.io/en/latest/distribution.html#:~:text=%2D%2Ddist%20load%20(default)%3A) might solve this problem.

Sounds fragile and/or slow, wouldn't go that route.

> Every tests performs an sql script at the end to delete its map.

We already have #788, if the different naming strategy does not fix the problem (fully), we prioritize #788 higher.
