### ISSUE TITLE
Fix Lint groovy findings fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#829]
### Describe the Bug

- [ ] Fix Lint groovy findings fails
- [ ] Why did this slip through to CI? Don't we already execute `pre-commit run --all-files`?

### Steps to Reproduce the Problem

run `pre-commit run --all-files`

### Expected Result

success

### Actual Result

```
Fix Lint groovy findings.................................................Failed
- hook id: fix-npm-groovy-lint
- exit code: 1

/home/markus/Projekte/PermaplanT/ci/Jenkinsfile
  14    warning  Map [time:5, unit:SECONDS] is duplicated.  DuplicateMapLiteral     


npm-groovy-lint results in 2 linted files:
┌─────────┬───────────┬─────────────┬─────────────┬─────────────────┐
│ (index) │ Severity  │ Total found │ Total fixed │ Total remaining │
├─────────┼───────────┼─────────────┼─────────────┼─────────────────┤
│    0    │  'Error'  │      0      │      0      │        0        │
│    1    │ 'Warning' │      1      │      0      │        1        │
│    2    │  'Info'   │      0      │      0      │        0        │
└─────────┴───────────┴─────────────┴─────────────┴─────────────────┘
Failure: 0 error(s) have been found 
 1 warning(s) have been found
```

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by 4ydan** [comment]
Thank you for this finding. We are not performing the groovy lint check in ci because it requires additional packages, which I was not able to install back then. See [#736 ](https://github.com/ElektraInitiative/PermaplanT/pull/736#issuecomment-1655805203)

**Comment by 4ydan** [comment]
The other issue I have is, sometimes the hook doesnt trigger locally.
