### ISSUE TITLE
e2e test failed

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#837]
### Steps to Reproduce the Problem

create a harmless PR

### Expected Result

CI is successfull

### Actual Result

```
E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       waiting for get_by_test_id("canvas").get_by_role("button")
E       ============================================================
```

https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-833/7/pipeline

### PermaplanT version

https://github.com/ElektraInitiative/PermaplanT/pull/833

### Operating System

Linux

### Browser

Firefox

**Comment by 4ydan** [comment]
This looks like #823

**Comment by markus2330** [comment]
Sorry, didn't recognize it as such.
