### ISSUE TITLE
Selection Rectangle does not show up

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#839]
### Describe the Bug

The selection rectangle does not show up as usual.

### Steps to Reproduce the Problem

1. navigate to the map editor.
2. try to make a selection by pressing and dragging.

### Expected Result

The selection rect showing

### Actual Result

A bunch of errors in the console

### PermaplanT version

master

### Operating System

MacOS

### Browser

Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Additional info/logs

Got introducted here 8ecca660188bf532ffe980bdebb716ccd2352bb3

**Comment by markus2330** [comment]
Thank you for reporting this issue! :heart: 

@badnames Please fix this. Can you also write an integration or E2E regression test?

**Comment by markus2330** [comment]
Thx for reporting, is fixed now :heart:
