### ISSUE TITLE
rewrite test protocol to Gherkin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#845]
### Tasks

 - [ ] check what is not yet automated
 - [ ] not-yet-automated tests rewrite in Gherkin

**Comment by 4ydan** [comment]
I just realized the following:

A Test Protocol is usually precedure-driven (more explicit, more steps).
Gherkin is more behavior-driven (shorter, hiding details).

We can still Gherkinize the test protocol, it would just make it less explicit.

**Comment by markus2330** [comment]
> Also information like this gets lost:
>    The message is sent to the chat and appears in Nextcloud.

I don't think that information necessarily needs to be lost, you simply need to be more strict about what a scenario is for. So if you specifically want to add a scenario about a chat message appearing, you can add such a scenario.
