### ISSUE TITLE
Swagger doc for the backend

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#85]
I just found https://github.com/juhaku/utoipa/tree/master. It's able to automatically generate OpenApi doc for structs and endpoints can be annotated with macros. 
According to the example it is also able to create a swagger endpoint (see https://github.com/juhaku/utoipa/blob/master/examples/actix-web-multiple-api-docs-with-scopes/src/main.rs#L27-L36)

**Comment by markus2330** [comment]
Great finding! We were thinking about API blueprint in https://github.com/ElektraInitiative/PermaplanT/issues/2 but we couldn't find something like you proposed.

> According to the example it is also able to create a swagger endpoint

Can you try if it works?  Could we also use it to run automatic tests?

Please write a decision (in doc/decision) about the use of web API documentation+testing. (Also mention API blueprint as considered alternative).
