### ISSUE TITLE
Improve CI time, speed up cargo doc

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#853]
### Tasks

Cargo doc can be speed up a bit, by passing the argument [--no-deps](https://doc.rust-lang.org/cargo/commands/cargo-doc.html#:~:text=browser%20configuration%20option.-,%2D%2Dno%2Ddeps,-Do%20not%20build).
This probably wont be noticeable, but its also not needed to build all docs in CI, unless when deploying the doc later in master.

Local measured times (its mostly diesels doc that takes quite some time)

593 items
cargo doc 
```
real    1m26.270s
user    9m0.065s
sys     1m4.006s
```

360 items
cargo doc --no-deps
```
real    0m55.706s
user    5m3.721s
sys     0m39.660s
```

**Comment by markus2330** [comment]
I am neutral to this. Even with deps included, fundamental types are still external links. With `--no-deps` all the external deps are external links.

@horenso do you have some opinion about this?

**Comment by markus2330** [comment]
Yeah, it is totally a matter of taste/workstyle. With `--no-deps` you might need the browsers's back button more often.

**Comment by 4ydan** [comment]
But these docs are only build for PR/Master builds, where no one is reading these docs anyway, am I right?

**Comment by markus2330** [comment]
Actually it is a repeated wish to finally have these docs available online. And I don't know which variant (pr, dev or www) will be the most popular one. I think we should offer all of them in the same way, simply for consistency.

**Comment by markus2330** [comment]
Probably better to not use this flag. Please reopen if someone disagrees.
