### ISSUE TITLE
Improve CI time, change package.json check

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#854]
### Tasks

The way I implemented the check slows down the pipeline by more than a minute, since we run an additional `npm i`.
Maybe we can simply just compare the two version numbers from the two files, if that is all we want to check, instead of performing this large installation.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/04f3608f-31d2-41ac-b64f-5287f19c4bde)

**Comment by markus2330** [comment]
I don't think that self-implemented version checks will be correct (get all corner cases). And we actually want to check if `npm i` was executed by the developer if needed.

Maybe we simply put this in its own stage and execute it in parallel?

**Comment by 4ydan** [comment]
> Maybe we simply put this in its own stage and execute it in parallel?

Maybe, I will think about it.
