### ISSUE TITLE
Makefile graph

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#855]
### Tasks

- [ ] Add makefile graph to mdbook
- [ ] Generate makefile graph in CI (either on master or release)

Maybe we could make use of [makefile2graph](https://github.com/lindenb/makefile2graph).

Output would look something like this.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/9eb59005-2ca2-42ea-96c6-76800dfa8af5)

**Comment by markus2330** [comment]
Yes, looks nice, please feel free to add it in the mdbook. For me `make help` is enough, though.

**Comment by markus2330** [comment]
Great, please continue to use it for dev, I don't think we need it in the repo, though.
