### ISSUE TITLE
Execute E2E on dev.plermaplant.net

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#856]
>  Yes they get performed only on pr.permaplant.net.
Maybe we would want to run them on dev.permaplant.net when merged to master?

_Originally posted by @4ydan in https://github.com/ElektraInitiative/PermaplanT/pull/846#discussion_r1302986695_

**Comment by markus2330** [comment]
Yes, this is a good idea as there are no other tests before the release.

Such errors are unlikely, though, so I don't think this is high-prior.

**Comment by 4ydan** [comment]
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/07f6ae71-e5eb-422f-9a87-a0abdff27144)
Shouldnt we remove the two stages Deploy PR and E2E tests for PR in the master branch?

**Comment by 4ydan** [comment]
Maybe it would be best to write a separate Jenkinsfile for the master pipeline.

**Comment by markus2330** [comment]
> Shouldnt we remove the two stages Deploy PR and E2E tests for PR in the master branch?

Yes, once we have proper dev E2E test, it does not make sense that way.

**Comment by markus2330** [comment]
> Maybe it would be best to write a separate Jenkinsfile for the master pipeline.

As it is best for you.
