### ISSUE TITLE
Docker images rebuilding frequently

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#858]
This impacts the lead time of the pipeline by a lot. I cant figure out what the image cleanup strategy is. Images are rebuilt multiple times per day it seems, increasing the pipelines lead time by 5-10 minutes, even though nothing has changed in the image.

From [this](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-857/10/pipeline) pipeline run:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/e70da182-de7a-49df-9c99-3a8cc085838a)

This is what it should look like instead:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/d1e09206-53d0-409a-a048-6e4fb6c54818)

**Comment by markus2330** [comment]
Currently, we clean the images twice a day. But this is actually only needed for Elektra (to not get out-of-disc-space errors), maybe we can filter non-Elektra images from this cleanup strategy?
