### ISSUE TITLE
master jobs are broken due to missing Changelog

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#859]
### Steps to Reproduce the Problem

new commits on master

### Expected Result

CI should not do the changelog check on master builds

### Actual Result

https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/master/405/pipeline

### PermaplanT version

master

### Operating System

Linux

### Browser

any

**Comment by 4ydan** [comment]
Ah, that is unfortunate.

Maybe we want to disable some other stages too in master?

Isnt the master pipeline performing exactly the same pipeline that was performed on the PR branch before merging?

**Comment by markus2330** [comment]
> Maybe we want to disable some other stages too in master?

No, the changelog-check is the only exception. (In Elektra it is also like this.)

> Isnt the master pipeline performing exactly the same pipeline that was performed on the PR branch before merging?

Not necessarily:

1. As merging sometimes can be done manually, there is a possibility that master contains something slightly different, e.g. rebased, different merging strategy etc.
2. When merging several PRs, the later ones are not up-to-date with master, so the overall result is also slightly different.

So it is needed to rerun everything on master.
