### ISSUE TITLE
Inconsistent Map/Seed create page

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#866]
## Tasks

- [ ] Different create button texts (one is `Create`, one is `Create Seed`)
- [ ] Different cancel button colors (one is green, one is blue).

A fix to this will break E2E tests.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/b6261d67-7d01-4303-a6e8-27fa6ae00d05)

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/d59f0b29-cc96-4331-a46e-5a9181c64bad)

**Comment by markus2330** [comment]
Thank you for creating the issue! I've split half of it to #873.

> A fix to this will break E2E tests.

@4ydan I think we should get resilient to such little things, at least until we don't have fixed guidelines about that.

@tschawax is there any "objective" better solution for usability in seeds vs. maps or are these differences only a matter of taste?

**Comment by 4ydan** [comment]
> @4ydan I think we should get resilient to such little things, at least until we don't have fixed guidelines about that.

Not everything is using data-testid yet and I dont know if we want everything to have a data-testid.

**Comment by markus2330** [comment]
You are right, we don't want data-testid everywhere. As @Bushuo recommended, we can also use regex, e.g. match on any buttons that are labelled with `.*create.*`, then it does not matter if it is called `Create`, `create seed`, `create plant seed` or similar we might find best at the end of the day. I don't see a disadvantage of being a bit relaxed about the specific text, having a button `don't create a seed` would be a terrible usability anyway.

**Comment by Bushuo** [comment]
@tschawax 
> I would always refrain from relying on any text/labelling whatsoever.

I think it depends on where we want to get our confidence up.
Imo it is reasonable to test for a button with the text 'create' in it.
