### ISSUE TITLE
Seeds fields validation

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#868]
### Describe the Bug

- [x] Letters inside the price field silently get removed after creating/editing
- [x] Error messages not telling what the problem is, e.g. entering 2.99 instead of 2,99 (as done for generation)
- [x] Example of yield should be "Good"/"Gut" to not confuse that also non-numbers are okay

### Steps to Reproduce the Problem

1. Create a new seed with price "A".
3. Create a new seed with price "0.1".
4. Create a new seed with negative price.

### Expected Result

Error message that tells me what is wrong.

### Actual Result

Seed is created.

### PermaplanT version

master

### Operating System

- any

### Browser

- any

**Comment by markus2330** [comment]
Can you please update what is still the case in master?

**Comment by 4ydan** [comment]
All 4 bugs are still present on master.

**Comment by markus2330** [comment]
> All 4 bugs are still present on master.

Thank you for checking again. I can also confirm them.

> I can enter letters inside the price field.

Ok, this is really a severe an nasty problem: silent data loss. This definitely must be fixed, I added release critical to this issue.

> I can enter letters inside the yield field.
> Yield can be negative.

This is no problem, yield is arbitrary text. The example could be better chosen to clarify this.

> Error messages not telling what the problem is (entering 2.99 instead of 2,99).

Yeah, this is bad usability. An error message should be shown on invalid prices, like we have for generation.

@badnames you might want to use zod for this form validation.
