### ISSUE TITLE
seeds fix route

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#873]
### Tasks

- [ ] Rename route from seed end point from `new` to `create`
- [ ] Update frontend guidelines about names of routes

**Comment by markus2330** [comment]
I've split the issue as this is not about usability.

Moved from https://github.com/ElektraInitiative/PermaplanT/issues/866#issue-1869513065
> Different endpoints (one is .../create one is .../new)

Thx, let us settle with create. This should be also updated in frontend guidelines. Probably it would have been better to create a different issue about this, as it is not about usability.

@4ydan I think you mean route instead of API here and it is unrelated to backend? Backend API is afaics only `/api/seeds`. Or do I miss something?

**Comment by 4ydan** [comment]
> @4ydan I think you mean route

Yes thank you for opening this separate issue, I was not sure what to do.
I did not know if it was maybe also /new and /create in the backend. I did not investigate further.

**Comment by 4ydan** [comment]
Also I think the route should be /inventory now not /seeds
