### ISSUE TITLE
Seeds amount/quality field search function

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#875]
### Describe the Bug

Amount and Quality fields have a search function, I dont think this was intended.

### Steps to Reproduce the Problem

Create a new seed.

**Comment by markus2330** [comment]
Can you please describe insofar this is a bug? To me it seems like a probably useless feature (at least as long we don't have much more entries in these enums).

**Comment by 4ydan** [comment]
You are right, bug is a bit too strong for this case. Its really a useless feature.
Also I feel like the typing cursor is barely visible in dark mode, because its also black, but this is very minor.

**Comment by markus2330** [comment]
I think we can close this for now, we will reopen if it somehow disturbs.
