### ISSUE TITLE
additional name rendered wrongly

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#878]
### Describe the Bug

Brassica oleracea palmifolia- austrosaat 'Nero di Toscana' should be changed to Brassica oleracea palmifolia 'Nero di Toscana' - austrosaat, see also doc/database/hierarchy.md

### Steps to Reproduce the Problem

create seed with:

- plant Brassica oleracea palmifolia
- additional name austrosaat

### Expected Result

Brassica oleracea palmifolia 'Nero di Toscana' - austrosaat

### Actual Result

Brassica oleracea palmifolia- austrosaat 'Nero di Toscana'

### PermaplanT version

master

### Operating System

Linux

### Browser

any

### Additional info/logs

This is not release critical but **very** nice to have.

**Comment by markus2330** [comment]
Still present in the release. Another test case:
- Currently rendered: `Cichorium endivia- White Ribbed Frisee 'Nuance'`
- Should be: `Cichorium endivia 'Nuance' - White Ribbed Frisee`

**Comment by markus2330** [comment]
Still rendered wrongly, did I check it wrongly?

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/dfd89b56-7cbb-4769-91f3-8268334fd5fd)

@4ydan can you check? Should be deployed on pr.permaplant.net?

**Comment by 4ydan** [comment]
Still rendered wrongly for me too.

**Comment by markus2330** [comment]
It is now wrong in a different way: "Indian abelia (Abelia triflora - t)"
