### ISSUE TITLE
confidence of specific relations (companion, antagonist, neutral)

### ISSUE THREAD

**Issue by aidnurs** [ElektraInitiative/PermaplanT#88]
**_EDIT 13.03.2023:_**

The main goal of the issue is to define relationships between different plants/genus/subfamily/family. 

In order to keep the discussion in one place, please refer to #89. 

It was originally decided to keep the entire conversation in a PR because the `relations` decision was discussed and fixed during the previous weeks, so there were some minor clarifications and no major researches needed.

**Comment by markus2330** [comment]
Thank you for creating the issue! Can you give a bit context what you want to solve here?

Small update (see also changes/comments in #95 and #89): the strength is not really something we know (at least not from the databases we found so far). We only have confidence with the polyculture algorithm.
