### ISSUE TITLE
Can't undo deletion of a plant

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#887]
### Describe the Bug

Select an existing plant on the map and then delete it. If you now try to undo that deletion it will fail.

### Steps to Reproduce the Problem

1. Select an existing plant (or create a new one and then select it)
2. Click on _Delete Planting_ (respectively _Pflanze löschen_) in the Plant Layer's left toolbar
3. Click on the _Undo_ icon in the Map's toolbar

### Expected Result

After undoing the deletion of a plant, that plant should appear again on the map, placed at its last position right before the deletion happened.

### Actual Result

After undoing the deletion of a plant, nothing happens.

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Chrome 116.0.5845.141

### Additional info/logs

**Be aware**: this bug does not exist on PROD yet but is already part of the current master branch. As such, it might be deemed to be release critical.

**Logs**:
- _Uncaught Error Error: Cannot find selected planting_ upon deletion of the plant
- _Uncaught Error: Cannot reverse action_ as a logical consequence upon attempting to undo that deletion

**Info**:
Both errors are being thrown from _TrackedMapStore_

**Comment by 4ydan** [comment]
> @4ydan can you write an E2E test for deleting and maybe check with git bisect which commit introduced it?
Seems like this commit.
```
root at ☁️ 522f16a94f10 in /workspaces/PermaplanT on 171f4176 [$]
$ git bisect good
d1b36b3b64d19543c323515b1ac1072ee00eb5c7 is the first bad commit
commit d1b36b3b64d19543c323515b1ac1072ee00eb5c7
Author: Bushuo <me@paulbuschmann.com>
Date:   Sun Jul 30 14:07:51 2023 +0200

    feat: handle action errors by reverting

 frontend/src/features/map_planning/store/TrackedMapStore.ts | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)
```
Will open a PR for the test.

**Comment by markus2330** [comment]
@Bushuo can you maybe give us an hint how to solve this problem?

Diff is quite small:

```diff
diff --git a/frontend/src/features/map_planning/store/TrackedMapStore.ts b/frontend/src/features/map_planning/store/TrackedMapStore.ts
index fa8f2920..f28bf002 100644
--- a/frontend/src/features/map_planning/store/TrackedMapStore.ts
+++ b/frontend/src/features/map_planning/store/TrackedMapStore.ts
@@ -109,8 +109,13 @@ export const createTrackedMapSlice: StateCreator<
  * After execution, the ability to redo any undone action is lost.
  */
 function executeAction(action: Action<unknown, unknown>, set: SetFn, get: GetFn) {
+  const snapshot = structuredClone(get());
+
   trackUserAction(action, set);
-  action.execute(get().untrackedState.mapId);
+  action.execute(get().untrackedState.mapId).catch(() => {
+    set(snapshot);
+  });
+
   trackReverseActionInHistory(action, get().step, set, get);
   applyActionToStore(action, set, get);
```

**Comment by Bushuo** [comment]
I can take a look in the evening
