### ISSUE TITLE
Deletion of a plant makes the rotater handle of a Konva transformer appear

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#888]
### Describe the Bug

Upon deletion of a plant, the rotater handle of a Konva transformer is appearing right where the deleted plant was last positioned. A subsequent click anywhere else on the map (except for clicking on either end of the rotater handle itself), makes the rotater disappear again.

### Steps to Reproduce the Problem

1. Select an existing plant (or create a new one and then select it)
2. Click on _Delete Planting_ (respectively _Pflanze löschen_) in the Plant Layer's left toolbar
3. Observe the rotater handle of a Konva transformer appear right where the deleted plant was positioned

### Expected Result

After deleting a plant, nothing is selected or shown instead.

### Actual Result

After deleting a plant, the rotater handle of a Konva transformer is shown right where the deleted plant had been positioned.

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Chrome 116.0.5845.141

### Additional info/logs

**Be aware**: this bug does not exist on PROD yet but is already part of the current master branch. But since a user can anyway continue normally afterwards by just clicking anywhere else on the map, that bug could be seen as minor.

**Logs**:

- _Uncaught Error Error: Cannot find selected planting_ upon deletion of the plant

**Info**:
That error is being thrown from _TrackedMapStore_

**Comment by markus2330** [comment]
Thx, yes, it never harms to have several bug reports for different each problematic behaviors, even if they can easily be fixed together.

**Comment by markus2330** [comment]
@tschawax thx for reporting and telling that it is now fixed.
