### ISSUE TITLE
Placing a new plant onto an existing plant isn't possible

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#890]
### Describe the Bug

Trying to place a new plant onto an existing plant in the map leads to abruptly ending the placement mode and selecting that existing plant.

### Steps to Reproduce the Problem

1. Search for a plant in the search input and select one
2. Place that plant onto an existing plant on the map

### Expected Result

The plant to be placed should appear on top of that existing plant.

### Actual Result

The new plant isn't placed on the map at all and instead, the existing plant is selected and the placement mode stopped.

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Chrome 116.0.5845.142

### Additional info/logs

Not sure if this is a bug or just a necessary feature/enhancement which wasn't considered yet.

**Comment by markus2330** [comment]
Thank you for reporting this bug!
