### ISSUE TITLE
E2E test fail with german locale

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#899]
### Describe the Bug

The tests do not really change the language to english resulting in all tests failing.

### Steps to Reproduce the Problem

Have a browser with the app running in german.

### Expected Result

All tests pass.

### Actual Result

Every single test cant login.

### PermaplanT version

master

### Operating System

any

### Browser

any

**Comment by markus2330** [comment]
Thx for creating the issue! Can you please specify which tests it is about? Is it urgent (master broken etc.) or release-critical (relevant for 3.3)?

**Comment by 4ydan** [comment]
> Is it urgent (master broken etc.)

Ah, I didnt know urgent means master ist broken.
I put urgent, because I thought its urgent for developers to tests manually maybe.

**Comment by markus2330** [comment]
Urgent is if everyone is affected, not if someone might be affected. It does not necessarily need to be a broken master, it could also be if some part of infrastructure is down/non-functional.

But anyway, quick fixes are always appreciated :rose:
