### ISSUE TITLE
persistent undo when deleting a map/plant etc. (cron jobs)

### ISSUE THREAD

**Issue by aidnurs** [ElektraInitiative/PermaplanT#90]
## Goal

Functionality to revert deletion of an element within a period of time. The first version of this feature considers an element to be either a map or a plant for the time being. However, the research done here should be kept general and can be applied to other database entities in the future.

Example sequence:
1. User deletes an element on 21.03.2023 at 12:00
2. User can revert the deletion only until 21.04.2023 at 12:00

## Suggestions from Markus

>1. requires to always keep previous entries, e.g. only mark as removed+time;
>2. with partitioning to keep for at least a month

## Outcomes

Since there is no built-in job handling feature(like cron jobs in Unix systems) in PSQL, we cannot just mark entries to be removed and expect them to fade away. So table partitioning sounds more reasonable in this case from first sight. If we're going to proceed with the partitioning based on the `deleted_at` column, we can run the partitioning process either manually every day, which is 100% no-go for us, or assign it to a PSQL trigger. Unfortunately, there are only on- INSERT/UPDATE/DELETE and no time-based triggers in PSQL. This means we could only run the partitioning e.g. on the insertion of new entries which can occur within a day/week/month or even a year. This means that some entries to be removed could stay in the database for a longer period of time than they should.

My suggestions are:
1. check if we can define cron jobs on the backend level to run the deletion query
     - ```DELETE FROM plants WHERE deleted_at IS NOT NULL and deleted_at < NOW() - INTERVAL '1 month'```
2. or to combine the methods described above
     - we mark entries to be removed from a table by setting the current timestamp in the `deleted_at` column
     - define a trigger on every table change to run the deletion query(not the partitioning)
     - but the problem described above remains
3. other options?

**Comment by markus2330** [comment]
>     check if we can define cron jobs on the backend level to run the deletion query 

Yes, we define cron jobs. @lukashartl do you see some way that we can even define them from within our code here? If not, we can simply have predefined scripts, e.g. `ci/run-daily.sh` and @lukashartl will do the magic that it gets executed daily.

> but the problem described above remains

I don't know to which problem this statement refers. Ideally use decision templates, this makes it more clear (at least for people used to read decisions).

**Comment by aidnurs** [comment]
Hey @lukashartl ,

could you please take a look at PR #130 with a decision regarding this issue? As we've discussed previously with Markus here, we would like to have the functionality either on the backend or on the server level but not on the database side(check the decision for the explanation). Since I wasn't sure how this will look exactly, I kept the Rationale in the decision general, could you please complete the Rationale section with a more precise solution?

Thank you in advance!

**Comment by lukashartl** [comment]
Hey @aidnurs , no problem.

I completely overlooked the mention, sorry for that.

So in essence we are trying to solve the problem of executing tasks in the background at specific times.

> but not on the database side(check the decision for the explanation)

In the decision you are talking about partitioning, but not actually running background tasks. I've only heard of partitioning in the context of performance or availability. Those two don't apply here IMO.

To achieve running jobs in a crontab-like fashion directly inside the Postgres DB, we could use [pg_cron](https://packages.debian.org/bullseye/postgresql-13-cron).

> do you see some way that we can even define them from within our code here?

How about staying inside the rust context? We could do some basic argument parsing and end up with a binary, that could both service both the service as well as running the background task.

For example, we could start the server like this:

```bash
$> ./permaplant server
```

and then run the cron-jobs like this:

```bash
$> ./permaplant cron-daily|cron-hourly
```

This way we just have to add cronjob, that calls the binary with the correct argument.

Maybe there are other things me might want to add to the binary later on. (e.g. look at `occ` from ownCloud/NextCloud, or gitea, ... . These are just some prominent examples that I could think of

If we embed the cron jobs right into the binary this solves other problems as well, but most importantly it makes the deployment really, really easy (we don't have to ship other parts of the repo, just the built binary).

**Comment by Benjaminimal** [comment]
Another option I can see is using an asynchronous task queue.
In previous python projects, I have used [celery](https://github.com/celery/celery/).
I'm not sure if there are any mature equivalents in the rust ecosystem but I found [rusty celery](https://github.com/rusty-celery/rusty-celery) with a quick google.
Maybe you know some alternatives @kitzbergerg @lukashartl ?

Pros:

- You can write it all in rust.
- You can schedule periodic tasks.
- You can fire off tasks to be run later while you continue to fulfill the request.

Cons:

- More complex deployment setup.
  You will need a message broker and some extra worker processes.

**Comment by kitzbergerg** [comment]
The easiest solution would be something like:
```rust
tokio::spawn(async  {
        loop {
            println!("This will be printed every 10secs");
            tokio::time::sleep(Duration::from_secs(10)).await;
        }
    });
```

If you want to run something just once simply remove the loop:
```rust
tokio::spawn(async  {
        println!("This will be printed once");
    });
```

For info: This is basically a new green thread that gets spawned and is then managed by tokio (which is an async runtime in Rust)
With this simple solution however you can't really change the behaviour after the task is spawned. If this is enough it is quite simple to implement.

If  I understood your question correctly you don't actually need a task queue as tokio itself has a thread-pool and you can simply add new tasks/green threads to that and it will automatically run them.

**Comment by Benjaminimal** [comment]
This looks like a good solution as long as we expect to only have one backend process running.
If we would ever need to scale by putting multiple processes behind a load balancer this would get executed multiple times, right?

**Comment by kitzbergerg** [comment]
> This looks like a good solution as long as we expect to only have one backend process running. If we would ever need to scale by putting multiple processes behind a load balancer this would get executed multiple times, right?

That is correct. It will run per service. However I don't think we need to worry about that. There need to be a lot of requests until the backend cannot handle them any more. And if we think about that now we would need something running independently of the backend (separate service) and then things get messy.

**Comment by markus2330** [comment]
We got lots of good input here, e.g. @Benjaminimal  https://github.com/ElektraInitiative/PermaplanT/issues/90#issuecomment-1476829766 and also @lukashartl with pg-cron. This should be added in the decision.

In the backend meeting we said, that @kitzbergerg will have a look if there is an easy Rust solution. So @kitzbergerg please also update the decision with the new aspects mentioned here.

> With this simple solution however you can't really change the behaviour after the task is spawned.

Shouldn't it be possible if you read the information from a configuration variable that is thread-safe?

> If we would ever need to scale by putting multiple processes behind a load balancer this would get executed multiple times, right?

Good point, we definitely need to consider this. But also here the solution seems quite simple: We simply configure only one PermaplanT instance to actually run the maintenance jobs on the DB.

These configuration options shouldn't be added now, Let us do this later when the the overall architecture of the backend is more clear (documented etc.). I also don't want to bring Elektra too soon to PermaplanT, as Elektra is heavily changed at the moment.

**Comment by kitzbergerg** [comment]
> Shouldn't it be possible if you read the information from a configuration variable that is thread-safe?

That is true although it is what I meant with 'simple solution'. As soon as threading is involved you need locks and if you use the wrong one it gets messy. Those locks need to be async (tokio provides locks like that) otherwise the executor gets blocked which has impact on performance. For Rust beginners it is easy to choose the wrong lock/wrong approach (I made mistakes like that a lot and the tricky part is that you normally don't see any difference), so it gets difficult regarding maintenance.

**Comment by kitzbergerg** [comment]
> In the backend meeting we said, that @kitzbergerg will have a look if there is an easy Rust solution. So @kitzbergerg please also update the decision with the new aspects mentioned here.

Do we have a decision about that? If so please link it to this issue. Or do you mean just update the comment above?

**Comment by markus2330** [comment]
It was merged recently in doc/decisions/reversible_deletion.md, you can continue the work from there in a new PR. (You might want to rename/split the decision if needed.)

**Comment by markus2330** [comment]
@ThorbenStaufer just to let you know that this issue and the decision doc/decisions/reversible_deletion.md exists. It will be needed later in for map deletion #323
