### ISSUE TITLE
`cargo deny` needs rust 1.70, but the project is set to 1.67.1

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#909]
>  `cargo deny` needs rust 1.70, but the project is set to 1.67.1

_Originally posted by @4ydan in https://github.com/ElektraInitiative/PermaplanT/issues/879#issuecomment-1721071476_

**Comment by markus2330** [comment]
> It is mentioned in the release procedure as a better alternative to npm audit --omit=dev fix

The text probably is a bit confusing. It is better than npm in its reports but also checks something different: it checks for security problems in the backend, `npm audit` checks for security problems in the frontend.

For me `cargo deny` worked last time, seems like this is a recent change. So we could either use an older version of `cargo deny` or to use some more recent rust dockerimage for that check?

It would be good to at least manually execute it also for the release 3.3.

**Comment by 4ydan** [comment]
```
rustup install 1.70.0
cargo +1.70.0 install --locked cargo-deny 
cargo deny init 
cargo deny check
```

There is quite a big output. Many warnings and three errors

## Error 1
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/9f84fbd2-4f55-4f0a-a14a-a0167af35818)

## Error 2
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/95fd6775-e854-420d-b85e-311d0734ed6a)

## Error 3
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/64bf3354-46fc-4bbf-86a3-bbc8891efd2b)

## Result
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/a10243e4-c09b-4433-8843-b4cd088a949c)

**Comment by markus2330** [comment]
Yes, all 3 errors seem to be important. Can you try to pump the versions?

What is wrong with the licenses?

**Comment by 4ydan** [comment]
> What is wrong with the licenses?

I dont know

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/1212f247-a823-471b-b979-3885c24513a9)

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/180c3bdd-dd30-43eb-9517-0fcf046b6064)

**Comment by markus2330** [comment]
MIT can be allowed.

**Comment by 4ydan** [comment]
Ah I see now, its a config
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/3be58a45-a2bb-4d11-98c0-b45ea4598466)

**Comment by 4ydan** [comment]
We would need to allow all of these, is that ok?
```
    "MIT",
    "ISC",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
```

**Comment by markus2330** [comment]
Can you check if they are compatible to BSD? (more liberate?) I don't know "Unicode-DFS-2016".

**Comment by 4ydan** [comment]
> Can you check if they are compatible to BSD? (more liberate?) I don't know "Unicode-DFS-2016".

I couldnt use the compatibility checker https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-compatibility-checker because Unicode-DFS-2016 doesnt exist there

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/1bb515cd-b418-4bcb-9f2a-f5cac48bff95)
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1766221

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/6a585465-d532-475b-b0ad-8101bbc4a107)
https://www.unicode.org/faq/unicode_license.html#4

Seems to be ok allowing that license.

**Comment by 4ydan** [comment]
ISC: https://joinup.ec.europa.eu/licence/compatibility-check/ISC/BSD-3-Clause looks good
Apache-2.0 https://joinup.ec.europa.eu/licence/compatibility-check/Apache-2.0/BSD-3-Clause looks good

**Comment by markus2330** [comment]
Yes, looks good, thx for looking into it! :heart:
