### ISSUE TITLE
feasibility: undo-redo functionality of the map

### ISSUE THREAD

**Issue by aidnurs** [ElektraInitiative/PermaplanT#91]
## Goal 
The main goal of this task is to understand how to store the state of the map in the database e.g. 5 red colored rectangles are drawn on the map at position XY. 

## Outcomes
The canvas library, that we use, provides a suggestion on how to implement undo-redo functionality with the canvas.

https://konvajs.org/docs/react/Undo-Redo.html
https://konvajs.org/docs/data_and_serialization/Best_Practices.html#page-title

> If you want to save/load simple canvas content you can use the built-in Konva methods: node.toJSON() and Node.create(json). But those methods are useful only in very small apps. In bigger apps it is VERY hard to use those methods. Why? Because the tree structure is usually very complex in larger apps, you may have a lot of event listeners, images, filters, etc. That data is not serializable into JSON (or it is very hard to do that).

In other words, the Konva nodes contain too much information e.g. color or shape which could be set by default. So there is no reason to store them in the database if they are set by default by Konva anyways.

> You just need to save a history of all the state changes within your app. There are many ways to do this. It may be simpler do to that if you use immutable structures.

The statement above should look the following way in our app:
1. we have a simple rectangle of a default size and color at position (20,20) saved in the database from the user's previous session
3. we rebuild the canvas based on the information from (1)
4. canvas is ready to be used
5. user moves it to a new position (40,20)
6. we save the new state of the rectangle to the `state` array, which updates the database

The main drawback of the method is that the structure of the state will be hard to debug and maintain on the frontend side e.g.
```
state[
     {
          timestamp:1,
          root{
              rootProp1,
              rootProp2,
              rootProp3,
              ....
              children:[
                    ...
              ]
           }
     },
     {
          timestamp:2,
          root{
              rootProp1,
              rootProp2,
              rootProp3,
              ....
              children:[
                ....
              ]
           }
     },
]
```

However, on the database level, such a state could be stored in a deserialized way using `JSON.stringify(state)` i.e. convert a root object with all its children into string

**Comment by markus2330** [comment]
Great investigation, thank you!

> The main goal of this task is to understand how to store the state of the map in the database

:+1: Super important!

> undo-redo functionality

Isn't this more or less independent if we implement undo in the database? What about  getting everything new from the backend+redraw from scratch for undo/import/changing layers etc? Would this be too slow?

>  In other words, the Konva nodes contain too much information e.g. color or shape which could be set by default. So there is no reason to store them in the database if they are set by default by Konva anyways.

Absolutely, I think we should basically only store where which plant is and the whole representation is up to the frontend/Konva.

>     we save the new state of the rectangle to the state array, which updates the database

Yes, moving a single object is quite clear. What what about operations that do massive changes, like enabling an layer.

> The main drawback of the method is that the structure of the state will be hard to debug and maintain

Can you propose a structure that is easier to debug and maintain? What would be the disadvantages?

> However, on the database level, such a state could be stored in a deserialized way using JSON.stringify(state) i.e. convert a root object with all its children into string

I don't think we should store any serialized data in the DB. Instead we should have:
- the DB tables have a representation of the real world (4d-coordinates with real-world distances, viewable in QGis or similar)
- the backend (or even PostGIS+[JSON](https://www.postgresql.org/docs/current/functions-json.html) functions within the DB) maps this to a 2D world in JSON (2d-coordinates with representation hints like size+color)
- the frontend/konva beautiful draws the JSON (images, shadows, ...)

For me the main question is how dumb we can make the data for the Kanvas. Is it efficiently possible to always redraw everything on bigger changes? So basically only **not** redraw from scratch on selection and other non-changing events?

@buenaflor what are your thoughts on this?

**Comment by aidnurs** [comment]
Hey @markus2330,

Great questions indeed, thank you!

> Isn't this more or less independent if we implement undo in the database? What about getting everything new from the backend+redraw from scratch for undo/import/changing layers etc? Would this be too slow?

If I got you right(correct me if I'm wrong), you would like to have the undo functionality implemented on the database side i.e. every step/action taken by a user within the canvas stored as a new entry in a table in the database.

At first sight, this could be a solution with total control over the application, unfortunately, it will be one of the slowest ways to accomplish the task from the performance perspective. Just imagine communicating with the backend on every undo action taken by a user on the frontend side. Backend/database calls are expensive compared to the local changes within the frontend.

> Yes, moving a single object is quite clear. What what about operations that do massive changes, like enabling an layer.

Good point here! Semantically this would be a massive change but in reality it is a visibility flag of a layer object. Based on that, I would suggest storing such information, which is not directly part of the canvas, in the same way as I proposed to store the canvas state(see the JSON example below). You're totally right, that we need to traverse through the history of such actions as well. 

Let me provide you with a flow on how I see it in general:

1. User works locally in the canvas
2. The state of the canvas is also modified locally
3. We sync the state to the backend on some custom rule i.e. every 5 seconds or when user is inactive, etc.
4. Both canvas and map information(let me introduce new terms in the glossary: e.g. canvas and map contexts) is stored and reproduced in the same way.
5. User refreshes the app. Frontend local state is fresh
6. Frontend rebuilds the map(canvas objects as well as non-canvas information like layers) from scratch based on the data fetched from the backend

```JSON
{
  "state": [
    {
      "timestamp": 1,
      "stage": {
        "backgroundColor": "0x000000",
        "children": [
          {
            "name": "myRectangle",
            "x": 0,
            "y": 0,
            "children": [
              {
                "name": "myText",
                "x": 0,
                "y": 0,
                "children": []
              }
            ]
          },
          {
            "name": "myCircle",
            "x": 100,
            "y": 100,
            "children": []
          }
        ]
      },
      "layers": {
        "baseLayer": {
          "isEnabled": true,
          "backgroundImage": "http://www.example.com/image.png"
        }
      }
    },
    {
      "timestamp": 2,
      "stage": {
        "backgroundColor": "0x000000",
        "children": [
          {
            "name": "myRectangle",
            "x": 0,
            "y": 0,
            "children": [
              {
                "name": "myText",
                "x": 0,
                "y": 0,
                "children": []
              }
            ]
          },
          {
            "name": "myCircle",
            "x": 100,
            "y": 100,
            "children": []
          }
        ]
      },
      "layers": {
        "baseLayer": {
          "isEnabled": false,
          "backgroundImage": "http://www.example.com/image.png"
        }
      }
    }
  ]
}
```

Answering your question about the coordinate system, I'm not sure yet how PostGIS will fit within the system i.e. which functional parts it covers. Let me do another research on that one.

> For me the main question is how dumb we can make the data for the Kanvas. Is it efficiently possible to always redraw everything on bigger changes? So basically only not redraw from scratch on selection and other non-changing events?

Could you please clarify this question for me? Especially the last sentence

**Comment by markus2330** [comment]
I'll close this, follow up is #135 (please put all relevant information from here into the architecture description)
