### ISSUE TITLE
Release 3.4 (seed names)

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#928]
## Release procedure
- [x] [Finish release critical task](https://github.com/ElektraInitiative/PermaplanT/milestone/5)
- [x] run external link check (change follow-web-links in book.toml and do `mdbook build`)
- [x] fix _real_ security problems
      unfortunately `npm audit --omit=dev fix` does [too much and too little](https://overreacted.io/npm-audit-broken-by-design/),
      `cargo deny` seems to be more helpful
- [x] check/improve reformatting
- [x] check if all issues labelled `release critical` are fixed
- [ ] update mergedDatasets.csv
- [x] manually test dev.permaplant.net according to protocol
- [x] build <https://build.libelektra.org/job/PermaplanT-Release/>
- [x] git tag -s vX.X.X
- [x] git push --tags
- [x] create release PR to pump versions and new section in Changelog
- [x] write announcement

**Comment by markus2330** [comment]
Thank you for creating the issue! I hope we also manage to do some of the optional tasks but I agree there are not 100% release-critical. (E.g. manual tests instead of e2e tests.)

I think it is handy to have the release procedure copied in the top post to see the progress.

#903 and #761 seem to be fixed but are not ticked?

**Comment by 4ydan** [comment]
Top post is updated, looks better now, thank you 👍🏻

**Comment by markus2330** [comment]
@4ydan afaics everything is merged for the release, I think you can release now. #869 and #954 would be nice to have.

**Comment by 4ydan** [comment]
seed data set does not need to be updated I guess?

**Comment by markus2330** [comment]
It should be fixed now.

**Comment by 4ydan** [comment]
we have scrollable elements on the right side, even though there is nothing to scroll.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/5628872f-c0cf-4738-b1b3-76ec7f137f35)

**Comment by 4ydan** [comment]
#969

**Comment by markus2330** [comment]
> we have scrollable elements on the right side, even though there is nothing to scroll.

This is a browser-dependent problem. Can you report the problem? It is not release critical, though.

**Comment by 4ydan** [comment]
> Can you report the problem?

#970

**Comment by markus2330** [comment]
@4ydan please add to the release procedure to check that master succeeded (as first step).
