### ISSUE TITLE
dynamically adjust size of text field

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#936]
https://stackoverflow.com/questions/54917131/how-to-dynamically-adjust-textarea-height-with-react

_Originally posted by @badnames in https://github.com/ElektraInitiative/PermaplanT/issues/935#issuecomment-1740509553_

**Comment by markus2330** [comment]
maybe together with #722, these fields should be the same component anyway.

**Comment by markus2330** [comment]
@danielsteinkogler do you already know if this can be easily done?

**Comment by danielsteinkogler** [comment]
@markus2330 yes, the markdown editor also supports auto resizing

**Comment by danielsteinkogler** [comment]
I just checked it again and there is indeed a feature that allows automatic resizing of the textarea, but it comes with a few "bugs." Firstly, manual resizing no longer works, and secondly, the preview is no longer displayed correctly.

**Comment by markus2330** [comment]
Ok, so let us better not dynamically resize.

**Comment by markus2330** [comment]
Thx for checking! :heart:
