### ISSUE TITLE
Guided Tour: Can't proceed beyond step 8/17 of the plants layer

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#955]
### Describe the Bug

Reaching step 8/17 of the plants layer in the guided tour leads to a dead end. This step 8/17 waits for the user to open the search bar by clicking on the search icon.
The behaviour of the plant search recently changed and now stays opened after selecting a plant from the search results list. This makes this step's action inexecutable and the whole step becomes obsolete as a whole.

### Steps to Reproduce the Problem

1. Start the guided tour
2. Proceed to step 8/17 of the plants layer
3. No chance to get to step 9/17

### Expected Result

It should be possible to proceed beyond any step in the guided tour, so that the tour can be completed.

### Actual Result

The requested action of step 8/17 to click on the search icon is not executable because the search bar is already opened. Hence it's not possible to proceed to the next step 9/17.

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Chrome 117.0.5938.150

**Comment by markus2330** [comment]
Great catch! Thank you for reporting it! :heart:
