### ISSUE TITLE
Timeline: Implement new timeline component

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#958]
Implement the user interface components that allow users to select a specific date using sliders

### Tasks

- [ ] Year, month and day can be individually selected by scrolling, moving sliders or clicking on the elements.
- [ ] Implement a visual indicator to highlight the date selected by the user in the timeline.

### Use case

Timeline Single Selection

**Comment by markus2330** [comment]
Thank you for creating the series of issues. LGTM.

**Comment by danielsteinkogler** [comment]
@markus2330 
In our regular meeting tomorrow i can present a first working version of the timeline in the map view.
