### ISSUE TITLE
master CI broken

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#969]
# ~~Guided tour stuck~~

Edit:

https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/master/453/pipeline

Master doesnt work.

**Comment by markus2330** [comment]
@4ydan can you maybe fix it? I think the related code is quite easy to understand.

It is probably some left-over of #956

**Comment by markus2330** [comment]
Did you test the correct version? Actually it sounds exactly like what was fixed in https://github.com/ElektraInitiative/PermaplanT/pull/956?

**Comment by 4ydan** [comment]
I think its from #911

**Comment by 4ydan** [comment]
hm, I tested on dev.permaplant.net, but also escape doesnt work for me smh

**Comment by markus2330** [comment]
@tschawax do you have some idea about this problem here?

**Comment by 4ydan** [comment]
past 4 jenkins pipelines didnt run on master

**Comment by markus2330** [comment]
I rebuild the latest, it seems to be a GitHub problem?

**Comment by markus2330** [comment]
master succeeded again.
