### ISSUE TITLE
Add documentation for entites/DTOs in the backend

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#97]
As part of #60 all functions, structs and modules need to be documented. Apart from some structs representing the data this is done (#72). This issue represents those leftover structs that still need to be documented.

@markus2330 maybe you can find someone to do that (as I don't know what fields represent what data and how they are used).

**Comment by kitzbergerg** [comment]
To find all structs that still need documentation search for `// TODO: See #97.`.

**Comment by aidnurs** [comment]
Hey guys,

the single table, that I've defined in the database, is called `plant_detail`. The structs that require documentation in the backend were actually implemented by Giancarlo. Therefore, it would be a better match for Giancarlo to address this particular issue in my opinion.

**Comment by aidnurs** [comment]
> @aidnurs it is about the plant_detail table (to be renamed to plants). The plants table is going to be removed (see #35).
> 
> If the structs don't exist already, it would be super-helpful if you can add them. If you struggle with the syntax, you can also add them commented-out.

Sure, I've updated the entity.rs with `plant_detail` and pushed it to #181, however, as I've said there are more structs and data tables marked to be documented, which I don't know much about.

**Comment by markus2330** [comment]
@kitzbergerg is there something like `@copydoc` (from Doxygen) in Rust? Do you have some tips how we can document DTOs and Entities with no/little duplication?

**Comment by kitzbergerg** [comment]
> Why would DTOs or Entities need that?

We don't need that for DTOs and Entities, only for functions. My comment was meant to give a general overview of I think we should use doc.

And like I mentioned I know of nothing/have found nothing similar to doxygen so far. 
Although at the same time I don't really think it is that necessary for Rust. 
It is also less to worry about when you change structs as you can just change the doc as well. 
As far as I'm concerned we don't have that many structs/things to document that we would need something like doxygen.

**Comment by markus2330** [comment]
As discussed, will be done by @yvonnemarkl and @aidnurs

**Comment by markus2330** [comment]
@aidnurs I unassigned you. Yvonne will do this after #229 is merged and you have finished your thesis.
