### ISSUE TITLE
Hide browser scrollbars

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#970]
There is multiple irritating scrollbars around the planting page.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/7107d135-d136-4050-95b9-43272e148c0b)

### Complexity

2

### PermaplanT version

master

### Operating System

any? (Reproduced on Opera, Chrome, Microsoft Edge and Tor Browser)

### Browser

any

**Comment by markus2330** [comment]
Please write which browser etc.
Can you also reproduce with other browsers?

**Comment by 4ydan** [comment]
Reproducable in Opera, Chrome, Microsoft Edge and Tor Browser.

**Comment by markus2330** [comment]
In master or what is deployed on dev.permaplant.net? Please use the bug template in the future.

And is it a regression? If it always was there, I agree it is low prior.

**Comment by 4ydan** [comment]
Updated top post, I didnt select the template, because I didnt think its a bug. I cant remember how it looked before, its just something I realized today.

**Comment by markus2330** [comment]
On Firefox, which I mainly use, they are not there. On Chromium and Vivaldi they are there, however.
