### ISSUE TITLE
Responsiveness: add horizontal scrolling to toolbars

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#981]
### Tasks

 - [x] Add horizontal scrollability to toolbars, so that no content is hidden due to a too narrow toolbar viewport

![toolbar-horizontal-scrolling](https://github.com/ElektraInitiative/PermaplanT/assets/141152959/4b7a407b-9322-4ef6-86ac-775178fbb396)

**Comment by markus2330** [comment]
I am not sure if I understand your proposal here.
The idea is that eventually the toolbars (and its content) get hidden if they are made small enough, see also #335.
