### ISSUE TITLE
Refreshing having guided tour's cancel-confirmation dialog opened leads to completion of tour

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#986]
### Describe the Bug

Clicking on the X in the guided tour opens the confirmation dialog where the user can choose to resume, pause or quit the tour.
If the window is now refreshed, the system automatically sets the tour to completed in the background.

### Steps to Reproduce the Problem

1. Start the guided tour
2. Click on the X in the guided tour to open the cancel-confirmation dialog
3. Refresh the page

### Expected Result

Guided tour should start again after refreshing the page

### Actual Result

Guided tour isn't opened again because it got set to completed

### PermaplanT version

master

### Operating System

Windows 10

### Browser

Chrome 118.0.5993.71

**Comment by markus2330** [comment]
Thank you for reporting this bug!

This is quite unfavorable as refreshing is the only way to change the language of the tour, see #710.
