### ISSUE TITLE
Repeated Error Toasts

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#990]
### Describe the Bug

![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/f6768762-e7f7-4c1a-875d-3c740f3a0ceb)

Identical error toasts are often shown multiple times when a single one would suffice.
This happens because we are currently not keeping track of which error messages are visible.

### Steps to Reproduce the Problem

1. Open up a random map.
2. Select the plant layer.
3. Disconnect from the backend (e.g. by turning of the internet connection)
4. Search for any plant.

### Expected Result

A single error toast tells the user that the server can not be reached.

### Actual Result

The required toast is shown multiple times (See above).

### PermaplanT version

master

### Operating System

Linux pop-os 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 x86_64 x86_64 GNU/Linux

### Browser

Chrome 118.0.5993.70

**Comment by markus2330** [comment]
Thank you for reporting the annoying bug! It is a good idea to find a global solution for that (e.g. suppress identical toasts).
